-- +goose Up
-- Push webhooks (Phase 4, BE-4.4). One row per application that auto-deploys:
-- it records the hook installed on the Git host (hook_id), the shared secret
-- the host signs deliveries with and the public control-plane URL the host
-- posts to. The secret is generated by the control plane and only ever leaves
-- it as part of the hook installation request.
CREATE TABLE application_webhooks (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    application_id uuid NOT NULL REFERENCES applications(id) ON DELETE CASCADE,
    provider text NOT NULL,
    repo text NOT NULL,
    hook_id text NOT NULL DEFAULT '',
    secret text NOT NULL DEFAULT '',
    url text NOT NULL DEFAULT '',
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX application_webhooks_app_idx ON application_webhooks (application_id);

-- webhook_events is the anti-spam ledger: one row per delivery the control
-- plane acted on. Claiming the row before the deployment is queued makes the
-- check-and-insert atomic, so a provider that re-delivers the same commit (or
-- the same delivery GUID) can never start a second deployment — the partial
-- unique indexes below enforce that across every control-plane replica, which
-- an in-memory cache could not. Rows are retained as an audit trail; pruning
-- them is deferred until a scheduled cleanup exists.
CREATE TABLE webhook_events (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    application_id uuid NOT NULL REFERENCES applications(id) ON DELETE CASCADE,
    provider text NOT NULL,
    event text NOT NULL DEFAULT '',
    delivery_id text NOT NULL DEFAULT '',
    ref text NOT NULL DEFAULT '',
    commit_sha text NOT NULL DEFAULT '',
    deployment_id uuid,
    received_at timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX webhook_events_app_commit_idx ON webhook_events (application_id, commit_sha)
    WHERE commit_sha <> '';

CREATE UNIQUE INDEX webhook_events_app_delivery_idx ON webhook_events (application_id, delivery_id)
    WHERE delivery_id <> '';

CREATE INDEX webhook_events_app_idx ON webhook_events (application_id, received_at DESC);

-- An incoming delivery names the repository and branch it was sent for; the
-- control plane resolves applications watching that target through
-- application_webhooks, so the lookup index lives there (provider first,
-- repository folded to lower case like the query).
CREATE INDEX application_webhooks_target_idx
    ON application_webhooks (provider, lower(repo));

-- +goose Down
DROP INDEX IF EXISTS application_webhooks_target_idx;
DROP TABLE IF EXISTS webhook_events;
DROP TABLE IF EXISTS application_webhooks;
