package store

import (
	"context"
	"errors"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/jackc/pgx/v5/pgxpool"

	"github.com/justindeelux/gotham/internal/store/sqlc"
)

// Store aggregates the persistence repositories. It owns the connection pool
// and exposes the typed queries generated by sqlc. Phase 1 replaces the flat
// user methods with dedicated repositories as the auth schema grows.
type Store struct {
	DB      *pgxpool.Pool
	queries *sqlc.Queries

	// BeforeFamilyRevoke is a nil-by-default test seam. RevokeFamilyIfStolen
	// calls it after revoking the family and before committing, so a test can
	// prove the revocation itself runs under the per-user lock (the hook sees
	// the lock still held). Production leaves it nil.
	BeforeFamilyRevoke func()
}

// New wires a Store to an existing pool.
func New(pool *pgxpool.Pool) *Store {
	return &Store{
		DB:      pool,
		queries: sqlc.New(pool),
	}
}

// GetUserByEmail returns the user with the given email. The lookup is
// case-insensitive, backed by the users_email_lower_idx functional index.
func (s *Store) GetUserByEmail(ctx context.Context, email string) (sqlc.User, error) {
	return s.queries.GetUserByEmail(ctx, email)
}

// GetUserByID returns the user with the given ID.
func (s *Store) GetUserByID(ctx context.Context, id pgtype.UUID) (sqlc.User, error) {
	return s.queries.GetUserByID(ctx, id)
}

// CreateSession stores a refresh-token session and returns the stored row.
func (s *Store) CreateSession(ctx context.Context, params sqlc.CreateSessionParams) (sqlc.Session, error) {
	return s.queries.CreateSession(ctx, params)
}

// GetSessionByRefreshHash returns the session with the given refresh-token hash.
func (s *Store) GetSessionByRefreshHash(ctx context.Context, refreshHash string) (sqlc.Session, error) {
	return s.queries.GetSessionByRefreshHash(ctx, refreshHash)
}

// RevokeSession marks the session with the given refresh-token hash as revoked.
// It is idempotent: an unknown or already-revoked token is not an error.
func (s *Store) RevokeSession(ctx context.Context, refreshHash string) error {
	return s.queries.RevokeSession(ctx, refreshHash)
}

// DeleteSession removes the live session with the given refresh-token hash.
// Logout uses it so a replayed logged-out token is a deleted row, not a revoked
// one: the reuse classifier attributes theft only to a still-existing revoked
// row, so the replay cannot force a mass logout. A row that was already rotated
// away is left in place so its reuse evidence survives. It is idempotent: an
// unknown token, or one that is already revoked, deletes nothing and is not an
// error.
func (s *Store) DeleteSession(ctx context.Context, refreshHash string) error {
	return s.queries.DeleteSession(ctx, refreshHash)
}

// RevokeSessionIfLive revokes a live session by its refresh hash and reports
// whether a row was updated. A false result means the session was already
// revoked or deleted, so a rotation racing it must not issue a new session.
func (s *Store) RevokeSessionIfLive(ctx context.Context, refreshHash string) (bool, error) {
	_, err := s.queries.RevokeSessionIfLive(ctx, refreshHash)
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return false, nil
		}
		return false, err
	}
	return true, nil
}

// RevokeFamilyIfStolen atomically classifies a presented refresh token and,
// only for genuine reuse, revokes every live session of its owner. It holds
// the per-user session lock across the re-read and the revocation, so a
// concurrent RotateSession cannot slip a replacement in and a password reset
// (which takes the same lock) cannot interleave.
//
// The token is genuine reuse only when, under the lock, the presented row
// still exists, is revoked, and carries the account's current credential
// version. A deleted row (a password reset) or a stale post-reset chain
// (an obsolete credential version) returns false without touching any session,
// so freshly authenticated sessions are never killed by a stale replay.
func (s *Store) RevokeFamilyIfStolen(ctx context.Context, userID pgtype.UUID, refreshHash string) (bool, error) {
	tx, err := s.DB.Begin(ctx)
	if err != nil {
		return false, err
	}
	defer func() { _ = tx.Rollback(ctx) }()

	queries := s.queries.WithTx(tx)
	if err := queries.LockUserSessions(ctx, sessionLockKey(userID)); err != nil {
		return false, err
	}

	presented, err := queries.GetSessionByRefreshHash(ctx, refreshHash)
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return false, nil // deleted: nothing to attribute
		}
		return false, err
	}
	if presented.UserID != userID {
		// The lock key and the revoked account must agree; a mismatch would
		// revoke the wrong user's family.
		return false, errors.New("store: presented session belongs to another user")
	}
	if !presented.RevokedAt.Valid {
		return false, nil // live (or rotated again): not this replay
	}
	user, err := queries.GetUserByID(ctx, presented.UserID)
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return false, nil
		}
		return false, err
	}
	if presented.CredentialVersion != user.CredentialVersion {
		return false, nil // obsolete post-reset chain: plain 401
	}
	if err := queries.RevokeUserSessions(ctx, presented.UserID); err != nil {
		return false, err
	}
	if s.BeforeFamilyRevoke != nil {
		// The seam sits after the revocation and before the commit: a hook
		// that observes the lock still held proves the revocation itself ran
		// under the per-user lock and not merely the classification.
		s.BeforeFamilyRevoke()
	}
	if err := tx.Commit(ctx); err != nil {
		return false, err
	}
	return true, nil
}

// RotateSession atomically revokes the presented live session and inserts its
// replacement in one statement, so a failed insert or a cancelled request
// cannot consume the user's only refresh token. It returns pgx.ErrNoRows when
// the presented session was no longer live, leaving no replacement behind.
//
// The statement runs inside the same per-user session lock as
// RevokeFamilyIfStolen and ResetUserPassword, so those either run entirely
// before it or entirely after it — never between the revoke and the insert.
func (s *Store) RotateSession(ctx context.Context, userID pgtype.UUID, params sqlc.RotateSessionParams) (sqlc.Session, error) {
	tx, err := s.DB.Begin(ctx)
	if err != nil {
		return sqlc.Session{}, err
	}
	defer func() { _ = tx.Rollback(ctx) }()

	queries := s.queries.WithTx(tx)
	if err := queries.LockUserSessions(ctx, sessionLockKey(userID)); err != nil {
		return sqlc.Session{}, err
	}
	session, err := queries.RotateSession(ctx, params)
	if err != nil {
		return sqlc.Session{}, err
	}
	if err := tx.Commit(ctx); err != nil {
		return sqlc.Session{}, err
	}
	return session, nil
}

// sessionLockKey is the advisory-lock key shared by every session mutation for
// one account.
func sessionLockKey(userID pgtype.UUID) string {
	return uuid.UUID(userID.Bytes).String()
}

// DeleteStaleSessions drops sessions that expired before expiredBefore and
// revoked sessions whose revocation predates revokedBefore, returning how many
// rows were removed. A revoked row stays for the full reuse window so a
// replayed token can still revoke its family; the expired cutoff only buffers
// plain-expired rows before deletion.
func (s *Store) DeleteStaleSessions(ctx context.Context, expiredBefore, revokedBefore time.Time) (int64, error) {
	return s.queries.DeleteStaleSessions(ctx, sqlc.DeleteStaleSessionsParams{
		ExpiredBefore: pgtype.Timestamptz{Time: expiredBefore, Valid: true},
		RevokedBefore: pgtype.Timestamptz{Time: revokedBefore, Valid: true},
	})
}

// CountUsers returns the number of accounts. Zero means registration is open:
// the first account bootstraps the instance (P-A2).
func (s *Store) CountUsers(ctx context.Context) (int64, error) {
	return s.queries.CountUsers(ctx)
}

// UpdateUserPasswordHash replaces the argon2id hash of the account with the
// given email. email must already be normalized (lowercase), as resolved
// through GetUserByEmail.
func (s *Store) UpdateUserPasswordHash(ctx context.Context, email, passwordHash string) error {
	return s.queries.UpdateUserPasswordHash(ctx, sqlc.UpdateUserPasswordHashParams{
		Lower:        email,
		PasswordHash: &passwordHash,
	})
}

// ResetUserPassword replaces the account's password hash, revokes its refresh
// sessions, and bumps its credential version in one transaction, so a partial
// failure can never leave a live session behind a changed password (admin
// reset-password, P-A3). The version bump (P-A5) is what ends a chain whose
// refresh or login is still in flight while this commits: a replacement
// session minted from the old credential carries the pre-bump version and is
// refused by Refresh.
//
// It takes the per-user session lock first, the same lock the reuse classifier
// and the rotation take, so a reset cannot delete sessions out from under an
// in-flight family-revocation decision and let it revoke sessions minted after
// the reset.
func (s *Store) ResetUserPassword(ctx context.Context, userID pgtype.UUID, email, passwordHash string) error {
	tx, err := s.DB.Begin(ctx)
	if err != nil {
		return err
	}
	defer func() { _ = tx.Rollback(ctx) }()

	queries := s.queries.WithTx(tx)
	if err := queries.LockUserSessions(ctx, sessionLockKey(userID)); err != nil {
		return err
	}
	if err := queries.DeleteUserSessions(ctx, userID); err != nil {
		return err
	}
	if err := queries.UpdateUserPasswordHash(ctx, sqlc.UpdateUserPasswordHashParams{
		Lower:        email,
		PasswordHash: &passwordHash,
	}); err != nil {
		return err
	}
	if err := queries.BumpCredentialVersion(ctx, userID); err != nil {
		return err
	}
	return tx.Commit(ctx)
}

// DeleteUserSessions removes every refresh session of a user, so an old token
// chain cannot outlive a password change.
func (s *Store) DeleteUserSessions(ctx context.Context, userID pgtype.UUID) error {
	return s.queries.DeleteUserSessions(ctx, userID)
}

// CreateAPIToken stores a scoped API token (hash only) and returns the row.
func (s *Store) CreateAPIToken(ctx context.Context, params sqlc.CreateAPITokenParams) (sqlc.ApiToken, error) {
	return s.queries.CreateAPIToken(ctx, params)
}

// ListAPITokensByUser returns every API token owned by userID, newest first,
// including revoked tokens so the caller can display their state.
func (s *Store) ListAPITokensByUser(ctx context.Context, userID pgtype.UUID) ([]sqlc.ApiToken, error) {
	return s.queries.ListAPITokensByUser(ctx, userID)
}

// GetAPITokenByHash returns the API token with the given hash.
func (s *Store) GetAPITokenByHash(ctx context.Context, hash string) (sqlc.ApiToken, error) {
	return s.queries.GetAPITokenByHash(ctx, hash)
}

// GetAPITokenByIDAndUser returns the API token with the given ID when it is
// owned by userID.
func (s *Store) GetAPITokenByIDAndUser(ctx context.Context, params sqlc.GetAPITokenByIDAndUserParams) (sqlc.ApiToken, error) {
	return s.queries.GetAPITokenByIDAndUser(ctx, params)
}

// RevokeAPIToken marks an owned, active token as revoked and reports how many
// rows were affected (0 when the token is unknown, not owned, or already
// revoked).
func (s *Store) RevokeAPIToken(ctx context.Context, params sqlc.RevokeAPITokenParams) (int64, error) {
	return s.queries.RevokeAPIToken(ctx, params)
}

// TouchAPITokenLastUsed records when the token was last presented.
func (s *Store) TouchAPITokenLastUsed(ctx context.Context, params sqlc.TouchAPITokenLastUsedParams) error {
	return s.queries.TouchAPITokenLastUsed(ctx, params)
}

// CreateServer stores a managed node and returns the stored row.
func (s *Store) CreateServer(ctx context.Context, params sqlc.CreateServerParams) (sqlc.Server, error) {
	return s.queries.CreateServer(ctx, params)
}

// GetServerByID returns the node with the given ID.
func (s *Store) GetServerByID(ctx context.Context, id pgtype.UUID) (sqlc.Server, error) {
	return s.queries.GetServerByID(ctx, id)
}

// GetServerByNodeID returns the node registered under nodeID.
func (s *Store) GetServerByNodeID(ctx context.Context, nodeID *string) (sqlc.Server, error) {
	return s.queries.GetServerByNodeID(ctx, nodeID)
}

// ListServers returns every managed node, newest first.
func (s *Store) ListServers(ctx context.Context) ([]sqlc.Server, error) {
	return s.queries.ListServers(ctx)
}

// ListServersByTeam returns the active team's nodes plus every legacy node
// (team_id NULL), newest first.
func (s *Store) ListServersByTeam(ctx context.Context, teamID pgtype.UUID) ([]sqlc.Server, error) {
	return s.queries.ListServersByTeam(ctx, teamID)
}

// DeleteServer removes the node with the given ID.
func (s *Store) DeleteServer(ctx context.Context, id pgtype.UUID) error {
	return s.queries.DeleteServer(ctx, id)
}

// UpdateServerAgentInfo records the agent capabilities reported at Register and
// returns the updated row.
func (s *Store) UpdateServerAgentInfo(ctx context.Context, params sqlc.UpdateServerAgentInfoParams) (sqlc.Server, error) {
	return s.queries.UpdateServerAgentInfo(ctx, params)
}

// UpdateServerMetrics records a heartbeat and returns the updated row.
func (s *Store) UpdateServerMetrics(ctx context.Context, params sqlc.UpdateServerMetricsParams) (sqlc.Server, error) {
	return s.queries.UpdateServerMetrics(ctx, params)
}

// SetServerStatus updates a node's lifecycle status and returns the updated row.
func (s *Store) SetServerStatus(ctx context.Context, params sqlc.SetServerStatusParams) (sqlc.Server, error) {
	return s.queries.SetServerStatus(ctx, params)
}

// CreatePrivateKey stores an encrypted SSH private key and returns its metadata.
func (s *Store) CreatePrivateKey(ctx context.Context, params sqlc.CreatePrivateKeyParams) (sqlc.CreatePrivateKeyRow, error) {
	return s.queries.CreatePrivateKey(ctx, params)
}

// GetPrivateKeyByID returns the private key with the given ID, including the
// encrypted material.
func (s *Store) GetPrivateKeyByID(ctx context.Context, id pgtype.UUID) (sqlc.PrivateKey, error) {
	return s.queries.GetPrivateKeyByID(ctx, id)
}

// ListPrivateKeys returns private-key metadata, newest first, without the
// encrypted material.
func (s *Store) ListPrivateKeys(ctx context.Context) ([]sqlc.ListPrivateKeysRow, error) {
	return s.queries.ListPrivateKeys(ctx)
}
