package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgxpool"

	"github.com/justindeelux/gotham/internal/store/sqlc"
)

// Store aggregates the persistence repositories. It owns the connection pool
// and exposes the typed queries generated by sqlc. Phase 1 replaces the flat
// user methods with dedicated repositories as the auth schema grows.
type Store struct {
	DB      *pgxpool.Pool
	queries *sqlc.Queries
}

// New wires a Store to an existing pool.
func New(pool *pgxpool.Pool) *Store {
	return &Store{
		DB:      pool,
		queries: sqlc.New(pool),
	}
}

// GetUserByEmail returns the user with the given email.
func (s *Store) GetUserByEmail(ctx context.Context, email string) (sqlc.User, error) {
	return s.queries.GetUserByEmail(ctx, email)
}

// CreateUser inserts a user with the given email and returns the stored row.
func (s *Store) CreateUser(ctx context.Context, email string) (sqlc.User, error) {
	return s.queries.CreateUser(ctx, email)
}
