// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: api_tokens.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAPIToken = `-- name: CreateAPIToken :one
INSERT INTO api_tokens (user_id, name, hash, scopes)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, name, hash, scopes, last_used_at, revoked_at, created_at
`

type CreateAPITokenParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Name   string      `json:"name"`
	Hash   string      `json:"hash"`
	Scopes []string    `json:"scopes"`
}

func (q *Queries) CreateAPIToken(ctx context.Context, arg CreateAPITokenParams) (ApiToken, error) {
	row := q.db.QueryRow(ctx, createAPIToken,
		arg.UserID,
		arg.Name,
		arg.Hash,
		arg.Scopes,
	)
	var i ApiToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Hash,
		&i.Scopes,
		&i.LastUsedAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getAPITokenByHash = `-- name: GetAPITokenByHash :one
SELECT id, user_id, name, hash, scopes, last_used_at, revoked_at, created_at
FROM api_tokens
WHERE hash = $1
`

func (q *Queries) GetAPITokenByHash(ctx context.Context, hash string) (ApiToken, error) {
	row := q.db.QueryRow(ctx, getAPITokenByHash, hash)
	var i ApiToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Hash,
		&i.Scopes,
		&i.LastUsedAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getAPITokenByIDAndUser = `-- name: GetAPITokenByIDAndUser :one
SELECT id, user_id, name, hash, scopes, last_used_at, revoked_at, created_at
FROM api_tokens
WHERE id = $1
  AND user_id = $2
`

type GetAPITokenByIDAndUserParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) GetAPITokenByIDAndUser(ctx context.Context, arg GetAPITokenByIDAndUserParams) (ApiToken, error) {
	row := q.db.QueryRow(ctx, getAPITokenByIDAndUser, arg.ID, arg.UserID)
	var i ApiToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Hash,
		&i.Scopes,
		&i.LastUsedAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listAPITokensByUser = `-- name: ListAPITokensByUser :many
SELECT id, user_id, name, hash, scopes, last_used_at, revoked_at, created_at
FROM api_tokens
WHERE user_id = $1
ORDER BY created_at DESC, id DESC
`

func (q *Queries) ListAPITokensByUser(ctx context.Context, userID pgtype.UUID) ([]ApiToken, error) {
	rows, err := q.db.Query(ctx, listAPITokensByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ApiToken{}
	for rows.Next() {
		var i ApiToken
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Hash,
			&i.Scopes,
			&i.LastUsedAt,
			&i.RevokedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAPIToken = `-- name: RevokeAPIToken :execrows
UPDATE api_tokens
SET revoked_at = now()
WHERE id = $1
  AND user_id = $2
  AND revoked_at IS NULL
`

type RevokeAPITokenParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) RevokeAPIToken(ctx context.Context, arg RevokeAPITokenParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeAPIToken, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const touchAPITokenLastUsed = `-- name: TouchAPITokenLastUsed :exec
UPDATE api_tokens
SET last_used_at = $2
WHERE id = $1
`

type TouchAPITokenLastUsedParams struct {
	ID         pgtype.UUID        `json:"id"`
	LastUsedAt pgtype.Timestamptz `json:"last_used_at"`
}

func (q *Queries) TouchAPITokenLastUsed(ctx context.Context, arg TouchAPITokenLastUsedParams) error {
	_, err := q.db.Exec(ctx, touchAPITokenLastUsed, arg.ID, arg.LastUsedAt)
	return err
}
