// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: application_domains.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const clearPrimaryApplicationDomains = `-- name: ClearPrimaryApplicationDomains :exec
UPDATE application_domains
SET is_primary = false, updated_at = now()
WHERE application_id = $1 AND is_primary
`

// ClearPrimaryApplicationDomains drops the primary flag of an application
// before a promotion, so the partial unique index never sees two primaries.
func (q *Queries) ClearPrimaryApplicationDomains(ctx context.Context, applicationID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, clearPrimaryApplicationDomains, applicationID)
	return err
}

const createApplicationDomain = `-- name: CreateApplicationDomain :one
INSERT INTO application_domains (application_id, domain, is_primary, disabled)
VALUES ($1, $2, $3, $4)
RETURNING id, application_id, domain, is_primary, disabled, created_at, updated_at
`

type CreateApplicationDomainParams struct {
	ApplicationID pgtype.UUID `json:"application_id"`
	Domain        string      `json:"domain"`
	IsPrimary     bool        `json:"is_primary"`
	Disabled      bool        `json:"disabled"`
}

func (q *Queries) CreateApplicationDomain(ctx context.Context, arg CreateApplicationDomainParams) (ApplicationDomain, error) {
	row := q.db.QueryRow(ctx, createApplicationDomain,
		arg.ApplicationID,
		arg.Domain,
		arg.IsPrimary,
		arg.Disabled,
	)
	var i ApplicationDomain
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.Domain,
		&i.IsPrimary,
		&i.Disabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteApplicationDomain = `-- name: DeleteApplicationDomain :exec
DELETE FROM application_domains WHERE id = $1 AND application_id = $2
`

type DeleteApplicationDomainParams struct {
	ID            pgtype.UUID `json:"id"`
	ApplicationID pgtype.UUID `json:"application_id"`
}

func (q *Queries) DeleteApplicationDomain(ctx context.Context, arg DeleteApplicationDomainParams) error {
	_, err := q.db.Exec(ctx, deleteApplicationDomain, arg.ID, arg.ApplicationID)
	return err
}

const deleteApplicationDomainsByApplication = `-- name: DeleteApplicationDomainsByApplication :exec
DELETE FROM application_domains WHERE application_id = $1
`

func (q *Queries) DeleteApplicationDomainsByApplication(ctx context.Context, applicationID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteApplicationDomainsByApplication, applicationID)
	return err
}

const getApplicationDomainByNameAnyApp = `-- name: GetApplicationDomainByNameAnyApp :one
SELECT id, application_id, domain, is_primary, disabled, created_at, updated_at FROM application_domains
WHERE lower(domain) = lower($1)
ORDER BY created_at, id
LIMIT 1
`

// GetApplicationDomainByNameAnyApp resolves the platform-wide claim on a
// host for the uniqueness guard (JUS-89): any application's row, including
// disabled ones, keeps its claim paused rather than released.
func (q *Queries) GetApplicationDomainByNameAnyApp(ctx context.Context, lower string) (ApplicationDomain, error) {
	row := q.db.QueryRow(ctx, getApplicationDomainByNameAnyApp, lower)
	var i ApplicationDomain
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.Domain,
		&i.IsPrimary,
		&i.Disabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listApplicationDomainsByApplication = `-- name: ListApplicationDomainsByApplication :many
SELECT id, application_id, domain, is_primary, disabled, created_at, updated_at FROM application_domains
WHERE application_id = $1
ORDER BY is_primary DESC, created_at, id
`

// ListApplicationDomainsByApplication returns one application's domains, the
// primary first, then oldest first. The order is the routing and promotion
// order: generation names the primary router after the application, and
// removing the primary promotes the next row deterministically (JUS-89).
func (q *Queries) ListApplicationDomainsByApplication(ctx context.Context, applicationID pgtype.UUID) ([]ApplicationDomain, error) {
	rows, err := q.db.Query(ctx, listApplicationDomainsByApplication, applicationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ApplicationDomain{}
	for rows.Next() {
		var i ApplicationDomain
		if err := rows.Scan(
			&i.ID,
			&i.ApplicationID,
			&i.Domain,
			&i.IsPrimary,
			&i.Disabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProxiedApplicationDomains = `-- name: ListProxiedApplicationDomains :many
SELECT d.application_id, a.server_id, d.domain, d.is_primary, d.disabled, d.created_at, d.id
FROM application_domains d
JOIN applications a ON a.id = d.application_id
ORDER BY a.created_at, a.id, d.is_primary DESC, d.created_at, d.id
`

type ListProxiedApplicationDomainsRow struct {
	ApplicationID pgtype.UUID        `json:"application_id"`
	ServerID      pgtype.UUID        `json:"server_id"`
	Domain        string             `json:"domain"`
	IsPrimary     bool               `json:"is_primary"`
	Disabled      bool               `json:"disabled"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	ID            pgtype.UUID        `json:"id"`
}

// ListProxiedApplicationDomains feeds the Traefik generator (JUS-89): every
// domain row joined to its application's node, ordered deterministically so
// generation input is stable. Disabled rows are included with their flag so
// the generator can report them as diagnostics instead of silently dropping
// them.
func (q *Queries) ListProxiedApplicationDomains(ctx context.Context) ([]ListProxiedApplicationDomainsRow, error) {
	rows, err := q.db.Query(ctx, listProxiedApplicationDomains)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProxiedApplicationDomainsRow{}
	for rows.Next() {
		var i ListProxiedApplicationDomainsRow
		if err := rows.Scan(
			&i.ApplicationID,
			&i.ServerID,
			&i.Domain,
			&i.IsPrimary,
			&i.Disabled,
			&i.CreatedAt,
			&i.ID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateApplicationDomain = `-- name: UpdateApplicationDomain :one
UPDATE application_domains
SET domain = $2,
    is_primary = $3,
    disabled = $4,
    updated_at = now()
WHERE id = $1
RETURNING id, application_id, domain, is_primary, disabled, created_at, updated_at
`

type UpdateApplicationDomainParams struct {
	ID        pgtype.UUID `json:"id"`
	Domain    string      `json:"domain"`
	IsPrimary bool        `json:"is_primary"`
	Disabled  bool        `json:"disabled"`
}

func (q *Queries) UpdateApplicationDomain(ctx context.Context, arg UpdateApplicationDomainParams) (ApplicationDomain, error) {
	row := q.db.QueryRow(ctx, updateApplicationDomain,
		arg.ID,
		arg.Domain,
		arg.IsPrimary,
		arg.Disabled,
	)
	var i ApplicationDomain
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.Domain,
		&i.IsPrimary,
		&i.Disabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
