// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: backups.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createBackup = `-- name: CreateBackup :one
INSERT INTO backups (
    id, database_id, schedule_id, type, status, size, location,
    target_id, container_id, error, finished_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, database_id, schedule_id, type, status, size, location, target_id, container_id, error, created_at, finished_at
`

type CreateBackupParams struct {
	ID          pgtype.UUID        `json:"id"`
	DatabaseID  pgtype.UUID        `json:"database_id"`
	ScheduleID  pgtype.UUID        `json:"schedule_id"`
	Type        string             `json:"type"`
	Status      string             `json:"status"`
	Size        int64              `json:"size"`
	Location    string             `json:"location"`
	TargetID    pgtype.UUID        `json:"target_id"`
	ContainerID string             `json:"container_id"`
	Error       string             `json:"error"`
	FinishedAt  pgtype.Timestamptz `json:"finished_at"`
}

func (q *Queries) CreateBackup(ctx context.Context, arg CreateBackupParams) (Backup, error) {
	row := q.db.QueryRow(ctx, createBackup,
		arg.ID,
		arg.DatabaseID,
		arg.ScheduleID,
		arg.Type,
		arg.Status,
		arg.Size,
		arg.Location,
		arg.TargetID,
		arg.ContainerID,
		arg.Error,
		arg.FinishedAt,
	)
	var i Backup
	err := row.Scan(
		&i.ID,
		&i.DatabaseID,
		&i.ScheduleID,
		&i.Type,
		&i.Status,
		&i.Size,
		&i.Location,
		&i.TargetID,
		&i.ContainerID,
		&i.Error,
		&i.CreatedAt,
		&i.FinishedAt,
	)
	return i, err
}

const createBackupSchedule = `-- name: CreateBackupSchedule :one
INSERT INTO backup_schedules (id, database_id, cron, target_id, enabled, next_run_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, database_id, cron, target_id, enabled, last_run_at, next_run_at, created_at, updated_at
`

type CreateBackupScheduleParams struct {
	ID         pgtype.UUID        `json:"id"`
	DatabaseID pgtype.UUID        `json:"database_id"`
	Cron       string             `json:"cron"`
	TargetID   pgtype.UUID        `json:"target_id"`
	Enabled    bool               `json:"enabled"`
	NextRunAt  pgtype.Timestamptz `json:"next_run_at"`
}

func (q *Queries) CreateBackupSchedule(ctx context.Context, arg CreateBackupScheduleParams) (BackupSchedule, error) {
	row := q.db.QueryRow(ctx, createBackupSchedule,
		arg.ID,
		arg.DatabaseID,
		arg.Cron,
		arg.TargetID,
		arg.Enabled,
		arg.NextRunAt,
	)
	var i BackupSchedule
	err := row.Scan(
		&i.ID,
		&i.DatabaseID,
		&i.Cron,
		&i.TargetID,
		&i.Enabled,
		&i.LastRunAt,
		&i.NextRunAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createBackupTarget = `-- name: CreateBackupTarget :one
INSERT INTO backup_targets (id, user_id, name, kind, endpoint, region, bucket, prefix)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, user_id, name, kind, endpoint, region, bucket, prefix, created_at, updated_at
`

type CreateBackupTargetParams struct {
	ID       pgtype.UUID `json:"id"`
	UserID   pgtype.UUID `json:"user_id"`
	Name     string      `json:"name"`
	Kind     string      `json:"kind"`
	Endpoint string      `json:"endpoint"`
	Region   string      `json:"region"`
	Bucket   string      `json:"bucket"`
	Prefix   string      `json:"prefix"`
}

func (q *Queries) CreateBackupTarget(ctx context.Context, arg CreateBackupTargetParams) (BackupTarget, error) {
	row := q.db.QueryRow(ctx, createBackupTarget,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.Kind,
		arg.Endpoint,
		arg.Region,
		arg.Bucket,
		arg.Prefix,
	)
	var i BackupTarget
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Kind,
		&i.Endpoint,
		&i.Region,
		&i.Bucket,
		&i.Prefix,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createBackupTargetSecret = `-- name: CreateBackupTargetSecret :one
INSERT INTO backup_target_secrets (target_id, key, ciphertext)
VALUES ($1, $2, $3)
RETURNING id, target_id, key, ciphertext, created_at
`

type CreateBackupTargetSecretParams struct {
	TargetID   pgtype.UUID `json:"target_id"`
	Key        string      `json:"key"`
	Ciphertext string      `json:"ciphertext"`
}

func (q *Queries) CreateBackupTargetSecret(ctx context.Context, arg CreateBackupTargetSecretParams) (BackupTargetSecret, error) {
	row := q.db.QueryRow(ctx, createBackupTargetSecret, arg.TargetID, arg.Key, arg.Ciphertext)
	var i BackupTargetSecret
	err := row.Scan(
		&i.ID,
		&i.TargetID,
		&i.Key,
		&i.Ciphertext,
		&i.CreatedAt,
	)
	return i, err
}

const deleteBackup = `-- name: DeleteBackup :one
DELETE FROM backups
WHERE id = $1
RETURNING id, database_id, schedule_id, type, status, size, location, target_id, container_id, error, created_at, finished_at
`

func (q *Queries) DeleteBackup(ctx context.Context, id pgtype.UUID) (Backup, error) {
	row := q.db.QueryRow(ctx, deleteBackup, id)
	var i Backup
	err := row.Scan(
		&i.ID,
		&i.DatabaseID,
		&i.ScheduleID,
		&i.Type,
		&i.Status,
		&i.Size,
		&i.Location,
		&i.TargetID,
		&i.ContainerID,
		&i.Error,
		&i.CreatedAt,
		&i.FinishedAt,
	)
	return i, err
}

const deleteBackupSchedule = `-- name: DeleteBackupSchedule :one
DELETE FROM backup_schedules
WHERE id = $1
RETURNING id, database_id, cron, target_id, enabled, last_run_at, next_run_at, created_at, updated_at
`

func (q *Queries) DeleteBackupSchedule(ctx context.Context, id pgtype.UUID) (BackupSchedule, error) {
	row := q.db.QueryRow(ctx, deleteBackupSchedule, id)
	var i BackupSchedule
	err := row.Scan(
		&i.ID,
		&i.DatabaseID,
		&i.Cron,
		&i.TargetID,
		&i.Enabled,
		&i.LastRunAt,
		&i.NextRunAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteBackupTarget = `-- name: DeleteBackupTarget :one
DELETE FROM backup_targets
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, name, kind, endpoint, region, bucket, prefix, created_at, updated_at
`

type DeleteBackupTargetParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) DeleteBackupTarget(ctx context.Context, arg DeleteBackupTargetParams) (BackupTarget, error) {
	row := q.db.QueryRow(ctx, deleteBackupTarget, arg.ID, arg.UserID)
	var i BackupTarget
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Kind,
		&i.Endpoint,
		&i.Region,
		&i.Bucket,
		&i.Prefix,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const finishBackup = `-- name: FinishBackup :one
UPDATE backups
SET status = $2,
    size = $3,
    location = $4,
    error = $5,
    container_id = $6,
    finished_at = $7
WHERE id = $1
RETURNING id, database_id, schedule_id, type, status, size, location, target_id, container_id, error, created_at, finished_at
`

type FinishBackupParams struct {
	ID          pgtype.UUID        `json:"id"`
	Status      string             `json:"status"`
	Size        int64              `json:"size"`
	Location    string             `json:"location"`
	Error       string             `json:"error"`
	ContainerID string             `json:"container_id"`
	FinishedAt  pgtype.Timestamptz `json:"finished_at"`
}

func (q *Queries) FinishBackup(ctx context.Context, arg FinishBackupParams) (Backup, error) {
	row := q.db.QueryRow(ctx, finishBackup,
		arg.ID,
		arg.Status,
		arg.Size,
		arg.Location,
		arg.Error,
		arg.ContainerID,
		arg.FinishedAt,
	)
	var i Backup
	err := row.Scan(
		&i.ID,
		&i.DatabaseID,
		&i.ScheduleID,
		&i.Type,
		&i.Status,
		&i.Size,
		&i.Location,
		&i.TargetID,
		&i.ContainerID,
		&i.Error,
		&i.CreatedAt,
		&i.FinishedAt,
	)
	return i, err
}

const getBackup = `-- name: GetBackup :one
SELECT b.id, b.database_id, b.schedule_id, b.type, b.status, b.size, b.location, b.target_id, b.container_id, b.error, b.created_at, b.finished_at
FROM backups b
    JOIN databases d ON d.id = b.database_id
WHERE b.id = $1 AND d.deleted_at IS NULL
`

func (q *Queries) GetBackup(ctx context.Context, id pgtype.UUID) (Backup, error) {
	row := q.db.QueryRow(ctx, getBackup, id)
	var i Backup
	err := row.Scan(
		&i.ID,
		&i.DatabaseID,
		&i.ScheduleID,
		&i.Type,
		&i.Status,
		&i.Size,
		&i.Location,
		&i.TargetID,
		&i.ContainerID,
		&i.Error,
		&i.CreatedAt,
		&i.FinishedAt,
	)
	return i, err
}

const getBackupSchedule = `-- name: GetBackupSchedule :one
SELECT s.id, s.database_id, s.cron, s.target_id, s.enabled, s.last_run_at, s.next_run_at, s.created_at, s.updated_at
FROM backup_schedules s
    JOIN databases d ON d.id = s.database_id
WHERE s.id = $1 AND d.deleted_at IS NULL
`

func (q *Queries) GetBackupSchedule(ctx context.Context, id pgtype.UUID) (BackupSchedule, error) {
	row := q.db.QueryRow(ctx, getBackupSchedule, id)
	var i BackupSchedule
	err := row.Scan(
		&i.ID,
		&i.DatabaseID,
		&i.Cron,
		&i.TargetID,
		&i.Enabled,
		&i.LastRunAt,
		&i.NextRunAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBackupTarget = `-- name: GetBackupTarget :one
SELECT id, user_id, name, kind, endpoint, region, bucket, prefix, created_at, updated_at FROM backup_targets
WHERE id = $1
`

func (q *Queries) GetBackupTarget(ctx context.Context, id pgtype.UUID) (BackupTarget, error) {
	row := q.db.QueryRow(ctx, getBackupTarget, id)
	var i BackupTarget
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Kind,
		&i.Endpoint,
		&i.Region,
		&i.Bucket,
		&i.Prefix,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listBackupSchedulesByDatabase = `-- name: ListBackupSchedulesByDatabase :many
SELECT s.id, s.database_id, s.cron, s.target_id, s.enabled, s.last_run_at, s.next_run_at, s.created_at, s.updated_at
FROM backup_schedules s
    JOIN databases d ON d.id = s.database_id
WHERE s.database_id = $1 AND d.deleted_at IS NULL
ORDER BY s.created_at DESC, s.id DESC
`

func (q *Queries) ListBackupSchedulesByDatabase(ctx context.Context, databaseID pgtype.UUID) ([]BackupSchedule, error) {
	rows, err := q.db.Query(ctx, listBackupSchedulesByDatabase, databaseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BackupSchedule{}
	for rows.Next() {
		var i BackupSchedule
		if err := rows.Scan(
			&i.ID,
			&i.DatabaseID,
			&i.Cron,
			&i.TargetID,
			&i.Enabled,
			&i.LastRunAt,
			&i.NextRunAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBackupTargetSecrets = `-- name: ListBackupTargetSecrets :many
SELECT id, target_id, key, ciphertext, created_at FROM backup_target_secrets
WHERE target_id = $1
ORDER BY key ASC
`

func (q *Queries) ListBackupTargetSecrets(ctx context.Context, targetID pgtype.UUID) ([]BackupTargetSecret, error) {
	rows, err := q.db.Query(ctx, listBackupTargetSecrets, targetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BackupTargetSecret{}
	for rows.Next() {
		var i BackupTargetSecret
		if err := rows.Scan(
			&i.ID,
			&i.TargetID,
			&i.Key,
			&i.Ciphertext,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBackupTargetsByUser = `-- name: ListBackupTargetsByUser :many
SELECT id, user_id, name, kind, endpoint, region, bucket, prefix, created_at, updated_at FROM backup_targets
WHERE user_id = $1
ORDER BY created_at DESC, id DESC
`

func (q *Queries) ListBackupTargetsByUser(ctx context.Context, userID pgtype.UUID) ([]BackupTarget, error) {
	rows, err := q.db.Query(ctx, listBackupTargetsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BackupTarget{}
	for rows.Next() {
		var i BackupTarget
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Kind,
			&i.Endpoint,
			&i.Region,
			&i.Bucket,
			&i.Prefix,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBackupsByDatabase = `-- name: ListBackupsByDatabase :many
SELECT b.id, b.database_id, b.schedule_id, b.type, b.status, b.size, b.location, b.target_id, b.container_id, b.error, b.created_at, b.finished_at
FROM backups b
    JOIN databases d ON d.id = b.database_id
WHERE b.database_id = $1 AND d.deleted_at IS NULL
ORDER BY b.created_at DESC, b.id DESC
`

func (q *Queries) ListBackupsByDatabase(ctx context.Context, databaseID pgtype.UUID) ([]Backup, error) {
	rows, err := q.db.Query(ctx, listBackupsByDatabase, databaseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Backup{}
	for rows.Next() {
		var i Backup
		if err := rows.Scan(
			&i.ID,
			&i.DatabaseID,
			&i.ScheduleID,
			&i.Type,
			&i.Status,
			&i.Size,
			&i.Location,
			&i.TargetID,
			&i.ContainerID,
			&i.Error,
			&i.CreatedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDueBackupSchedules = `-- name: ListDueBackupSchedules :many
SELECT s.id, s.database_id, s.cron, s.target_id, s.enabled, s.last_run_at, s.next_run_at, s.created_at, s.updated_at
FROM backup_schedules s
    JOIN databases d ON d.id = s.database_id
WHERE s.enabled AND s.next_run_at <= $1 AND d.deleted_at IS NULL
ORDER BY s.next_run_at ASC, s.id ASC
`

func (q *Queries) ListDueBackupSchedules(ctx context.Context, nextRunAt pgtype.Timestamptz) ([]BackupSchedule, error) {
	rows, err := q.db.Query(ctx, listDueBackupSchedules, nextRunAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BackupSchedule{}
	for rows.Next() {
		var i BackupSchedule
		if err := rows.Scan(
			&i.ID,
			&i.DatabaseID,
			&i.Cron,
			&i.TargetID,
			&i.Enabled,
			&i.LastRunAt,
			&i.NextRunAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunningBackups = `-- name: ListRunningBackups :many
SELECT id, database_id, schedule_id, type, status, size, location, target_id, container_id, error, created_at, finished_at FROM backups
WHERE status = 'running'
ORDER BY created_at ASC
`

// Boot-time recovery: rows the control plane left running after a crash or
// restart can never finish, so they are swept to failed.
func (q *Queries) ListRunningBackups(ctx context.Context) ([]Backup, error) {
	rows, err := q.db.Query(ctx, listRunningBackups)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Backup{}
	for rows.Next() {
		var i Backup
		if err := rows.Scan(
			&i.ID,
			&i.DatabaseID,
			&i.ScheduleID,
			&i.Type,
			&i.Status,
			&i.Size,
			&i.Location,
			&i.TargetID,
			&i.ContainerID,
			&i.Error,
			&i.CreatedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markBackupScheduleRun = `-- name: MarkBackupScheduleRun :one
UPDATE backup_schedules
SET last_run_at = $2,
    next_run_at = $3,
    updated_at = now()
WHERE id = $1
RETURNING id, database_id, cron, target_id, enabled, last_run_at, next_run_at, created_at, updated_at
`

type MarkBackupScheduleRunParams struct {
	ID        pgtype.UUID        `json:"id"`
	LastRunAt pgtype.Timestamptz `json:"last_run_at"`
	NextRunAt pgtype.Timestamptz `json:"next_run_at"`
}

func (q *Queries) MarkBackupScheduleRun(ctx context.Context, arg MarkBackupScheduleRunParams) (BackupSchedule, error) {
	row := q.db.QueryRow(ctx, markBackupScheduleRun, arg.ID, arg.LastRunAt, arg.NextRunAt)
	var i BackupSchedule
	err := row.Scan(
		&i.ID,
		&i.DatabaseID,
		&i.Cron,
		&i.TargetID,
		&i.Enabled,
		&i.LastRunAt,
		&i.NextRunAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateBackupSchedule = `-- name: UpdateBackupSchedule :one
UPDATE backup_schedules
SET cron = $2,
    target_id = $3,
    enabled = $4,
    next_run_at = $5,
    updated_at = now()
WHERE id = $1
RETURNING id, database_id, cron, target_id, enabled, last_run_at, next_run_at, created_at, updated_at
`

type UpdateBackupScheduleParams struct {
	ID        pgtype.UUID        `json:"id"`
	Cron      string             `json:"cron"`
	TargetID  pgtype.UUID        `json:"target_id"`
	Enabled   bool               `json:"enabled"`
	NextRunAt pgtype.Timestamptz `json:"next_run_at"`
}

func (q *Queries) UpdateBackupSchedule(ctx context.Context, arg UpdateBackupScheduleParams) (BackupSchedule, error) {
	row := q.db.QueryRow(ctx, updateBackupSchedule,
		arg.ID,
		arg.Cron,
		arg.TargetID,
		arg.Enabled,
		arg.NextRunAt,
	)
	var i BackupSchedule
	err := row.Scan(
		&i.ID,
		&i.DatabaseID,
		&i.Cron,
		&i.TargetID,
		&i.Enabled,
		&i.LastRunAt,
		&i.NextRunAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateBackupTarget = `-- name: UpdateBackupTarget :one
UPDATE backup_targets
SET name = $2,
    kind = $3,
    endpoint = $4,
    region = $5,
    bucket = $6,
    prefix = $7,
    updated_at = now()
WHERE id = $1
RETURNING id, user_id, name, kind, endpoint, region, bucket, prefix, created_at, updated_at
`

type UpdateBackupTargetParams struct {
	ID       pgtype.UUID `json:"id"`
	Name     string      `json:"name"`
	Kind     string      `json:"kind"`
	Endpoint string      `json:"endpoint"`
	Region   string      `json:"region"`
	Bucket   string      `json:"bucket"`
	Prefix   string      `json:"prefix"`
}

func (q *Queries) UpdateBackupTarget(ctx context.Context, arg UpdateBackupTargetParams) (BackupTarget, error) {
	row := q.db.QueryRow(ctx, updateBackupTarget,
		arg.ID,
		arg.Name,
		arg.Kind,
		arg.Endpoint,
		arg.Region,
		arg.Bucket,
		arg.Prefix,
	)
	var i BackupTarget
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Kind,
		&i.Endpoint,
		&i.Region,
		&i.Bucket,
		&i.Prefix,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertBackupTargetSecret = `-- name: UpsertBackupTargetSecret :one
INSERT INTO backup_target_secrets (target_id, key, ciphertext)
VALUES ($1, $2, $3)
ON CONFLICT (target_id, key)
DO UPDATE SET ciphertext = EXCLUDED.ciphertext
RETURNING id, target_id, key, ciphertext, created_at
`

type UpsertBackupTargetSecretParams struct {
	TargetID   pgtype.UUID `json:"target_id"`
	Key        string      `json:"key"`
	Ciphertext string      `json:"ciphertext"`
}

func (q *Queries) UpsertBackupTargetSecret(ctx context.Context, arg UpsertBackupTargetSecretParams) (BackupTargetSecret, error) {
	row := q.db.QueryRow(ctx, upsertBackupTargetSecret, arg.TargetID, arg.Key, arg.Ciphertext)
	var i BackupTargetSecret
	err := row.Scan(
		&i.ID,
		&i.TargetID,
		&i.Key,
		&i.Ciphertext,
		&i.CreatedAt,
	)
	return i, err
}
