// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: databases.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDatabase = `-- name: CreateDatabase :one
INSERT INTO databases (
    id, user_id, server_id, name, engine, version, status, public_port, storage_path, team_id
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, user_id, server_id, name, engine, version, status, container_id, public_port, storage_path, created_at, updated_at, deleted_at, team_id
`

type CreateDatabaseParams struct {
	ID          pgtype.UUID `json:"id"`
	UserID      pgtype.UUID `json:"user_id"`
	ServerID    pgtype.UUID `json:"server_id"`
	Name        string      `json:"name"`
	Engine      string      `json:"engine"`
	Version     string      `json:"version"`
	Status      string      `json:"status"`
	PublicPort  int32       `json:"public_port"`
	StoragePath string      `json:"storage_path"`
	TeamID      pgtype.UUID `json:"team_id"`
}

func (q *Queries) CreateDatabase(ctx context.Context, arg CreateDatabaseParams) (Database, error) {
	row := q.db.QueryRow(ctx, createDatabase,
		arg.ID,
		arg.UserID,
		arg.ServerID,
		arg.Name,
		arg.Engine,
		arg.Version,
		arg.Status,
		arg.PublicPort,
		arg.StoragePath,
		arg.TeamID,
	)
	var i Database
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ServerID,
		&i.Name,
		&i.Engine,
		&i.Version,
		&i.Status,
		&i.ContainerID,
		&i.PublicPort,
		&i.StoragePath,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.TeamID,
	)
	return i, err
}

const createDatabaseSecret = `-- name: CreateDatabaseSecret :one
INSERT INTO database_secrets (database_id, key, ciphertext)
VALUES ($1, $2, $3)
RETURNING id, database_id, key, ciphertext, created_at
`

type CreateDatabaseSecretParams struct {
	DatabaseID pgtype.UUID `json:"database_id"`
	Key        string      `json:"key"`
	Ciphertext string      `json:"ciphertext"`
}

func (q *Queries) CreateDatabaseSecret(ctx context.Context, arg CreateDatabaseSecretParams) (DatabaseSecret, error) {
	row := q.db.QueryRow(ctx, createDatabaseSecret, arg.DatabaseID, arg.Key, arg.Ciphertext)
	var i DatabaseSecret
	err := row.Scan(
		&i.ID,
		&i.DatabaseID,
		&i.Key,
		&i.Ciphertext,
		&i.CreatedAt,
	)
	return i, err
}

const deleteDatabaseSecrets = `-- name: DeleteDatabaseSecrets :exec
DELETE FROM database_secrets
WHERE database_id = $1
`

func (q *Queries) DeleteDatabaseSecrets(ctx context.Context, databaseID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteDatabaseSecrets, databaseID)
	return err
}

const getDatabase = `-- name: GetDatabase :one
SELECT id, user_id, server_id, name, engine, version, status, container_id, public_port, storage_path, created_at, updated_at, deleted_at, team_id FROM databases
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetDatabase(ctx context.Context, id pgtype.UUID) (Database, error) {
	row := q.db.QueryRow(ctx, getDatabase, id)
	var i Database
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ServerID,
		&i.Name,
		&i.Engine,
		&i.Version,
		&i.Status,
		&i.ContainerID,
		&i.PublicPort,
		&i.StoragePath,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.TeamID,
	)
	return i, err
}

const listDatabaseSecrets = `-- name: ListDatabaseSecrets :many
SELECT id, database_id, key, ciphertext, created_at FROM database_secrets
WHERE database_id = $1
ORDER BY key ASC
`

func (q *Queries) ListDatabaseSecrets(ctx context.Context, databaseID pgtype.UUID) ([]DatabaseSecret, error) {
	rows, err := q.db.Query(ctx, listDatabaseSecrets, databaseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DatabaseSecret{}
	for rows.Next() {
		var i DatabaseSecret
		if err := rows.Scan(
			&i.ID,
			&i.DatabaseID,
			&i.Key,
			&i.Ciphertext,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDatabasesByTeam = `-- name: ListDatabasesByTeam :many
SELECT id, user_id, server_id, name, engine, version, status, container_id, public_port, storage_path, created_at, updated_at, deleted_at, team_id FROM databases
WHERE team_id = $1 AND deleted_at IS NULL
ORDER BY created_at DESC, id DESC
`

func (q *Queries) ListDatabasesByTeam(ctx context.Context, teamID pgtype.UUID) ([]Database, error) {
	rows, err := q.db.Query(ctx, listDatabasesByTeam, teamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Database{}
	for rows.Next() {
		var i Database
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ServerID,
			&i.Name,
			&i.Engine,
			&i.Version,
			&i.Status,
			&i.ContainerID,
			&i.PublicPort,
			&i.StoragePath,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.TeamID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDatabasesByUser = `-- name: ListDatabasesByUser :many
SELECT id, user_id, server_id, name, engine, version, status, container_id, public_port, storage_path, created_at, updated_at, deleted_at, team_id FROM databases
WHERE user_id = $1 AND deleted_at IS NULL
ORDER BY created_at DESC, id DESC
`

func (q *Queries) ListDatabasesByUser(ctx context.Context, userID pgtype.UUID) ([]Database, error) {
	rows, err := q.db.Query(ctx, listDatabasesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Database{}
	for rows.Next() {
		var i Database
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ServerID,
			&i.Name,
			&i.Engine,
			&i.Version,
			&i.Status,
			&i.ContainerID,
			&i.PublicPort,
			&i.StoragePath,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.TeamID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const publicPortInUse = `-- name: PublicPortInUse :one
SELECT EXISTS (
    SELECT 1 FROM databases
    WHERE server_id = $1 AND public_port = $2 AND deleted_at IS NULL
)
`

type PublicPortInUseParams struct {
	ServerID   pgtype.UUID `json:"server_id"`
	PublicPort int32       `json:"public_port"`
}

func (q *Queries) PublicPortInUse(ctx context.Context, arg PublicPortInUseParams) (bool, error) {
	row := q.db.QueryRow(ctx, publicPortInUse, arg.ServerID, arg.PublicPort)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const softDeleteDatabase = `-- name: SoftDeleteDatabase :one
UPDATE databases
SET status = 'deleting',
    deleted_at = now(),
    updated_at = now()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, user_id, server_id, name, engine, version, status, container_id, public_port, storage_path, created_at, updated_at, deleted_at, team_id
`

func (q *Queries) SoftDeleteDatabase(ctx context.Context, id pgtype.UUID) (Database, error) {
	row := q.db.QueryRow(ctx, softDeleteDatabase, id)
	var i Database
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ServerID,
		&i.Name,
		&i.Engine,
		&i.Version,
		&i.Status,
		&i.ContainerID,
		&i.PublicPort,
		&i.StoragePath,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.TeamID,
	)
	return i, err
}

const updateDatabaseContainer = `-- name: UpdateDatabaseContainer :one
UPDATE databases
SET container_id = $2,
    updated_at = now()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, user_id, server_id, name, engine, version, status, container_id, public_port, storage_path, created_at, updated_at, deleted_at, team_id
`

type UpdateDatabaseContainerParams struct {
	ID          pgtype.UUID `json:"id"`
	ContainerID string      `json:"container_id"`
}

func (q *Queries) UpdateDatabaseContainer(ctx context.Context, arg UpdateDatabaseContainerParams) (Database, error) {
	row := q.db.QueryRow(ctx, updateDatabaseContainer, arg.ID, arg.ContainerID)
	var i Database
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ServerID,
		&i.Name,
		&i.Engine,
		&i.Version,
		&i.Status,
		&i.ContainerID,
		&i.PublicPort,
		&i.StoragePath,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.TeamID,
	)
	return i, err
}

const updateDatabaseName = `-- name: UpdateDatabaseName :one
UPDATE databases
SET name = $2,
    updated_at = now()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, user_id, server_id, name, engine, version, status, container_id, public_port, storage_path, created_at, updated_at, deleted_at, team_id
`

type UpdateDatabaseNameParams struct {
	ID   pgtype.UUID `json:"id"`
	Name string      `json:"name"`
}

func (q *Queries) UpdateDatabaseName(ctx context.Context, arg UpdateDatabaseNameParams) (Database, error) {
	row := q.db.QueryRow(ctx, updateDatabaseName, arg.ID, arg.Name)
	var i Database
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ServerID,
		&i.Name,
		&i.Engine,
		&i.Version,
		&i.Status,
		&i.ContainerID,
		&i.PublicPort,
		&i.StoragePath,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.TeamID,
	)
	return i, err
}

const updateDatabaseStatus = `-- name: UpdateDatabaseStatus :one
UPDATE databases
SET status = $2,
    updated_at = now()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, user_id, server_id, name, engine, version, status, container_id, public_port, storage_path, created_at, updated_at, deleted_at, team_id
`

type UpdateDatabaseStatusParams struct {
	ID     pgtype.UUID `json:"id"`
	Status string      `json:"status"`
}

func (q *Queries) UpdateDatabaseStatus(ctx context.Context, arg UpdateDatabaseStatusParams) (Database, error) {
	row := q.db.QueryRow(ctx, updateDatabaseStatus, arg.ID, arg.Status)
	var i Database
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ServerID,
		&i.Name,
		&i.Engine,
		&i.Version,
		&i.Status,
		&i.ContainerID,
		&i.PublicPort,
		&i.StoragePath,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.TeamID,
	)
	return i, err
}
