// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: databases.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countDatabasesByEnvironment = `-- name: CountDatabasesByEnvironment :one
SELECT count(*) FROM databases WHERE environment_id = $1 AND deleted_at IS NULL
`

func (q *Queries) CountDatabasesByEnvironment(ctx context.Context, environmentID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countDatabasesByEnvironment, environmentID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countDatabasesByProject = `-- name: CountDatabasesByProject :one
SELECT count(*) FROM databases d
JOIN environments e ON e.id = d.environment_id
WHERE e.project_id = $1 AND d.deleted_at IS NULL
`

func (q *Queries) CountDatabasesByProject(ctx context.Context, projectID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countDatabasesByProject, projectID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createDatabase = `-- name: CreateDatabase :one
INSERT INTO databases (
    id, user_id, server_id, environment_id, name, engine, version, status, public_port, storage_path, team_id
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, user_id, server_id, name, engine, version, status, container_id, public_port, storage_path, created_at, updated_at, deleted_at, team_id, environment_id
`

type CreateDatabaseParams struct {
	ID            pgtype.UUID `json:"id"`
	UserID        pgtype.UUID `json:"user_id"`
	ServerID      pgtype.UUID `json:"server_id"`
	EnvironmentID pgtype.UUID `json:"environment_id"`
	Name          string      `json:"name"`
	Engine        string      `json:"engine"`
	Version       string      `json:"version"`
	Status        string      `json:"status"`
	PublicPort    int32       `json:"public_port"`
	StoragePath   string      `json:"storage_path"`
	TeamID        pgtype.UUID `json:"team_id"`
}

func (q *Queries) CreateDatabase(ctx context.Context, arg CreateDatabaseParams) (Database, error) {
	row := q.db.QueryRow(ctx, createDatabase,
		arg.ID,
		arg.UserID,
		arg.ServerID,
		arg.EnvironmentID,
		arg.Name,
		arg.Engine,
		arg.Version,
		arg.Status,
		arg.PublicPort,
		arg.StoragePath,
		arg.TeamID,
	)
	var i Database
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ServerID,
		&i.Name,
		&i.Engine,
		&i.Version,
		&i.Status,
		&i.ContainerID,
		&i.PublicPort,
		&i.StoragePath,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.TeamID,
		&i.EnvironmentID,
	)
	return i, err
}

const createDatabaseSecret = `-- name: CreateDatabaseSecret :one
INSERT INTO database_secrets (database_id, key, ciphertext)
VALUES ($1, $2, $3)
RETURNING id, database_id, key, ciphertext, created_at
`

type CreateDatabaseSecretParams struct {
	DatabaseID pgtype.UUID `json:"database_id"`
	Key        string      `json:"key"`
	Ciphertext string      `json:"ciphertext"`
}

func (q *Queries) CreateDatabaseSecret(ctx context.Context, arg CreateDatabaseSecretParams) (DatabaseSecret, error) {
	row := q.db.QueryRow(ctx, createDatabaseSecret, arg.DatabaseID, arg.Key, arg.Ciphertext)
	var i DatabaseSecret
	err := row.Scan(
		&i.ID,
		&i.DatabaseID,
		&i.Key,
		&i.Ciphertext,
		&i.CreatedAt,
	)
	return i, err
}

const databaseNameInEnvironment = `-- name: DatabaseNameInEnvironment :one
SELECT EXISTS (
    SELECT 1 FROM databases
    WHERE environment_id = $1 AND name = $2 AND id <> $3 AND deleted_at IS NULL
)
`

type DatabaseNameInEnvironmentParams struct {
	EnvironmentID pgtype.UUID `json:"environment_id"`
	Name          string      `json:"name"`
	ID            pgtype.UUID `json:"id"`
}

// The move-collision pre-check: whether the environment holds another live
// database with the name (exact match, like the unique index).
func (q *Queries) DatabaseNameInEnvironment(ctx context.Context, arg DatabaseNameInEnvironmentParams) (bool, error) {
	row := q.db.QueryRow(ctx, databaseNameInEnvironment, arg.EnvironmentID, arg.Name, arg.ID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const deleteDatabaseSecrets = `-- name: DeleteDatabaseSecrets :exec
DELETE FROM database_secrets
WHERE database_id = $1
`

func (q *Queries) DeleteDatabaseSecrets(ctx context.Context, databaseID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteDatabaseSecrets, databaseID)
	return err
}

const getDatabase = `-- name: GetDatabase :one
SELECT id, user_id, server_id, name, engine, version, status, container_id, public_port, storage_path, created_at, updated_at, deleted_at, team_id, environment_id FROM databases
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetDatabase(ctx context.Context, id pgtype.UUID) (Database, error) {
	row := q.db.QueryRow(ctx, getDatabase, id)
	var i Database
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ServerID,
		&i.Name,
		&i.Engine,
		&i.Version,
		&i.Status,
		&i.ContainerID,
		&i.PublicPort,
		&i.StoragePath,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.TeamID,
		&i.EnvironmentID,
	)
	return i, err
}

const listDatabaseSecrets = `-- name: ListDatabaseSecrets :many
SELECT id, database_id, key, ciphertext, created_at FROM database_secrets
WHERE database_id = $1
ORDER BY key ASC
`

func (q *Queries) ListDatabaseSecrets(ctx context.Context, databaseID pgtype.UUID) ([]DatabaseSecret, error) {
	rows, err := q.db.Query(ctx, listDatabaseSecrets, databaseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DatabaseSecret{}
	for rows.Next() {
		var i DatabaseSecret
		if err := rows.Scan(
			&i.ID,
			&i.DatabaseID,
			&i.Key,
			&i.Ciphertext,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDatabasesByEnvironment = `-- name: ListDatabasesByEnvironment :many
SELECT id, user_id, server_id, name, engine, version, status, container_id, public_port, storage_path, created_at, updated_at, deleted_at, team_id, environment_id FROM databases
WHERE environment_id = $1 AND deleted_at IS NULL
ORDER BY created_at DESC, id DESC
`

func (q *Queries) ListDatabasesByEnvironment(ctx context.Context, environmentID pgtype.UUID) ([]Database, error) {
	rows, err := q.db.Query(ctx, listDatabasesByEnvironment, environmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Database{}
	for rows.Next() {
		var i Database
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ServerID,
			&i.Name,
			&i.Engine,
			&i.Version,
			&i.Status,
			&i.ContainerID,
			&i.PublicPort,
			&i.StoragePath,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.TeamID,
			&i.EnvironmentID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDatabasesByProject = `-- name: ListDatabasesByProject :many
SELECT d.id, d.user_id, d.server_id, d.name, d.engine, d.version, d.status, d.container_id, d.public_port, d.storage_path, d.created_at, d.updated_at, d.deleted_at, d.team_id, d.environment_id FROM databases d
JOIN environments e ON e.id = d.environment_id
WHERE e.project_id = $1 AND d.deleted_at IS NULL
ORDER BY d.created_at DESC, d.id DESC
`

func (q *Queries) ListDatabasesByProject(ctx context.Context, projectID pgtype.UUID) ([]Database, error) {
	rows, err := q.db.Query(ctx, listDatabasesByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Database{}
	for rows.Next() {
		var i Database
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ServerID,
			&i.Name,
			&i.Engine,
			&i.Version,
			&i.Status,
			&i.ContainerID,
			&i.PublicPort,
			&i.StoragePath,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.TeamID,
			&i.EnvironmentID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDatabasesByServer = `-- name: ListDatabasesByServer :many
SELECT id, name FROM databases
WHERE server_id = $1 AND deleted_at IS NULL
ORDER BY created_at DESC, id DESC
`

type ListDatabasesByServerRow struct {
	ID   pgtype.UUID `json:"id"`
	Name string      `json:"name"`
}

func (q *Queries) ListDatabasesByServer(ctx context.Context, serverID pgtype.UUID) ([]ListDatabasesByServerRow, error) {
	rows, err := q.db.Query(ctx, listDatabasesByServer, serverID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDatabasesByServerRow{}
	for rows.Next() {
		var i ListDatabasesByServerRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDatabasesByTeam = `-- name: ListDatabasesByTeam :many
SELECT id, user_id, server_id, name, engine, version, status, container_id, public_port, storage_path, created_at, updated_at, deleted_at, team_id, environment_id FROM databases
WHERE team_id = $1 AND deleted_at IS NULL
ORDER BY created_at DESC, id DESC
`

func (q *Queries) ListDatabasesByTeam(ctx context.Context, teamID pgtype.UUID) ([]Database, error) {
	rows, err := q.db.Query(ctx, listDatabasesByTeam, teamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Database{}
	for rows.Next() {
		var i Database
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ServerID,
			&i.Name,
			&i.Engine,
			&i.Version,
			&i.Status,
			&i.ContainerID,
			&i.PublicPort,
			&i.StoragePath,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.TeamID,
			&i.EnvironmentID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDatabasesByUser = `-- name: ListDatabasesByUser :many
SELECT id, user_id, server_id, name, engine, version, status, container_id, public_port, storage_path, created_at, updated_at, deleted_at, team_id, environment_id FROM databases
WHERE user_id = $1 AND deleted_at IS NULL
ORDER BY created_at DESC, id DESC
`

func (q *Queries) ListDatabasesByUser(ctx context.Context, userID pgtype.UUID) ([]Database, error) {
	rows, err := q.db.Query(ctx, listDatabasesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Database{}
	for rows.Next() {
		var i Database
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ServerID,
			&i.Name,
			&i.Engine,
			&i.Version,
			&i.Status,
			&i.ContainerID,
			&i.PublicPort,
			&i.StoragePath,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.TeamID,
			&i.EnvironmentID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpiredDatabases = `-- name: ListExpiredDatabases :many
SELECT id, user_id, server_id, name, engine, version, status, container_id, public_port, storage_path, created_at, updated_at, deleted_at, team_id, environment_id FROM databases
WHERE deleted_at IS NOT NULL AND deleted_at <= $1
ORDER BY deleted_at ASC, id ASC
`

// Soft-deleted databases whose grace window has elapsed. The retention sweep
// is the only reader that looks past deleted_at; every API read filters it.
func (q *Queries) ListExpiredDatabases(ctx context.Context, deletedAt pgtype.Timestamptz) ([]Database, error) {
	rows, err := q.db.Query(ctx, listExpiredDatabases, deletedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Database{}
	for rows.Next() {
		var i Database
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ServerID,
			&i.Name,
			&i.Engine,
			&i.Version,
			&i.Status,
			&i.ContainerID,
			&i.PublicPort,
			&i.StoragePath,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.TeamID,
			&i.EnvironmentID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const publicPortInUse = `-- name: PublicPortInUse :one
SELECT EXISTS (
    SELECT 1 FROM databases
    WHERE server_id = $1 AND public_port = $2 AND deleted_at IS NULL
)
`

type PublicPortInUseParams struct {
	ServerID   pgtype.UUID `json:"server_id"`
	PublicPort int32       `json:"public_port"`
}

func (q *Queries) PublicPortInUse(ctx context.Context, arg PublicPortInUseParams) (bool, error) {
	row := q.db.QueryRow(ctx, publicPortInUse, arg.ServerID, arg.PublicPort)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const purgeDatabase = `-- name: PurgeDatabase :execrows
DELETE FROM databases
WHERE id = $1 AND deleted_at IS NOT NULL
`

// Hard-deletes a soft-deleted database after its volume is removed; the
// database_secrets cascade with it. A live row is never purged.
func (q *Queries) PurgeDatabase(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, purgeDatabase, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const softDeleteDatabase = `-- name: SoftDeleteDatabase :one
UPDATE databases
SET status = 'deleting',
    deleted_at = now(),
    updated_at = now()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, user_id, server_id, name, engine, version, status, container_id, public_port, storage_path, created_at, updated_at, deleted_at, team_id, environment_id
`

func (q *Queries) SoftDeleteDatabase(ctx context.Context, id pgtype.UUID) (Database, error) {
	row := q.db.QueryRow(ctx, softDeleteDatabase, id)
	var i Database
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ServerID,
		&i.Name,
		&i.Engine,
		&i.Version,
		&i.Status,
		&i.ContainerID,
		&i.PublicPort,
		&i.StoragePath,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.TeamID,
		&i.EnvironmentID,
	)
	return i, err
}

const updateDatabaseContainer = `-- name: UpdateDatabaseContainer :one
UPDATE databases
SET container_id = $2,
    updated_at = now()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, user_id, server_id, name, engine, version, status, container_id, public_port, storage_path, created_at, updated_at, deleted_at, team_id, environment_id
`

type UpdateDatabaseContainerParams struct {
	ID          pgtype.UUID `json:"id"`
	ContainerID string      `json:"container_id"`
}

func (q *Queries) UpdateDatabaseContainer(ctx context.Context, arg UpdateDatabaseContainerParams) (Database, error) {
	row := q.db.QueryRow(ctx, updateDatabaseContainer, arg.ID, arg.ContainerID)
	var i Database
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ServerID,
		&i.Name,
		&i.Engine,
		&i.Version,
		&i.Status,
		&i.ContainerID,
		&i.PublicPort,
		&i.StoragePath,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.TeamID,
		&i.EnvironmentID,
	)
	return i, err
}

const updateDatabaseName = `-- name: UpdateDatabaseName :one
UPDATE databases
SET name = $2,
    updated_at = now()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, user_id, server_id, name, engine, version, status, container_id, public_port, storage_path, created_at, updated_at, deleted_at, team_id, environment_id
`

type UpdateDatabaseNameParams struct {
	ID   pgtype.UUID `json:"id"`
	Name string      `json:"name"`
}

func (q *Queries) UpdateDatabaseName(ctx context.Context, arg UpdateDatabaseNameParams) (Database, error) {
	row := q.db.QueryRow(ctx, updateDatabaseName, arg.ID, arg.Name)
	var i Database
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ServerID,
		&i.Name,
		&i.Engine,
		&i.Version,
		&i.Status,
		&i.ContainerID,
		&i.PublicPort,
		&i.StoragePath,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.TeamID,
		&i.EnvironmentID,
	)
	return i, err
}

const updateDatabaseStatus = `-- name: UpdateDatabaseStatus :one
UPDATE databases
SET status = $2,
    updated_at = now()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, user_id, server_id, name, engine, version, status, container_id, public_port, storage_path, created_at, updated_at, deleted_at, team_id, environment_id
`

type UpdateDatabaseStatusParams struct {
	ID     pgtype.UUID `json:"id"`
	Status string      `json:"status"`
}

func (q *Queries) UpdateDatabaseStatus(ctx context.Context, arg UpdateDatabaseStatusParams) (Database, error) {
	row := q.db.QueryRow(ctx, updateDatabaseStatus, arg.ID, arg.Status)
	var i Database
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ServerID,
		&i.Name,
		&i.Engine,
		&i.Version,
		&i.Status,
		&i.ContainerID,
		&i.PublicPort,
		&i.StoragePath,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.TeamID,
		&i.EnvironmentID,
	)
	return i, err
}

const updateDatabaseTarget = `-- name: UpdateDatabaseTarget :one
UPDATE databases
SET name = $2,
    environment_id = $3,
    server_id = $4,
    updated_at = now()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, user_id, server_id, name, engine, version, status, container_id, public_port, storage_path, created_at, updated_at, deleted_at, team_id, environment_id
`

type UpdateDatabaseTargetParams struct {
	ID            pgtype.UUID `json:"id"`
	Name          string      `json:"name"`
	EnvironmentID pgtype.UUID `json:"environment_id"`
	ServerID      pgtype.UUID `json:"server_id"`
}

// Rename, move environment and change node in one write. The row stays live
// throughout: the write is fenced on deleted_at, so a concurrent delete wins
// and the move silently no-ops to ErrNotFound instead.
func (q *Queries) UpdateDatabaseTarget(ctx context.Context, arg UpdateDatabaseTargetParams) (Database, error) {
	row := q.db.QueryRow(ctx, updateDatabaseTarget,
		arg.ID,
		arg.Name,
		arg.EnvironmentID,
		arg.ServerID,
	)
	var i Database
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ServerID,
		&i.Name,
		&i.Engine,
		&i.Version,
		&i.Status,
		&i.ContainerID,
		&i.PublicPort,
		&i.StoragePath,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.TeamID,
		&i.EnvironmentID,
	)
	return i, err
}
