// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: databases.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDatabase = `-- name: CreateDatabase :one
INSERT INTO databases (
    id, user_id, server_id, name, engine, version, status, public_port, storage_path
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, user_id, server_id, name, engine, version, status, container_id, public_port, storage_path, created_at, updated_at, deleted_at
`

type CreateDatabaseParams struct {
	ID          pgtype.UUID `json:"id"`
	UserID      pgtype.UUID `json:"user_id"`
	ServerID    pgtype.UUID `json:"server_id"`
	Name        string      `json:"name"`
	Engine      string      `json:"engine"`
	Version     string      `json:"version"`
	Status      string      `json:"status"`
	PublicPort  int32       `json:"public_port"`
	StoragePath string      `json:"storage_path"`
}

func (q *Queries) CreateDatabase(ctx context.Context, arg CreateDatabaseParams) (Database, error) {
	row := q.db.QueryRow(ctx, createDatabase,
		arg.ID,
		arg.UserID,
		arg.ServerID,
		arg.Name,
		arg.Engine,
		arg.Version,
		arg.Status,
		arg.PublicPort,
		arg.StoragePath,
	)
	var i Database
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ServerID,
		&i.Name,
		&i.Engine,
		&i.Version,
		&i.Status,
		&i.ContainerID,
		&i.PublicPort,
		&i.StoragePath,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createDatabaseSecret = `-- name: CreateDatabaseSecret :one
INSERT INTO database_secrets (database_id, key, ciphertext)
VALUES ($1, $2, $3)
RETURNING id, database_id, key, ciphertext, created_at
`

type CreateDatabaseSecretParams struct {
	DatabaseID pgtype.UUID `json:"database_id"`
	Key        string      `json:"key"`
	Ciphertext string      `json:"ciphertext"`
}

func (q *Queries) CreateDatabaseSecret(ctx context.Context, arg CreateDatabaseSecretParams) (DatabaseSecret, error) {
	row := q.db.QueryRow(ctx, createDatabaseSecret, arg.DatabaseID, arg.Key, arg.Ciphertext)
	var i DatabaseSecret
	err := row.Scan(
		&i.ID,
		&i.DatabaseID,
		&i.Key,
		&i.Ciphertext,
		&i.CreatedAt,
	)
	return i, err
}

const getDatabase = `-- name: GetDatabase :one
SELECT id, user_id, server_id, name, engine, version, status, container_id, public_port, storage_path, created_at, updated_at, deleted_at FROM databases
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetDatabase(ctx context.Context, id pgtype.UUID) (Database, error) {
	row := q.db.QueryRow(ctx, getDatabase, id)
	var i Database
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ServerID,
		&i.Name,
		&i.Engine,
		&i.Version,
		&i.Status,
		&i.ContainerID,
		&i.PublicPort,
		&i.StoragePath,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listDatabaseSecrets = `-- name: ListDatabaseSecrets :many
SELECT id, database_id, key, ciphertext, created_at FROM database_secrets
WHERE database_id = $1
ORDER BY key ASC
`

func (q *Queries) ListDatabaseSecrets(ctx context.Context, databaseID pgtype.UUID) ([]DatabaseSecret, error) {
	rows, err := q.db.Query(ctx, listDatabaseSecrets, databaseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DatabaseSecret{}
	for rows.Next() {
		var i DatabaseSecret
		if err := rows.Scan(
			&i.ID,
			&i.DatabaseID,
			&i.Key,
			&i.Ciphertext,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDatabasesByUser = `-- name: ListDatabasesByUser :many
SELECT id, user_id, server_id, name, engine, version, status, container_id, public_port, storage_path, created_at, updated_at, deleted_at FROM databases
WHERE user_id = $1 AND deleted_at IS NULL
ORDER BY created_at DESC, id DESC
`

func (q *Queries) ListDatabasesByUser(ctx context.Context, userID pgtype.UUID) ([]Database, error) {
	rows, err := q.db.Query(ctx, listDatabasesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Database{}
	for rows.Next() {
		var i Database
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ServerID,
			&i.Name,
			&i.Engine,
			&i.Version,
			&i.Status,
			&i.ContainerID,
			&i.PublicPort,
			&i.StoragePath,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteDatabase = `-- name: SoftDeleteDatabase :one
UPDATE databases
SET status = 'deleting',
    deleted_at = now(),
    updated_at = now()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, user_id, server_id, name, engine, version, status, container_id, public_port, storage_path, created_at, updated_at, deleted_at
`

func (q *Queries) SoftDeleteDatabase(ctx context.Context, id pgtype.UUID) (Database, error) {
	row := q.db.QueryRow(ctx, softDeleteDatabase, id)
	var i Database
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ServerID,
		&i.Name,
		&i.Engine,
		&i.Version,
		&i.Status,
		&i.ContainerID,
		&i.PublicPort,
		&i.StoragePath,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateDatabase = `-- name: UpdateDatabase :one
UPDATE databases
SET name = $2,
    status = $3,
    container_id = $4,
    updated_at = now()
WHERE id = $1
RETURNING id, user_id, server_id, name, engine, version, status, container_id, public_port, storage_path, created_at, updated_at, deleted_at
`

type UpdateDatabaseParams struct {
	ID          pgtype.UUID `json:"id"`
	Name        string      `json:"name"`
	Status      string      `json:"status"`
	ContainerID string      `json:"container_id"`
}

func (q *Queries) UpdateDatabase(ctx context.Context, arg UpdateDatabaseParams) (Database, error) {
	row := q.db.QueryRow(ctx, updateDatabase,
		arg.ID,
		arg.Name,
		arg.Status,
		arg.ContainerID,
	)
	var i Database
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ServerID,
		&i.Name,
		&i.Engine,
		&i.Version,
		&i.Status,
		&i.ContainerID,
		&i.PublicPort,
		&i.StoragePath,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
