// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: deploy.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const clearEnvVarsByApp = `-- name: ClearEnvVarsByApp :exec
DELETE FROM env_vars WHERE application_id = $1
`

func (q *Queries) ClearEnvVarsByApp(ctx context.Context, applicationID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, clearEnvVarsByApp, applicationID)
	return err
}

const clearSecretsByApp = `-- name: ClearSecretsByApp :exec
DELETE FROM secrets WHERE application_id = $1
`

func (q *Queries) ClearSecretsByApp(ctx context.Context, applicationID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, clearSecretsByApp, applicationID)
	return err
}

const clearStoragesByApp = `-- name: ClearStoragesByApp :exec
DELETE FROM storages WHERE application_id = $1
`

func (q *Queries) ClearStoragesByApp(ctx context.Context, applicationID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, clearStoragesByApp, applicationID)
	return err
}

const createApplication = `-- name: CreateApplication :one
INSERT INTO applications (
    user_id, server_id, name, provider, repo, clone_url,
    branch, build_pack, base_domain, port, host_port
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, user_id, server_id, name, provider, repo, clone_url, branch, build_pack, base_domain, port, host_port, created_at, updated_at
`

type CreateApplicationParams struct {
	UserID     pgtype.UUID `json:"user_id"`
	ServerID   pgtype.UUID `json:"server_id"`
	Name       string      `json:"name"`
	Provider   string      `json:"provider"`
	Repo       string      `json:"repo"`
	CloneUrl   string      `json:"clone_url"`
	Branch     string      `json:"branch"`
	BuildPack  string      `json:"build_pack"`
	BaseDomain string      `json:"base_domain"`
	Port       int32       `json:"port"`
	HostPort   int32       `json:"host_port"`
}

func (q *Queries) CreateApplication(ctx context.Context, arg CreateApplicationParams) (Application, error) {
	row := q.db.QueryRow(ctx, createApplication,
		arg.UserID,
		arg.ServerID,
		arg.Name,
		arg.Provider,
		arg.Repo,
		arg.CloneUrl,
		arg.Branch,
		arg.BuildPack,
		arg.BaseDomain,
		arg.Port,
		arg.HostPort,
	)
	var i Application
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ServerID,
		&i.Name,
		&i.Provider,
		&i.Repo,
		&i.CloneUrl,
		&i.Branch,
		&i.BuildPack,
		&i.BaseDomain,
		&i.Port,
		&i.HostPort,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createDeployment = `-- name: CreateDeployment :one
INSERT INTO deployments (
    application_id, kind, state, image_tag, registry_image, digest, rollback_from
)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, application_id, kind, state, image_tag, registry_image, digest, error, attempt, container_id, rollback_from, started_at, finished_at, created_at, updated_at
`

type CreateDeploymentParams struct {
	ApplicationID pgtype.UUID `json:"application_id"`
	Kind          string      `json:"kind"`
	State         string      `json:"state"`
	ImageTag      string      `json:"image_tag"`
	RegistryImage string      `json:"registry_image"`
	Digest        string      `json:"digest"`
	RollbackFrom  pgtype.UUID `json:"rollback_from"`
}

func (q *Queries) CreateDeployment(ctx context.Context, arg CreateDeploymentParams) (Deployment, error) {
	row := q.db.QueryRow(ctx, createDeployment,
		arg.ApplicationID,
		arg.Kind,
		arg.State,
		arg.ImageTag,
		arg.RegistryImage,
		arg.Digest,
		arg.RollbackFrom,
	)
	var i Deployment
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.Kind,
		&i.State,
		&i.ImageTag,
		&i.RegistryImage,
		&i.Digest,
		&i.Error,
		&i.Attempt,
		&i.ContainerID,
		&i.RollbackFrom,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteApplication = `-- name: DeleteApplication :exec
DELETE FROM applications WHERE id = $1
`

func (q *Queries) DeleteApplication(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteApplication, id)
	return err
}

const failStaleDeployments = `-- name: FailStaleDeployments :execrows
UPDATE deployments
SET state = 'failed',
    error = 'control plane restarted before the deployment finished',
    finished_at = now(),
    updated_at = now()
WHERE state NOT IN ('running', 'failed')
`

// Boot-time recovery: a deployment left in a non-terminal state by a previous
// control plane process can never resume, and its row would keep blocking the
// active-deployment partial unique index. Mark those rows failed so the index
// unblocks. Running deployments are left alone (their container is the state),
// and the worker pool is empty when this runs at service construction.
func (q *Queries) FailStaleDeployments(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, failStaleDeployments)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getActiveDeploymentByApp = `-- name: GetActiveDeploymentByApp :one
SELECT id, application_id, kind, state, image_tag, registry_image, digest, error, attempt, container_id, rollback_from, started_at, finished_at, created_at, updated_at FROM deployments
WHERE application_id = $1 AND state NOT IN ('running', 'failed')
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetActiveDeploymentByApp(ctx context.Context, applicationID pgtype.UUID) (Deployment, error) {
	row := q.db.QueryRow(ctx, getActiveDeploymentByApp, applicationID)
	var i Deployment
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.Kind,
		&i.State,
		&i.ImageTag,
		&i.RegistryImage,
		&i.Digest,
		&i.Error,
		&i.Attempt,
		&i.ContainerID,
		&i.RollbackFrom,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getApplication = `-- name: GetApplication :one
SELECT id, user_id, server_id, name, provider, repo, clone_url, branch, build_pack, base_domain, port, host_port, created_at, updated_at FROM applications WHERE id = $1
`

func (q *Queries) GetApplication(ctx context.Context, id pgtype.UUID) (Application, error) {
	row := q.db.QueryRow(ctx, getApplication, id)
	var i Application
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ServerID,
		&i.Name,
		&i.Provider,
		&i.Repo,
		&i.CloneUrl,
		&i.Branch,
		&i.BuildPack,
		&i.BaseDomain,
		&i.Port,
		&i.HostPort,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDeployment = `-- name: GetDeployment :one
SELECT id, application_id, kind, state, image_tag, registry_image, digest, error, attempt, container_id, rollback_from, started_at, finished_at, created_at, updated_at FROM deployments
WHERE id = $1 AND application_id = $2
`

type GetDeploymentParams struct {
	ID            pgtype.UUID `json:"id"`
	ApplicationID pgtype.UUID `json:"application_id"`
}

func (q *Queries) GetDeployment(ctx context.Context, arg GetDeploymentParams) (Deployment, error) {
	row := q.db.QueryRow(ctx, getDeployment, arg.ID, arg.ApplicationID)
	var i Deployment
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.Kind,
		&i.State,
		&i.ImageTag,
		&i.RegistryImage,
		&i.Digest,
		&i.Error,
		&i.Attempt,
		&i.ContainerID,
		&i.RollbackFrom,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertEnvVar = `-- name: InsertEnvVar :one
INSERT INTO env_vars (application_id, key, value)
VALUES ($1, $2, $3)
RETURNING id, application_id, key, value, created_at
`

type InsertEnvVarParams struct {
	ApplicationID pgtype.UUID `json:"application_id"`
	Key           string      `json:"key"`
	Value         string      `json:"value"`
}

func (q *Queries) InsertEnvVar(ctx context.Context, arg InsertEnvVarParams) (EnvVar, error) {
	row := q.db.QueryRow(ctx, insertEnvVar, arg.ApplicationID, arg.Key, arg.Value)
	var i EnvVar
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.Key,
		&i.Value,
		&i.CreatedAt,
	)
	return i, err
}

const insertSecret = `-- name: InsertSecret :one
INSERT INTO secrets (id, application_id, key, ciphertext)
VALUES ($1, $2, $3, $4)
RETURNING id, application_id, key, ciphertext, created_at
`

type InsertSecretParams struct {
	ID            pgtype.UUID `json:"id"`
	ApplicationID pgtype.UUID `json:"application_id"`
	Key           string      `json:"key"`
	Ciphertext    string      `json:"ciphertext"`
}

// The id is written explicitly: it is the stable `secret:<id>` reference the
// API hands out for a sealed value, so re-writing a secret keeps its reference.
func (q *Queries) InsertSecret(ctx context.Context, arg InsertSecretParams) (Secret, error) {
	row := q.db.QueryRow(ctx, insertSecret,
		arg.ID,
		arg.ApplicationID,
		arg.Key,
		arg.Ciphertext,
	)
	var i Secret
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.Key,
		&i.Ciphertext,
		&i.CreatedAt,
	)
	return i, err
}

const insertStorage = `-- name: InsertStorage :one
INSERT INTO storages (application_id, name, host_path, container_path)
VALUES ($1, $2, $3, $4)
RETURNING id, application_id, name, host_path, container_path, created_at
`

type InsertStorageParams struct {
	ApplicationID pgtype.UUID `json:"application_id"`
	Name          string      `json:"name"`
	HostPath      string      `json:"host_path"`
	ContainerPath string      `json:"container_path"`
}

func (q *Queries) InsertStorage(ctx context.Context, arg InsertStorageParams) (Storage, error) {
	row := q.db.QueryRow(ctx, insertStorage,
		arg.ApplicationID,
		arg.Name,
		arg.HostPath,
		arg.ContainerPath,
	)
	var i Storage
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.Name,
		&i.HostPath,
		&i.ContainerPath,
		&i.CreatedAt,
	)
	return i, err
}

const listApplicationsByUser = `-- name: ListApplicationsByUser :many
SELECT id, user_id, server_id, name, provider, repo, clone_url, branch, build_pack, base_domain, port, host_port, created_at, updated_at FROM applications
WHERE user_id = $1
ORDER BY created_at DESC, id DESC
`

func (q *Queries) ListApplicationsByUser(ctx context.Context, userID pgtype.UUID) ([]Application, error) {
	rows, err := q.db.Query(ctx, listApplicationsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Application{}
	for rows.Next() {
		var i Application
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ServerID,
			&i.Name,
			&i.Provider,
			&i.Repo,
			&i.CloneUrl,
			&i.Branch,
			&i.BuildPack,
			&i.BaseDomain,
			&i.Port,
			&i.HostPort,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeploymentsByApp = `-- name: ListDeploymentsByApp :many
SELECT id, application_id, kind, state, image_tag, registry_image, digest, error, attempt, container_id, rollback_from, started_at, finished_at, created_at, updated_at FROM deployments
WHERE application_id = $1
ORDER BY created_at DESC, id DESC
`

func (q *Queries) ListDeploymentsByApp(ctx context.Context, applicationID pgtype.UUID) ([]Deployment, error) {
	rows, err := q.db.Query(ctx, listDeploymentsByApp, applicationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Deployment{}
	for rows.Next() {
		var i Deployment
		if err := rows.Scan(
			&i.ID,
			&i.ApplicationID,
			&i.Kind,
			&i.State,
			&i.ImageTag,
			&i.RegistryImage,
			&i.Digest,
			&i.Error,
			&i.Attempt,
			&i.ContainerID,
			&i.RollbackFrom,
			&i.StartedAt,
			&i.FinishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnvVarsByApp = `-- name: ListEnvVarsByApp :many
SELECT id, application_id, key, value, created_at FROM env_vars
WHERE application_id = $1
ORDER BY key ASC
`

func (q *Queries) ListEnvVarsByApp(ctx context.Context, applicationID pgtype.UUID) ([]EnvVar, error) {
	rows, err := q.db.Query(ctx, listEnvVarsByApp, applicationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EnvVar{}
	for rows.Next() {
		var i EnvVar
		if err := rows.Scan(
			&i.ID,
			&i.ApplicationID,
			&i.Key,
			&i.Value,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSecretsByApp = `-- name: ListSecretsByApp :many
SELECT id, application_id, key, ciphertext, created_at FROM secrets
WHERE application_id = $1
ORDER BY key ASC
`

func (q *Queries) ListSecretsByApp(ctx context.Context, applicationID pgtype.UUID) ([]Secret, error) {
	rows, err := q.db.Query(ctx, listSecretsByApp, applicationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Secret{}
	for rows.Next() {
		var i Secret
		if err := rows.Scan(
			&i.ID,
			&i.ApplicationID,
			&i.Key,
			&i.Ciphertext,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStoragesByApp = `-- name: ListStoragesByApp :many
SELECT id, application_id, name, host_path, container_path, created_at FROM storages
WHERE application_id = $1
ORDER BY name ASC
`

func (q *Queries) ListStoragesByApp(ctx context.Context, applicationID pgtype.UUID) ([]Storage, error) {
	rows, err := q.db.Query(ctx, listStoragesByApp, applicationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Storage{}
	for rows.Next() {
		var i Storage
		if err := rows.Scan(
			&i.ID,
			&i.ApplicationID,
			&i.Name,
			&i.HostPath,
			&i.ContainerPath,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateApplication = `-- name: UpdateApplication :one
UPDATE applications
SET name = $2,
    branch = $3,
    build_pack = $4,
    base_domain = $5,
    port = $6,
    host_port = $7,
    server_id = $8,
    updated_at = now()
WHERE id = $1
RETURNING id, user_id, server_id, name, provider, repo, clone_url, branch, build_pack, base_domain, port, host_port, created_at, updated_at
`

type UpdateApplicationParams struct {
	ID         pgtype.UUID `json:"id"`
	Name       string      `json:"name"`
	Branch     string      `json:"branch"`
	BuildPack  string      `json:"build_pack"`
	BaseDomain string      `json:"base_domain"`
	Port       int32       `json:"port"`
	HostPort   int32       `json:"host_port"`
	ServerID   pgtype.UUID `json:"server_id"`
}

func (q *Queries) UpdateApplication(ctx context.Context, arg UpdateApplicationParams) (Application, error) {
	row := q.db.QueryRow(ctx, updateApplication,
		arg.ID,
		arg.Name,
		arg.Branch,
		arg.BuildPack,
		arg.BaseDomain,
		arg.Port,
		arg.HostPort,
		arg.ServerID,
	)
	var i Application
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ServerID,
		&i.Name,
		&i.Provider,
		&i.Repo,
		&i.CloneUrl,
		&i.Branch,
		&i.BuildPack,
		&i.BaseDomain,
		&i.Port,
		&i.HostPort,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateDeployment = `-- name: UpdateDeployment :one
UPDATE deployments
SET state = $2,
    image_tag = $3,
    registry_image = $4,
    digest = $5,
    error = $6,
    attempt = $7,
    container_id = $8,
    started_at = $9,
    finished_at = $10,
    updated_at = now()
WHERE id = $1
RETURNING id, application_id, kind, state, image_tag, registry_image, digest, error, attempt, container_id, rollback_from, started_at, finished_at, created_at, updated_at
`

type UpdateDeploymentParams struct {
	ID            pgtype.UUID        `json:"id"`
	State         string             `json:"state"`
	ImageTag      string             `json:"image_tag"`
	RegistryImage string             `json:"registry_image"`
	Digest        string             `json:"digest"`
	Error         string             `json:"error"`
	Attempt       int32              `json:"attempt"`
	ContainerID   string             `json:"container_id"`
	StartedAt     pgtype.Timestamptz `json:"started_at"`
	FinishedAt    pgtype.Timestamptz `json:"finished_at"`
}

func (q *Queries) UpdateDeployment(ctx context.Context, arg UpdateDeploymentParams) (Deployment, error) {
	row := q.db.QueryRow(ctx, updateDeployment,
		arg.ID,
		arg.State,
		arg.ImageTag,
		arg.RegistryImage,
		arg.Digest,
		arg.Error,
		arg.Attempt,
		arg.ContainerID,
		arg.StartedAt,
		arg.FinishedAt,
	)
	var i Deployment
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.Kind,
		&i.State,
		&i.ImageTag,
		&i.RegistryImage,
		&i.Digest,
		&i.Error,
		&i.Attempt,
		&i.ContainerID,
		&i.RollbackFrom,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
