// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: deploy_keys.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createApplicationDeployKey = `-- name: CreateApplicationDeployKey :one
INSERT INTO application_deploy_keys (
    application_id, private_key_id, provider, repo, provider_key_id, fingerprint, public_key
)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, application_id, private_key_id, provider, repo, provider_key_id, fingerprint, public_key, created_at, updated_at
`

type CreateApplicationDeployKeyParams struct {
	ApplicationID pgtype.UUID `json:"application_id"`
	PrivateKeyID  pgtype.UUID `json:"private_key_id"`
	Provider      string      `json:"provider"`
	Repo          string      `json:"repo"`
	ProviderKeyID string      `json:"provider_key_id"`
	Fingerprint   string      `json:"fingerprint"`
	PublicKey     string      `json:"public_key"`
}

func (q *Queries) CreateApplicationDeployKey(ctx context.Context, arg CreateApplicationDeployKeyParams) (ApplicationDeployKey, error) {
	row := q.db.QueryRow(ctx, createApplicationDeployKey,
		arg.ApplicationID,
		arg.PrivateKeyID,
		arg.Provider,
		arg.Repo,
		arg.ProviderKeyID,
		arg.Fingerprint,
		arg.PublicKey,
	)
	var i ApplicationDeployKey
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.PrivateKeyID,
		&i.Provider,
		&i.Repo,
		&i.ProviderKeyID,
		&i.Fingerprint,
		&i.PublicKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteApplicationDeployKey = `-- name: DeleteApplicationDeployKey :one
DELETE FROM application_deploy_keys
WHERE application_id = $1
RETURNING id, application_id, private_key_id, provider, repo, provider_key_id, fingerprint, public_key, created_at, updated_at
`

func (q *Queries) DeleteApplicationDeployKey(ctx context.Context, applicationID pgtype.UUID) (ApplicationDeployKey, error) {
	row := q.db.QueryRow(ctx, deleteApplicationDeployKey, applicationID)
	var i ApplicationDeployKey
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.PrivateKeyID,
		&i.Provider,
		&i.Repo,
		&i.ProviderKeyID,
		&i.Fingerprint,
		&i.PublicKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getApplicationDeployKey = `-- name: GetApplicationDeployKey :one
SELECT id, application_id, private_key_id, provider, repo, provider_key_id, fingerprint, public_key, created_at, updated_at FROM application_deploy_keys
WHERE application_id = $1
`

func (q *Queries) GetApplicationDeployKey(ctx context.Context, applicationID pgtype.UUID) (ApplicationDeployKey, error) {
	row := q.db.QueryRow(ctx, getApplicationDeployKey, applicationID)
	var i ApplicationDeployKey
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.PrivateKeyID,
		&i.Provider,
		&i.Repo,
		&i.ProviderKeyID,
		&i.Fingerprint,
		&i.PublicKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
