// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: deploy.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const applicationNameInEnvironment = `-- name: ApplicationNameInEnvironment :one
SELECT EXISTS (
    SELECT 1 FROM applications
    WHERE environment_id = $1 AND name = $2 AND id <> $3
)
`

type ApplicationNameInEnvironmentParams struct {
	EnvironmentID pgtype.UUID `json:"environment_id"`
	Name          string      `json:"name"`
	ID            pgtype.UUID `json:"id"`
}

// The move-collision pre-check: whether the environment holds another
// application with the name (exact match, like the unique index).
func (q *Queries) ApplicationNameInEnvironment(ctx context.Context, arg ApplicationNameInEnvironmentParams) (bool, error) {
	row := q.db.QueryRow(ctx, applicationNameInEnvironment, arg.EnvironmentID, arg.Name, arg.ID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const clearEnvVarsByApp = `-- name: ClearEnvVarsByApp :exec
DELETE FROM env_vars WHERE application_id = $1
`

func (q *Queries) ClearEnvVarsByApp(ctx context.Context, applicationID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, clearEnvVarsByApp, applicationID)
	return err
}

const clearSecretsByApp = `-- name: ClearSecretsByApp :exec
DELETE FROM secrets WHERE application_id = $1
`

func (q *Queries) ClearSecretsByApp(ctx context.Context, applicationID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, clearSecretsByApp, applicationID)
	return err
}

const clearStoragesByApp = `-- name: ClearStoragesByApp :exec
DELETE FROM storages WHERE application_id = $1
`

func (q *Queries) ClearStoragesByApp(ctx context.Context, applicationID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, clearStoragesByApp, applicationID)
	return err
}

const countApplicationsByEnvironment = `-- name: CountApplicationsByEnvironment :one
SELECT count(*) FROM applications WHERE environment_id = $1 AND is_preview = false
`

// Live applications only: previews are hidden from the default listing, so
// the display counts match it. Delete guards consult the preview counts
// below instead.
func (q *Queries) CountApplicationsByEnvironment(ctx context.Context, environmentID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countApplicationsByEnvironment, environmentID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countApplicationsByProject = `-- name: CountApplicationsByProject :one
SELECT count(*) FROM applications a
JOIN environments e ON e.id = a.environment_id
WHERE e.project_id = $1 AND a.is_preview = false
`

func (q *Queries) CountApplicationsByProject(ctx context.Context, projectID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countApplicationsByProject, projectID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPreviewApplicationsByEnvironment = `-- name: CountPreviewApplicationsByEnvironment :one
SELECT count(*) FROM applications WHERE environment_id = $1 AND is_preview = true
`

// Live previews of one environment: they stay out of every count and
// listing, but they still block the environment delete.
func (q *Queries) CountPreviewApplicationsByEnvironment(ctx context.Context, environmentID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countPreviewApplicationsByEnvironment, environmentID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPreviewApplicationsByProject = `-- name: CountPreviewApplicationsByProject :one
SELECT count(*) FROM applications a
JOIN environments e ON e.id = a.environment_id
WHERE e.project_id = $1 AND a.is_preview = true
`

// Live previews of every environment of one project (see above).
func (q *Queries) CountPreviewApplicationsByProject(ctx context.Context, projectID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countPreviewApplicationsByProject, projectID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createApplication = `-- name: CreateApplication :one
INSERT INTO applications (
    id, user_id, server_id, environment_id, name, provider, repo, clone_url,
    branch, build_pack, base_domain, port, host_port, team_id, is_preview,
    source_type
)
VALUES (
    COALESCE($1::uuid, gen_random_uuid()),
    $2, $3, $4, $5, $6,
    $7, $8, $9, $10,
    $11, $12, $13, $14,
    -- Direct sqlc callers (fixtures, previews) may pass an empty source
    -- type; COALESCE maps it onto the default so the CHECK never sees it.
    -- The deploy repository normalizes the same way in Go.
    $15, COALESCE(NULLIF($16, ''), 'git_public')
)
RETURNING id, user_id, server_id, name, provider, repo, clone_url, branch, build_pack, base_domain, port, host_port, created_at, updated_at, base_domain_disabled, team_id, is_preview, environment_id, source_type
`

type CreateApplicationParams struct {
	ID            pgtype.UUID `json:"id"`
	UserID        pgtype.UUID `json:"user_id"`
	ServerID      pgtype.UUID `json:"server_id"`
	EnvironmentID pgtype.UUID `json:"environment_id"`
	Name          string      `json:"name"`
	Provider      string      `json:"provider"`
	Repo          string      `json:"repo"`
	CloneUrl      string      `json:"clone_url"`
	Branch        string      `json:"branch"`
	BuildPack     string      `json:"build_pack"`
	BaseDomain    string      `json:"base_domain"`
	Port          int32       `json:"port"`
	HostPort      int32       `json:"host_port"`
	TeamID        pgtype.UUID `json:"team_id"`
	IsPreview     bool        `json:"is_preview"`
	SourceType    interface{} `json:"source_type"`
}

// The id is optional: a caller that must know the application id before the
// insert (storage host paths are confined to <managed root>/<app id>) passes
// one, and COALESCE keeps the database-generated default for every other
// caller.
func (q *Queries) CreateApplication(ctx context.Context, arg CreateApplicationParams) (Application, error) {
	row := q.db.QueryRow(ctx, createApplication,
		arg.ID,
		arg.UserID,
		arg.ServerID,
		arg.EnvironmentID,
		arg.Name,
		arg.Provider,
		arg.Repo,
		arg.CloneUrl,
		arg.Branch,
		arg.BuildPack,
		arg.BaseDomain,
		arg.Port,
		arg.HostPort,
		arg.TeamID,
		arg.IsPreview,
		arg.SourceType,
	)
	var i Application
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ServerID,
		&i.Name,
		&i.Provider,
		&i.Repo,
		&i.CloneUrl,
		&i.Branch,
		&i.BuildPack,
		&i.BaseDomain,
		&i.Port,
		&i.HostPort,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BaseDomainDisabled,
		&i.TeamID,
		&i.IsPreview,
		&i.EnvironmentID,
		&i.SourceType,
	)
	return i, err
}

const createDeployment = `-- name: CreateDeployment :one
INSERT INTO deployments (
    application_id, kind, state, image_tag, registry_image, digest, rollback_from
)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, application_id, kind, state, image_tag, registry_image, digest, error, attempt, container_id, rollback_from, started_at, finished_at, created_at, updated_at
`

type CreateDeploymentParams struct {
	ApplicationID pgtype.UUID `json:"application_id"`
	Kind          string      `json:"kind"`
	State         string      `json:"state"`
	ImageTag      string      `json:"image_tag"`
	RegistryImage string      `json:"registry_image"`
	Digest        string      `json:"digest"`
	RollbackFrom  pgtype.UUID `json:"rollback_from"`
}

func (q *Queries) CreateDeployment(ctx context.Context, arg CreateDeploymentParams) (Deployment, error) {
	row := q.db.QueryRow(ctx, createDeployment,
		arg.ApplicationID,
		arg.Kind,
		arg.State,
		arg.ImageTag,
		arg.RegistryImage,
		arg.Digest,
		arg.RollbackFrom,
	)
	var i Deployment
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.Kind,
		&i.State,
		&i.ImageTag,
		&i.RegistryImage,
		&i.Digest,
		&i.Error,
		&i.Attempt,
		&i.ContainerID,
		&i.RollbackFrom,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteApplication = `-- name: DeleteApplication :exec
DELETE FROM applications WHERE id = $1
`

func (q *Queries) DeleteApplication(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteApplication, id)
	return err
}

const failStaleDeployments = `-- name: FailStaleDeployments :execrows
UPDATE deployments
SET state = 'failed',
    error = 'control plane restarted before the deployment finished',
    finished_at = now(),
    updated_at = now()
WHERE state NOT IN ('running', 'failed')
`

// Boot-time recovery: a deployment left in a non-terminal state by a previous
// control plane process can never resume, and its row would keep blocking the
// active-deployment partial unique index. Mark those rows failed so the index
// unblocks. Running deployments are left alone (their container is the state),
// and the worker pool is empty when this runs at service construction.
func (q *Queries) FailStaleDeployments(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, failStaleDeployments)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getActiveDeploymentByApp = `-- name: GetActiveDeploymentByApp :one
SELECT id, application_id, kind, state, image_tag, registry_image, digest, error, attempt, container_id, rollback_from, started_at, finished_at, created_at, updated_at FROM deployments
WHERE application_id = $1 AND state NOT IN ('running', 'failed')
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetActiveDeploymentByApp(ctx context.Context, applicationID pgtype.UUID) (Deployment, error) {
	row := q.db.QueryRow(ctx, getActiveDeploymentByApp, applicationID)
	var i Deployment
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.Kind,
		&i.State,
		&i.ImageTag,
		&i.RegistryImage,
		&i.Digest,
		&i.Error,
		&i.Attempt,
		&i.ContainerID,
		&i.RollbackFrom,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getApplication = `-- name: GetApplication :one
SELECT id, user_id, server_id, name, provider, repo, clone_url, branch, build_pack, base_domain, port, host_port, created_at, updated_at, base_domain_disabled, team_id, is_preview, environment_id, source_type FROM applications WHERE id = $1
`

func (q *Queries) GetApplication(ctx context.Context, id pgtype.UUID) (Application, error) {
	row := q.db.QueryRow(ctx, getApplication, id)
	var i Application
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ServerID,
		&i.Name,
		&i.Provider,
		&i.Repo,
		&i.CloneUrl,
		&i.Branch,
		&i.BuildPack,
		&i.BaseDomain,
		&i.Port,
		&i.HostPort,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BaseDomainDisabled,
		&i.TeamID,
		&i.IsPreview,
		&i.EnvironmentID,
		&i.SourceType,
	)
	return i, err
}

const getDeployment = `-- name: GetDeployment :one
SELECT id, application_id, kind, state, image_tag, registry_image, digest, error, attempt, container_id, rollback_from, started_at, finished_at, created_at, updated_at FROM deployments
WHERE id = $1 AND application_id = $2
`

type GetDeploymentParams struct {
	ID            pgtype.UUID `json:"id"`
	ApplicationID pgtype.UUID `json:"application_id"`
}

func (q *Queries) GetDeployment(ctx context.Context, arg GetDeploymentParams) (Deployment, error) {
	row := q.db.QueryRow(ctx, getDeployment, arg.ID, arg.ApplicationID)
	var i Deployment
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.Kind,
		&i.State,
		&i.ImageTag,
		&i.RegistryImage,
		&i.Digest,
		&i.Error,
		&i.Attempt,
		&i.ContainerID,
		&i.RollbackFrom,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertEnvVar = `-- name: InsertEnvVar :one
INSERT INTO env_vars (application_id, key, value)
VALUES ($1, $2, $3)
RETURNING id, application_id, key, value, created_at
`

type InsertEnvVarParams struct {
	ApplicationID pgtype.UUID `json:"application_id"`
	Key           string      `json:"key"`
	Value         string      `json:"value"`
}

func (q *Queries) InsertEnvVar(ctx context.Context, arg InsertEnvVarParams) (EnvVar, error) {
	row := q.db.QueryRow(ctx, insertEnvVar, arg.ApplicationID, arg.Key, arg.Value)
	var i EnvVar
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.Key,
		&i.Value,
		&i.CreatedAt,
	)
	return i, err
}

const insertSecret = `-- name: InsertSecret :one
INSERT INTO secrets (id, application_id, key, ciphertext)
VALUES ($1, $2, $3, $4)
RETURNING id, application_id, key, ciphertext, created_at
`

type InsertSecretParams struct {
	ID            pgtype.UUID `json:"id"`
	ApplicationID pgtype.UUID `json:"application_id"`
	Key           string      `json:"key"`
	Ciphertext    string      `json:"ciphertext"`
}

// The id is written explicitly: it is the stable `secret:<id>` reference the
// API hands out for a sealed value, so re-writing a secret keeps its reference.
func (q *Queries) InsertSecret(ctx context.Context, arg InsertSecretParams) (Secret, error) {
	row := q.db.QueryRow(ctx, insertSecret,
		arg.ID,
		arg.ApplicationID,
		arg.Key,
		arg.Ciphertext,
	)
	var i Secret
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.Key,
		&i.Ciphertext,
		&i.CreatedAt,
	)
	return i, err
}

const insertStorage = `-- name: InsertStorage :one
INSERT INTO storages (application_id, name, host_path, container_path)
VALUES ($1, $2, $3, $4)
RETURNING id, application_id, name, host_path, container_path, created_at
`

type InsertStorageParams struct {
	ApplicationID pgtype.UUID `json:"application_id"`
	Name          string      `json:"name"`
	HostPath      string      `json:"host_path"`
	ContainerPath string      `json:"container_path"`
}

func (q *Queries) InsertStorage(ctx context.Context, arg InsertStorageParams) (Storage, error) {
	row := q.db.QueryRow(ctx, insertStorage,
		arg.ApplicationID,
		arg.Name,
		arg.HostPath,
		arg.ContainerPath,
	)
	var i Storage
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.Name,
		&i.HostPath,
		&i.ContainerPath,
		&i.CreatedAt,
	)
	return i, err
}

const listApplicationsByEnvironment = `-- name: ListApplicationsByEnvironment :many
SELECT id, user_id, server_id, name, provider, repo, clone_url, branch, build_pack, base_domain, port, host_port, created_at, updated_at, base_domain_disabled, team_id, is_preview, environment_id, source_type FROM applications
WHERE environment_id = $1 AND (is_preview = false OR $2::bool = true)
ORDER BY created_at DESC, id DESC
`

type ListApplicationsByEnvironmentParams struct {
	EnvironmentID   pgtype.UUID `json:"environment_id"`
	IncludePreviews bool        `json:"include_previews"`
}

// One environment's applications, newest first. Previews stay out of the
// default listing; the resources endpoint passes true for ?previews=1.
func (q *Queries) ListApplicationsByEnvironment(ctx context.Context, arg ListApplicationsByEnvironmentParams) ([]Application, error) {
	rows, err := q.db.Query(ctx, listApplicationsByEnvironment, arg.EnvironmentID, arg.IncludePreviews)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Application{}
	for rows.Next() {
		var i Application
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ServerID,
			&i.Name,
			&i.Provider,
			&i.Repo,
			&i.CloneUrl,
			&i.Branch,
			&i.BuildPack,
			&i.BaseDomain,
			&i.Port,
			&i.HostPort,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.BaseDomainDisabled,
			&i.TeamID,
			&i.IsPreview,
			&i.EnvironmentID,
			&i.SourceType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listApplicationsByProject = `-- name: ListApplicationsByProject :many
SELECT a.id, a.user_id, a.server_id, a.name, a.provider, a.repo, a.clone_url, a.branch, a.build_pack, a.base_domain, a.port, a.host_port, a.created_at, a.updated_at, a.base_domain_disabled, a.team_id, a.is_preview, a.environment_id, a.source_type FROM applications a
JOIN environments e ON e.id = a.environment_id
WHERE e.project_id = $1 AND (a.is_preview = false OR $2::bool = true)
ORDER BY a.created_at DESC, a.id DESC
`

type ListApplicationsByProjectParams struct {
	ProjectID       pgtype.UUID `json:"project_id"`
	IncludePreviews bool        `json:"include_previews"`
}

// Every environment's applications of one project (the ?project_id= filter),
// newest first. Previews are included only on request, as above.
func (q *Queries) ListApplicationsByProject(ctx context.Context, arg ListApplicationsByProjectParams) ([]Application, error) {
	rows, err := q.db.Query(ctx, listApplicationsByProject, arg.ProjectID, arg.IncludePreviews)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Application{}
	for rows.Next() {
		var i Application
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ServerID,
			&i.Name,
			&i.Provider,
			&i.Repo,
			&i.CloneUrl,
			&i.Branch,
			&i.BuildPack,
			&i.BaseDomain,
			&i.Port,
			&i.HostPort,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.BaseDomainDisabled,
			&i.TeamID,
			&i.IsPreview,
			&i.EnvironmentID,
			&i.SourceType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listApplicationsByServer = `-- name: ListApplicationsByServer :many
SELECT id, name FROM applications
WHERE server_id = $1
ORDER BY created_at DESC, id DESC
`

type ListApplicationsByServerRow struct {
	ID   pgtype.UUID `json:"id"`
	Name string      `json:"name"`
}

// One node's applications (id and name only): the server-delete 409 names its
// blocking resources.
func (q *Queries) ListApplicationsByServer(ctx context.Context, serverID pgtype.UUID) ([]ListApplicationsByServerRow, error) {
	rows, err := q.db.Query(ctx, listApplicationsByServer, serverID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListApplicationsByServerRow{}
	for rows.Next() {
		var i ListApplicationsByServerRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listApplicationsByTeam = `-- name: ListApplicationsByTeam :many
SELECT id, user_id, server_id, name, provider, repo, clone_url, branch, build_pack, base_domain, port, host_port, created_at, updated_at, base_domain_disabled, team_id, is_preview, environment_id, source_type FROM applications
WHERE team_id = $1 AND is_preview = false
ORDER BY created_at DESC, id DESC
`

func (q *Queries) ListApplicationsByTeam(ctx context.Context, teamID pgtype.UUID) ([]Application, error) {
	rows, err := q.db.Query(ctx, listApplicationsByTeam, teamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Application{}
	for rows.Next() {
		var i Application
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ServerID,
			&i.Name,
			&i.Provider,
			&i.Repo,
			&i.CloneUrl,
			&i.Branch,
			&i.BuildPack,
			&i.BaseDomain,
			&i.Port,
			&i.HostPort,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.BaseDomainDisabled,
			&i.TeamID,
			&i.IsPreview,
			&i.EnvironmentID,
			&i.SourceType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listApplicationsByUser = `-- name: ListApplicationsByUser :many
SELECT id, user_id, server_id, name, provider, repo, clone_url, branch, build_pack, base_domain, port, host_port, created_at, updated_at, base_domain_disabled, team_id, is_preview, environment_id, source_type FROM applications
WHERE user_id = $1 AND is_preview = false
ORDER BY created_at DESC, id DESC
`

func (q *Queries) ListApplicationsByUser(ctx context.Context, userID pgtype.UUID) ([]Application, error) {
	rows, err := q.db.Query(ctx, listApplicationsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Application{}
	for rows.Next() {
		var i Application
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ServerID,
			&i.Name,
			&i.Provider,
			&i.Repo,
			&i.CloneUrl,
			&i.Branch,
			&i.BuildPack,
			&i.BaseDomain,
			&i.Port,
			&i.HostPort,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.BaseDomainDisabled,
			&i.TeamID,
			&i.IsPreview,
			&i.EnvironmentID,
			&i.SourceType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeploymentsByApp = `-- name: ListDeploymentsByApp :many
SELECT id, application_id, kind, state, image_tag, registry_image, digest, error, attempt, container_id, rollback_from, started_at, finished_at, created_at, updated_at FROM deployments
WHERE application_id = $1
ORDER BY created_at DESC, id DESC
`

func (q *Queries) ListDeploymentsByApp(ctx context.Context, applicationID pgtype.UUID) ([]Deployment, error) {
	rows, err := q.db.Query(ctx, listDeploymentsByApp, applicationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Deployment{}
	for rows.Next() {
		var i Deployment
		if err := rows.Scan(
			&i.ID,
			&i.ApplicationID,
			&i.Kind,
			&i.State,
			&i.ImageTag,
			&i.RegistryImage,
			&i.Digest,
			&i.Error,
			&i.Attempt,
			&i.ContainerID,
			&i.RollbackFrom,
			&i.StartedAt,
			&i.FinishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeploymentsByAppLimit = `-- name: ListDeploymentsByAppLimit :many
SELECT id, application_id, kind, state, image_tag, registry_image, digest, error, attempt, container_id, rollback_from, started_at, finished_at, created_at, updated_at FROM deployments
WHERE application_id = $1
ORDER BY created_at DESC, id DESC
LIMIT $2
`

type ListDeploymentsByAppLimitParams struct {
	ApplicationID pgtype.UUID `json:"application_id"`
	Limit         int32       `json:"limit"`
}

func (q *Queries) ListDeploymentsByAppLimit(ctx context.Context, arg ListDeploymentsByAppLimitParams) ([]Deployment, error) {
	rows, err := q.db.Query(ctx, listDeploymentsByAppLimit, arg.ApplicationID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Deployment{}
	for rows.Next() {
		var i Deployment
		if err := rows.Scan(
			&i.ID,
			&i.ApplicationID,
			&i.Kind,
			&i.State,
			&i.ImageTag,
			&i.RegistryImage,
			&i.Digest,
			&i.Error,
			&i.Attempt,
			&i.ContainerID,
			&i.RollbackFrom,
			&i.StartedAt,
			&i.FinishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnvVarsByApp = `-- name: ListEnvVarsByApp :many
SELECT id, application_id, key, value, created_at FROM env_vars
WHERE application_id = $1
ORDER BY key ASC
`

func (q *Queries) ListEnvVarsByApp(ctx context.Context, applicationID pgtype.UUID) ([]EnvVar, error) {
	rows, err := q.db.Query(ctx, listEnvVarsByApp, applicationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EnvVar{}
	for rows.Next() {
		var i EnvVar
		if err := rows.Scan(
			&i.ID,
			&i.ApplicationID,
			&i.Key,
			&i.Value,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSecretsByApp = `-- name: ListSecretsByApp :many
SELECT id, application_id, key, ciphertext, created_at FROM secrets
WHERE application_id = $1
ORDER BY key ASC
`

func (q *Queries) ListSecretsByApp(ctx context.Context, applicationID pgtype.UUID) ([]Secret, error) {
	rows, err := q.db.Query(ctx, listSecretsByApp, applicationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Secret{}
	for rows.Next() {
		var i Secret
		if err := rows.Scan(
			&i.ID,
			&i.ApplicationID,
			&i.Key,
			&i.Ciphertext,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStoragesByApp = `-- name: ListStoragesByApp :many
SELECT id, application_id, name, host_path, container_path, created_at FROM storages
WHERE application_id = $1
ORDER BY name ASC
`

func (q *Queries) ListStoragesByApp(ctx context.Context, applicationID pgtype.UUID) ([]Storage, error) {
	rows, err := q.db.Query(ctx, listStoragesByApp, applicationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Storage{}
	for rows.Next() {
		var i Storage
		if err := rows.Scan(
			&i.ID,
			&i.ApplicationID,
			&i.Name,
			&i.HostPath,
			&i.ContainerPath,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockApplication = `-- name: LockApplication :exec
SELECT id FROM applications WHERE id = $1 FOR UPDATE
`

// LockApplication takes a row lock on the parent application, serializing
// mutations of its child collections (env vars, secrets, storages). Without
// it, two transactions that clear an empty collection and then insert
// disjoint keys both see nothing to delete and commit their union — a merge
// where a replace was requested.
func (q *Queries) LockApplication(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, lockApplication, id)
	return err
}

const updateApplication = `-- name: UpdateApplication :one
UPDATE applications
SET name = $2,
    branch = $3,
    build_pack = $4,
    base_domain = $5,
    port = $6,
    host_port = $7,
    server_id = $8,
    base_domain_disabled = $9,
    environment_id = $10,
    updated_at = now()
WHERE id = $1
RETURNING id, user_id, server_id, name, provider, repo, clone_url, branch, build_pack, base_domain, port, host_port, created_at, updated_at, base_domain_disabled, team_id, is_preview, environment_id, source_type
`

type UpdateApplicationParams struct {
	ID                 pgtype.UUID `json:"id"`
	Name               string      `json:"name"`
	Branch             string      `json:"branch"`
	BuildPack          string      `json:"build_pack"`
	BaseDomain         string      `json:"base_domain"`
	Port               int32       `json:"port"`
	HostPort           int32       `json:"host_port"`
	ServerID           pgtype.UUID `json:"server_id"`
	BaseDomainDisabled bool        `json:"base_domain_disabled"`
	EnvironmentID      pgtype.UUID `json:"environment_id"`
}

func (q *Queries) UpdateApplication(ctx context.Context, arg UpdateApplicationParams) (Application, error) {
	row := q.db.QueryRow(ctx, updateApplication,
		arg.ID,
		arg.Name,
		arg.Branch,
		arg.BuildPack,
		arg.BaseDomain,
		arg.Port,
		arg.HostPort,
		arg.ServerID,
		arg.BaseDomainDisabled,
		arg.EnvironmentID,
	)
	var i Application
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ServerID,
		&i.Name,
		&i.Provider,
		&i.Repo,
		&i.CloneUrl,
		&i.Branch,
		&i.BuildPack,
		&i.BaseDomain,
		&i.Port,
		&i.HostPort,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BaseDomainDisabled,
		&i.TeamID,
		&i.IsPreview,
		&i.EnvironmentID,
		&i.SourceType,
	)
	return i, err
}

const updateDeployment = `-- name: UpdateDeployment :one
UPDATE deployments
SET state = $2,
    image_tag = $3,
    registry_image = $4,
    digest = $5,
    error = $6,
    attempt = $7,
    container_id = $8,
    started_at = $9,
    finished_at = $10,
    updated_at = now()
WHERE id = $1
RETURNING id, application_id, kind, state, image_tag, registry_image, digest, error, attempt, container_id, rollback_from, started_at, finished_at, created_at, updated_at
`

type UpdateDeploymentParams struct {
	ID            pgtype.UUID        `json:"id"`
	State         string             `json:"state"`
	ImageTag      string             `json:"image_tag"`
	RegistryImage string             `json:"registry_image"`
	Digest        string             `json:"digest"`
	Error         string             `json:"error"`
	Attempt       int32              `json:"attempt"`
	ContainerID   string             `json:"container_id"`
	StartedAt     pgtype.Timestamptz `json:"started_at"`
	FinishedAt    pgtype.Timestamptz `json:"finished_at"`
}

func (q *Queries) UpdateDeployment(ctx context.Context, arg UpdateDeploymentParams) (Deployment, error) {
	row := q.db.QueryRow(ctx, updateDeployment,
		arg.ID,
		arg.State,
		arg.ImageTag,
		arg.RegistryImage,
		arg.Digest,
		arg.Error,
		arg.Attempt,
		arg.ContainerID,
		arg.StartedAt,
		arg.FinishedAt,
	)
	var i Deployment
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.Kind,
		&i.State,
		&i.ImageTag,
		&i.RegistryImage,
		&i.Digest,
		&i.Error,
		&i.Attempt,
		&i.ContainerID,
		&i.RollbackFrom,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
