// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: git_credentials.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteApplicationGitCredential = `-- name: DeleteApplicationGitCredential :exec
DELETE FROM application_git_credentials WHERE application_id = $1
`

func (q *Queries) DeleteApplicationGitCredential(ctx context.Context, applicationID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteApplicationGitCredential, applicationID)
	return err
}

const getApplicationGitCredential = `-- name: GetApplicationGitCredential :one
SELECT application_id, username, ciphertext, created_at, updated_at FROM application_git_credentials
WHERE application_id = $1
`

func (q *Queries) GetApplicationGitCredential(ctx context.Context, applicationID pgtype.UUID) (ApplicationGitCredential, error) {
	row := q.db.QueryRow(ctx, getApplicationGitCredential, applicationID)
	var i ApplicationGitCredential
	err := row.Scan(
		&i.ApplicationID,
		&i.Username,
		&i.Ciphertext,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertApplicationGitCredential = `-- name: UpsertApplicationGitCredential :one
INSERT INTO application_git_credentials (application_id, username, ciphertext, updated_at)
VALUES ($1, $2, $3, now())
ON CONFLICT (application_id) DO UPDATE SET
    username = EXCLUDED.username,
    ciphertext = EXCLUDED.ciphertext,
    updated_at = now()
RETURNING application_id, username, ciphertext, created_at, updated_at
`

type UpsertApplicationGitCredentialParams struct {
	ApplicationID pgtype.UUID `json:"application_id"`
	Username      string      `json:"username"`
	Ciphertext    string      `json:"ciphertext"`
}

func (q *Queries) UpsertApplicationGitCredential(ctx context.Context, arg UpsertApplicationGitCredentialParams) (ApplicationGitCredential, error) {
	row := q.db.QueryRow(ctx, upsertApplicationGitCredential, arg.ApplicationID, arg.Username, arg.Ciphertext)
	var i ApplicationGitCredential
	err := row.Scan(
		&i.ApplicationID,
		&i.Username,
		&i.Ciphertext,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
