// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: githubapp.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countGitHubAppApplications = `-- name: CountGitHubAppApplications :one
SELECT count(*)::bigint FROM applications
WHERE user_id = $1 AND source_type = 'github_app' AND provider = 'github'
`

func (q *Queries) CountGitHubAppApplications(ctx context.Context, userID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countGitHubAppApplications, userID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createGitHubApp = `-- name: CreateGitHubApp :one
INSERT INTO github_apps (
    user_id, app_id, slug, name, base_url, api_base_url, client_id,
    webhook_secret_cipher, private_key_cipher
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, user_id, app_id, slug, name, base_url, api_base_url, client_id, webhook_secret_cipher, private_key_cipher, created_at, updated_at
`

type CreateGitHubAppParams struct {
	UserID              pgtype.UUID `json:"user_id"`
	AppID               int64       `json:"app_id"`
	Slug                string      `json:"slug"`
	Name                string      `json:"name"`
	BaseUrl             string      `json:"base_url"`
	ApiBaseUrl          string      `json:"api_base_url"`
	ClientID            string      `json:"client_id"`
	WebhookSecretCipher string      `json:"webhook_secret_cipher"`
	PrivateKeyCipher    string      `json:"private_key_cipher"`
}

func (q *Queries) CreateGitHubApp(ctx context.Context, arg CreateGitHubAppParams) (GithubApp, error) {
	row := q.db.QueryRow(ctx, createGitHubApp,
		arg.UserID,
		arg.AppID,
		arg.Slug,
		arg.Name,
		arg.BaseUrl,
		arg.ApiBaseUrl,
		arg.ClientID,
		arg.WebhookSecretCipher,
		arg.PrivateKeyCipher,
	)
	var i GithubApp
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AppID,
		&i.Slug,
		&i.Name,
		&i.BaseUrl,
		&i.ApiBaseUrl,
		&i.ClientID,
		&i.WebhookSecretCipher,
		&i.PrivateKeyCipher,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteGitHubApp = `-- name: DeleteGitHubApp :execrows
DELETE FROM github_apps WHERE id = $1 AND user_id = $2
`

type DeleteGitHubAppParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) DeleteGitHubApp(ctx context.Context, arg DeleteGitHubAppParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteGitHubApp, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteGitHubInstallation = `-- name: DeleteGitHubInstallation :execrows
DELETE FROM github_installations WHERE id = $1
`

func (q *Queries) DeleteGitHubInstallation(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteGitHubInstallation, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteGitHubRepoCache = `-- name: DeleteGitHubRepoCache :exec
DELETE FROM github_repo_cache WHERE github_app_id = $1 AND installation_id = $2
`

type DeleteGitHubRepoCacheParams struct {
	GithubAppID    pgtype.UUID `json:"github_app_id"`
	InstallationID int64       `json:"installation_id"`
}

func (q *Queries) DeleteGitHubRepoCache(ctx context.Context, arg DeleteGitHubRepoCacheParams) error {
	_, err := q.db.Exec(ctx, deleteGitHubRepoCache, arg.GithubAppID, arg.InstallationID)
	return err
}

const getGitHubAppByIDAndUser = `-- name: GetGitHubAppByIDAndUser :one
SELECT id, user_id, app_id, slug, name, base_url, api_base_url, client_id, webhook_secret_cipher, private_key_cipher, created_at, updated_at FROM github_apps WHERE id = $1 AND user_id = $2
`

type GetGitHubAppByIDAndUserParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) GetGitHubAppByIDAndUser(ctx context.Context, arg GetGitHubAppByIDAndUserParams) (GithubApp, error) {
	row := q.db.QueryRow(ctx, getGitHubAppByIDAndUser, arg.ID, arg.UserID)
	var i GithubApp
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AppID,
		&i.Slug,
		&i.Name,
		&i.BaseUrl,
		&i.ApiBaseUrl,
		&i.ClientID,
		&i.WebhookSecretCipher,
		&i.PrivateKeyCipher,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listGitHubAppsByInstallationID = `-- name: ListGitHubAppsByInstallationID :many
SELECT g.id, g.user_id, g.app_id, g.slug, g.name, g.base_url, g.api_base_url, g.client_id, g.webhook_secret_cipher, g.private_key_cipher, g.created_at, g.updated_at FROM github_apps g
JOIN github_installations i ON i.github_app_id = g.id
WHERE i.installation_id = $1
`

func (q *Queries) ListGitHubAppsByInstallationID(ctx context.Context, installationID int64) ([]GithubApp, error) {
	rows, err := q.db.Query(ctx, listGitHubAppsByInstallationID, installationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GithubApp{}
	for rows.Next() {
		var i GithubApp
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AppID,
			&i.Slug,
			&i.Name,
			&i.BaseUrl,
			&i.ApiBaseUrl,
			&i.ClientID,
			&i.WebhookSecretCipher,
			&i.PrivateKeyCipher,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGitHubAppsByUser = `-- name: ListGitHubAppsByUser :many
SELECT id, user_id, app_id, slug, name, base_url, api_base_url, client_id, webhook_secret_cipher, private_key_cipher, created_at, updated_at FROM github_apps
WHERE user_id = $1
ORDER BY created_at DESC, id DESC
`

func (q *Queries) ListGitHubAppsByUser(ctx context.Context, userID pgtype.UUID) ([]GithubApp, error) {
	rows, err := q.db.Query(ctx, listGitHubAppsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GithubApp{}
	for rows.Next() {
		var i GithubApp
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AppID,
			&i.Slug,
			&i.Name,
			&i.BaseUrl,
			&i.ApiBaseUrl,
			&i.ClientID,
			&i.WebhookSecretCipher,
			&i.PrivateKeyCipher,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGitHubInstallations = `-- name: ListGitHubInstallations :many
SELECT id, github_app_id, installation_id, account, created_at, updated_at FROM github_installations
WHERE github_app_id = $1
ORDER BY installation_id ASC
`

func (q *Queries) ListGitHubInstallations(ctx context.Context, githubAppID pgtype.UUID) ([]GithubInstallation, error) {
	rows, err := q.db.Query(ctx, listGitHubInstallations, githubAppID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GithubInstallation{}
	for rows.Next() {
		var i GithubInstallation
		if err := rows.Scan(
			&i.ID,
			&i.GithubAppID,
			&i.InstallationID,
			&i.Account,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGitHubRepoCache = `-- name: ListGitHubRepoCache :many
SELECT github_app_id, installation_id, external_id, name, full_name, private, default_branch, clone_url, ssh_url, html_url, cached_at FROM github_repo_cache
WHERE github_app_id = $1 AND installation_id = $2
ORDER BY full_name ASC
`

type ListGitHubRepoCacheParams struct {
	GithubAppID    pgtype.UUID `json:"github_app_id"`
	InstallationID int64       `json:"installation_id"`
}

func (q *Queries) ListGitHubRepoCache(ctx context.Context, arg ListGitHubRepoCacheParams) ([]GithubRepoCache, error) {
	rows, err := q.db.Query(ctx, listGitHubRepoCache, arg.GithubAppID, arg.InstallationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GithubRepoCache{}
	for rows.Next() {
		var i GithubRepoCache
		if err := rows.Scan(
			&i.GithubAppID,
			&i.InstallationID,
			&i.ExternalID,
			&i.Name,
			&i.FullName,
			&i.Private,
			&i.DefaultBranch,
			&i.CloneUrl,
			&i.SshUrl,
			&i.HtmlUrl,
			&i.CachedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertGitHubInstallation = `-- name: UpsertGitHubInstallation :one
INSERT INTO github_installations (github_app_id, installation_id, account)
VALUES ($1, $2, $3)
ON CONFLICT (github_app_id, installation_id) DO UPDATE
SET account = EXCLUDED.account,
    updated_at = now()
RETURNING id, github_app_id, installation_id, account, created_at, updated_at
`

type UpsertGitHubInstallationParams struct {
	GithubAppID    pgtype.UUID `json:"github_app_id"`
	InstallationID int64       `json:"installation_id"`
	Account        string      `json:"account"`
}

func (q *Queries) UpsertGitHubInstallation(ctx context.Context, arg UpsertGitHubInstallationParams) (GithubInstallation, error) {
	row := q.db.QueryRow(ctx, upsertGitHubInstallation, arg.GithubAppID, arg.InstallationID, arg.Account)
	var i GithubInstallation
	err := row.Scan(
		&i.ID,
		&i.GithubAppID,
		&i.InstallationID,
		&i.Account,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertGitHubRepoCache = `-- name: UpsertGitHubRepoCache :one
INSERT INTO github_repo_cache (
    github_app_id, installation_id, external_id, name, full_name, private,
    default_branch, clone_url, ssh_url, html_url, cached_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, now())
ON CONFLICT (github_app_id, installation_id, external_id) DO UPDATE
SET name = EXCLUDED.name,
    full_name = EXCLUDED.full_name,
    private = EXCLUDED.private,
    default_branch = EXCLUDED.default_branch,
    clone_url = EXCLUDED.clone_url,
    ssh_url = EXCLUDED.ssh_url,
    html_url = EXCLUDED.html_url,
    cached_at = now()
RETURNING github_app_id, installation_id, external_id, name, full_name, private, default_branch, clone_url, ssh_url, html_url, cached_at
`

type UpsertGitHubRepoCacheParams struct {
	GithubAppID    pgtype.UUID `json:"github_app_id"`
	InstallationID int64       `json:"installation_id"`
	ExternalID     string      `json:"external_id"`
	Name           string      `json:"name"`
	FullName       string      `json:"full_name"`
	Private        bool        `json:"private"`
	DefaultBranch  string      `json:"default_branch"`
	CloneUrl       string      `json:"clone_url"`
	SshUrl         string      `json:"ssh_url"`
	HtmlUrl        string      `json:"html_url"`
}

func (q *Queries) UpsertGitHubRepoCache(ctx context.Context, arg UpsertGitHubRepoCacheParams) (GithubRepoCache, error) {
	row := q.db.QueryRow(ctx, upsertGitHubRepoCache,
		arg.GithubAppID,
		arg.InstallationID,
		arg.ExternalID,
		arg.Name,
		arg.FullName,
		arg.Private,
		arg.DefaultBranch,
		arg.CloneUrl,
		arg.SshUrl,
		arg.HtmlUrl,
	)
	var i GithubRepoCache
	err := row.Scan(
		&i.GithubAppID,
		&i.InstallationID,
		&i.ExternalID,
		&i.Name,
		&i.FullName,
		&i.Private,
		&i.DefaultBranch,
		&i.CloneUrl,
		&i.SshUrl,
		&i.HtmlUrl,
		&i.CachedAt,
	)
	return i, err
}
