// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: instance_settings.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getInstanceSettings = `-- name: GetInstanceSettings :one
SELECT id, control_plane_url, instance_name, timezone, dns_servers, ipv4_mode, ipv4_address, ipv4_gateway, ipv6_enabled, ipv6_mode, ipv6_address, ipv6_gateway, hostname, ntp_enabled, ntp_servers, pending_network, pending_deadline, updated_at FROM instance_settings WHERE id = 1
`

func (q *Queries) GetInstanceSettings(ctx context.Context) (InstanceSetting, error) {
	row := q.db.QueryRow(ctx, getInstanceSettings)
	var i InstanceSetting
	err := row.Scan(
		&i.ID,
		&i.ControlPlaneUrl,
		&i.InstanceName,
		&i.Timezone,
		&i.DnsServers,
		&i.Ipv4Mode,
		&i.Ipv4Address,
		&i.Ipv4Gateway,
		&i.Ipv6Enabled,
		&i.Ipv6Mode,
		&i.Ipv6Address,
		&i.Ipv6Gateway,
		&i.Hostname,
		&i.NtpEnabled,
		&i.NtpServers,
		&i.PendingNetwork,
		&i.PendingDeadline,
		&i.UpdatedAt,
	)
	return i, err
}

const insertInstanceAudit = `-- name: InsertInstanceAudit :exec
INSERT INTO instance_settings_audit (actor_id, section, changes) VALUES ($1, $2, $3)
`

type InsertInstanceAuditParams struct {
	ActorID pgtype.UUID `json:"actor_id"`
	Section string      `json:"section"`
	Changes []byte      `json:"changes"`
}

func (q *Queries) InsertInstanceAudit(ctx context.Context, arg InsertInstanceAuditParams) error {
	_, err := q.db.Exec(ctx, insertInstanceAudit, arg.ActorID, arg.Section, arg.Changes)
	return err
}

const updateInstanceGeneral = `-- name: UpdateInstanceGeneral :one
UPDATE instance_settings
SET control_plane_url = $1, instance_name = $2, timezone = $3, updated_at = now()
WHERE id = 1
RETURNING id, control_plane_url, instance_name, timezone, dns_servers, ipv4_mode, ipv4_address, ipv4_gateway, ipv6_enabled, ipv6_mode, ipv6_address, ipv6_gateway, hostname, ntp_enabled, ntp_servers, pending_network, pending_deadline, updated_at
`

type UpdateInstanceGeneralParams struct {
	ControlPlaneUrl *string `json:"control_plane_url"`
	InstanceName    *string `json:"instance_name"`
	Timezone        *string `json:"timezone"`
}

func (q *Queries) UpdateInstanceGeneral(ctx context.Context, arg UpdateInstanceGeneralParams) (InstanceSetting, error) {
	row := q.db.QueryRow(ctx, updateInstanceGeneral, arg.ControlPlaneUrl, arg.InstanceName, arg.Timezone)
	var i InstanceSetting
	err := row.Scan(
		&i.ID,
		&i.ControlPlaneUrl,
		&i.InstanceName,
		&i.Timezone,
		&i.DnsServers,
		&i.Ipv4Mode,
		&i.Ipv4Address,
		&i.Ipv4Gateway,
		&i.Ipv6Enabled,
		&i.Ipv6Mode,
		&i.Ipv6Address,
		&i.Ipv6Gateway,
		&i.Hostname,
		&i.NtpEnabled,
		&i.NtpServers,
		&i.PendingNetwork,
		&i.PendingDeadline,
		&i.UpdatedAt,
	)
	return i, err
}

const updateInstanceNetwork = `-- name: UpdateInstanceNetwork :one
UPDATE instance_settings
SET dns_servers = $1,
    ipv4_mode = $2, ipv4_address = $3, ipv4_gateway = $4,
    ipv6_enabled = $5, ipv6_mode = $6, ipv6_address = $7, ipv6_gateway = $8,
    pending_network = $9, pending_deadline = $10,
    updated_at = now()
WHERE id = 1
RETURNING id, control_plane_url, instance_name, timezone, dns_servers, ipv4_mode, ipv4_address, ipv4_gateway, ipv6_enabled, ipv6_mode, ipv6_address, ipv6_gateway, hostname, ntp_enabled, ntp_servers, pending_network, pending_deadline, updated_at
`

type UpdateInstanceNetworkParams struct {
	DnsServers      []string           `json:"dns_servers"`
	Ipv4Mode        string             `json:"ipv4_mode"`
	Ipv4Address     string             `json:"ipv4_address"`
	Ipv4Gateway     string             `json:"ipv4_gateway"`
	Ipv6Enabled     bool               `json:"ipv6_enabled"`
	Ipv6Mode        string             `json:"ipv6_mode"`
	Ipv6Address     string             `json:"ipv6_address"`
	Ipv6Gateway     string             `json:"ipv6_gateway"`
	PendingNetwork  []byte             `json:"pending_network"`
	PendingDeadline pgtype.Timestamptz `json:"pending_deadline"`
}

func (q *Queries) UpdateInstanceNetwork(ctx context.Context, arg UpdateInstanceNetworkParams) (InstanceSetting, error) {
	row := q.db.QueryRow(ctx, updateInstanceNetwork,
		arg.DnsServers,
		arg.Ipv4Mode,
		arg.Ipv4Address,
		arg.Ipv4Gateway,
		arg.Ipv6Enabled,
		arg.Ipv6Mode,
		arg.Ipv6Address,
		arg.Ipv6Gateway,
		arg.PendingNetwork,
		arg.PendingDeadline,
	)
	var i InstanceSetting
	err := row.Scan(
		&i.ID,
		&i.ControlPlaneUrl,
		&i.InstanceName,
		&i.Timezone,
		&i.DnsServers,
		&i.Ipv4Mode,
		&i.Ipv4Address,
		&i.Ipv4Gateway,
		&i.Ipv6Enabled,
		&i.Ipv6Mode,
		&i.Ipv6Address,
		&i.Ipv6Gateway,
		&i.Hostname,
		&i.NtpEnabled,
		&i.NtpServers,
		&i.PendingNetwork,
		&i.PendingDeadline,
		&i.UpdatedAt,
	)
	return i, err
}

const updateInstanceSystem = `-- name: UpdateInstanceSystem :one
UPDATE instance_settings
SET hostname = $1, ntp_enabled = $2, ntp_servers = $3, updated_at = now()
WHERE id = 1
RETURNING id, control_plane_url, instance_name, timezone, dns_servers, ipv4_mode, ipv4_address, ipv4_gateway, ipv6_enabled, ipv6_mode, ipv6_address, ipv6_gateway, hostname, ntp_enabled, ntp_servers, pending_network, pending_deadline, updated_at
`

type UpdateInstanceSystemParams struct {
	Hostname   string   `json:"hostname"`
	NtpEnabled bool     `json:"ntp_enabled"`
	NtpServers []string `json:"ntp_servers"`
}

func (q *Queries) UpdateInstanceSystem(ctx context.Context, arg UpdateInstanceSystemParams) (InstanceSetting, error) {
	row := q.db.QueryRow(ctx, updateInstanceSystem, arg.Hostname, arg.NtpEnabled, arg.NtpServers)
	var i InstanceSetting
	err := row.Scan(
		&i.ID,
		&i.ControlPlaneUrl,
		&i.InstanceName,
		&i.Timezone,
		&i.DnsServers,
		&i.Ipv4Mode,
		&i.Ipv4Address,
		&i.Ipv4Gateway,
		&i.Ipv6Enabled,
		&i.Ipv6Mode,
		&i.Ipv6Address,
		&i.Ipv6Gateway,
		&i.Hostname,
		&i.NtpEnabled,
		&i.NtpServers,
		&i.PendingNetwork,
		&i.PendingDeadline,
		&i.UpdatedAt,
	)
	return i, err
}
