// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: metrics.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteServerMetricsBefore = `-- name: DeleteServerMetricsBefore :execrows
DELETE FROM server_metrics WHERE recorded_at < $1
`

// Retention sweep: drops samples recorded before the cutoff. Runs on its own
// schedule, never per heartbeat.
func (q *Queries) DeleteServerMetricsBefore(ctx context.Context, recordedAt pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, deleteServerMetricsBefore, recordedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertServerMetric = `-- name: InsertServerMetric :exec

INSERT INTO server_metrics (
    server_id,
    recorded_at,
    cpu_usage,
    mem_usage,
    disk_usage,
    net_rx_bps,
    net_tx_bps,
    disk_read_bps,
    disk_write_bps,
    container_count
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
ON CONFLICT (server_id, recorded_at) DO NOTHING
`

type InsertServerMetricParams struct {
	ServerID       pgtype.UUID        `json:"server_id"`
	RecordedAt     pgtype.Timestamptz `json:"recorded_at"`
	CpuUsage       float64            `json:"cpu_usage"`
	MemUsage       float64            `json:"mem_usage"`
	DiskUsage      float64            `json:"disk_usage"`
	NetRxBps       float64            `json:"net_rx_bps"`
	NetTxBps       float64            `json:"net_tx_bps"`
	DiskReadBps    float64            `json:"disk_read_bps"`
	DiskWriteBps   float64            `json:"disk_write_bps"`
	ContainerCount int64              `json:"container_count"`
}

// Server time-series queries (Phase 8, BE-8.4).
// Appends one heartbeat sample. A duplicate (server, instant) is ignored: the
// heartbeat stream may resend after a transport hiccup, and the point already
// stored is the same observation.
func (q *Queries) InsertServerMetric(ctx context.Context, arg InsertServerMetricParams) error {
	_, err := q.db.Exec(ctx, insertServerMetric,
		arg.ServerID,
		arg.RecordedAt,
		arg.CpuUsage,
		arg.MemUsage,
		arg.DiskUsage,
		arg.NetRxBps,
		arg.NetTxBps,
		arg.DiskReadBps,
		arg.DiskWriteBps,
		arg.ContainerCount,
	)
	return err
}

const listServerMetrics = `-- name: ListServerMetrics :many
SELECT
    date_bin($2::interval, recorded_at, 'epoch'::timestamptz)::timestamptz AS bucket,
    avg(cpu_usage)::float8 AS cpu_usage,
    avg(mem_usage)::float8 AS mem_usage,
    avg(disk_usage)::float8 AS disk_usage,
    avg(net_rx_bps)::float8 AS net_rx_bps,
    avg(net_tx_bps)::float8 AS net_tx_bps,
    avg(disk_read_bps)::float8 AS disk_read_bps,
    avg(disk_write_bps)::float8 AS disk_write_bps,
    avg(container_count)::float8 AS container_count
FROM server_metrics
WHERE server_id = $1
  AND recorded_at >= $3
  AND recorded_at < $4
GROUP BY bucket
ORDER BY bucket
`

type ListServerMetricsParams struct {
	ServerID   pgtype.UUID        `json:"server_id"`
	Bucket     pgtype.Interval    `json:"bucket"`
	RangeStart pgtype.Timestamptz `json:"range_start"`
	RangeEnd   pgtype.Timestamptz `json:"range_end"`
}

type ListServerMetricsRow struct {
	Bucket         pgtype.Timestamptz `json:"bucket"`
	CpuUsage       float64            `json:"cpu_usage"`
	MemUsage       float64            `json:"mem_usage"`
	DiskUsage      float64            `json:"disk_usage"`
	NetRxBps       float64            `json:"net_rx_bps"`
	NetTxBps       float64            `json:"net_tx_bps"`
	DiskReadBps    float64            `json:"disk_read_bps"`
	DiskWriteBps   float64            `json:"disk_write_bps"`
	ContainerCount float64            `json:"container_count"`
}

// One row per non-empty aggregation bucket, ordered oldest first. Buckets
// without samples are omitted rather than returned as zero/NaN points, so the
// chart draws gaps (or connects across them) instead of inventing data.
func (q *Queries) ListServerMetrics(ctx context.Context, arg ListServerMetricsParams) ([]ListServerMetricsRow, error) {
	rows, err := q.db.Query(ctx, listServerMetrics,
		arg.ServerID,
		arg.Bucket,
		arg.RangeStart,
		arg.RangeEnd,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListServerMetricsRow{}
	for rows.Next() {
		var i ListServerMetricsRow
		if err := rows.Scan(
			&i.Bucket,
			&i.CpuUsage,
			&i.MemUsage,
			&i.DiskUsage,
			&i.NetRxBps,
			&i.NetTxBps,
			&i.DiskReadBps,
			&i.DiskWriteBps,
			&i.ContainerCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
