// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ApiToken struct {
	ID         pgtype.UUID        `json:"id"`
	UserID     pgtype.UUID        `json:"user_id"`
	Name       string             `json:"name"`
	Hash       string             `json:"hash"`
	Scopes     []string           `json:"scopes"`
	LastUsedAt pgtype.Timestamptz `json:"last_used_at"`
	RevokedAt  pgtype.Timestamptz `json:"revoked_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type PrivateKey struct {
	ID           pgtype.UUID        `json:"id"`
	Name         string             `json:"name"`
	EncryptedKey string             `json:"encrypted_key"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type Server struct {
	ID             pgtype.UUID        `json:"id"`
	Name           string             `json:"name"`
	Ip             string             `json:"ip"`
	Port           int32              `json:"port"`
	SshUser        string             `json:"ssh_user"`
	SshKeyID       pgtype.UUID        `json:"ssh_key_id"`
	Status         string             `json:"status"`
	NodeID         *string            `json:"node_id"`
	Os             *string            `json:"os"`
	DockerVersion  *string            `json:"docker_version"`
	Arch           *string            `json:"arch"`
	TotalMem       *int64             `json:"total_mem"`
	TotalDisk      *int64             `json:"total_disk"`
	CpuUsage       *float64           `json:"cpu_usage"`
	MemUsage       *float64           `json:"mem_usage"`
	DiskUsage      *float64           `json:"disk_usage"`
	ContainerCount *int64             `json:"container_count"`
	LastSeen       pgtype.Timestamptz `json:"last_seen"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type Session struct {
	ID          pgtype.UUID        `json:"id"`
	UserID      pgtype.UUID        `json:"user_id"`
	RefreshHash string             `json:"refresh_hash"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
	RevokedAt   pgtype.Timestamptz `json:"revoked_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID           pgtype.UUID        `json:"id"`
	Email        string             `json:"email"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	PasswordHash *string            `json:"password_hash"`
	Avatar       *string            `json:"avatar"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}
