// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ApiToken struct {
	ID         pgtype.UUID        `json:"id"`
	UserID     pgtype.UUID        `json:"user_id"`
	Name       string             `json:"name"`
	Hash       string             `json:"hash"`
	Scopes     []string           `json:"scopes"`
	LastUsedAt pgtype.Timestamptz `json:"last_used_at"`
	RevokedAt  pgtype.Timestamptz `json:"revoked_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type Application struct {
	ID                 pgtype.UUID        `json:"id"`
	UserID             pgtype.UUID        `json:"user_id"`
	ServerID           pgtype.UUID        `json:"server_id"`
	Name               string             `json:"name"`
	Provider           string             `json:"provider"`
	Repo               string             `json:"repo"`
	CloneUrl           string             `json:"clone_url"`
	Branch             string             `json:"branch"`
	BuildPack          string             `json:"build_pack"`
	BaseDomain         string             `json:"base_domain"`
	Port               int32              `json:"port"`
	HostPort           int32              `json:"host_port"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	BaseDomainDisabled bool               `json:"base_domain_disabled"`
}

type ApplicationDeployKey struct {
	ID            pgtype.UUID        `json:"id"`
	ApplicationID pgtype.UUID        `json:"application_id"`
	PrivateKeyID  pgtype.UUID        `json:"private_key_id"`
	Provider      string             `json:"provider"`
	Repo          string             `json:"repo"`
	ProviderKeyID string             `json:"provider_key_id"`
	Fingerprint   string             `json:"fingerprint"`
	PublicKey     string             `json:"public_key"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type ApplicationWebhook struct {
	ID            pgtype.UUID        `json:"id"`
	ApplicationID pgtype.UUID        `json:"application_id"`
	Provider      string             `json:"provider"`
	Repo          string             `json:"repo"`
	HookID        string             `json:"hook_id"`
	Secret        string             `json:"secret"`
	Url           string             `json:"url"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type Backup struct {
	ID          pgtype.UUID        `json:"id"`
	DatabaseID  pgtype.UUID        `json:"database_id"`
	ScheduleID  pgtype.UUID        `json:"schedule_id"`
	Type        string             `json:"type"`
	Status      string             `json:"status"`
	Size        int64              `json:"size"`
	Location    string             `json:"location"`
	TargetID    pgtype.UUID        `json:"target_id"`
	ContainerID string             `json:"container_id"`
	Error       string             `json:"error"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	FinishedAt  pgtype.Timestamptz `json:"finished_at"`
}

type BackupSchedule struct {
	ID         pgtype.UUID        `json:"id"`
	DatabaseID pgtype.UUID        `json:"database_id"`
	Cron       string             `json:"cron"`
	TargetID   pgtype.UUID        `json:"target_id"`
	Enabled    bool               `json:"enabled"`
	LastRunAt  pgtype.Timestamptz `json:"last_run_at"`
	NextRunAt  pgtype.Timestamptz `json:"next_run_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type BackupTarget struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	Name      string             `json:"name"`
	Kind      string             `json:"kind"`
	Endpoint  string             `json:"endpoint"`
	Region    string             `json:"region"`
	Bucket    string             `json:"bucket"`
	Prefix    string             `json:"prefix"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type BackupTargetSecret struct {
	ID         pgtype.UUID        `json:"id"`
	TargetID   pgtype.UUID        `json:"target_id"`
	Key        string             `json:"key"`
	Ciphertext string             `json:"ciphertext"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type Database struct {
	ID          pgtype.UUID        `json:"id"`
	UserID      pgtype.UUID        `json:"user_id"`
	ServerID    pgtype.UUID        `json:"server_id"`
	Name        string             `json:"name"`
	Engine      string             `json:"engine"`
	Version     string             `json:"version"`
	Status      string             `json:"status"`
	ContainerID string             `json:"container_id"`
	PublicPort  int32              `json:"public_port"`
	StoragePath string             `json:"storage_path"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	DeletedAt   pgtype.Timestamptz `json:"deleted_at"`
}

type DatabaseSecret struct {
	ID         pgtype.UUID        `json:"id"`
	DatabaseID pgtype.UUID        `json:"database_id"`
	Key        string             `json:"key"`
	Ciphertext string             `json:"ciphertext"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type Deployment struct {
	ID            pgtype.UUID        `json:"id"`
	ApplicationID pgtype.UUID        `json:"application_id"`
	Kind          string             `json:"kind"`
	State         string             `json:"state"`
	ImageTag      string             `json:"image_tag"`
	RegistryImage string             `json:"registry_image"`
	Digest        string             `json:"digest"`
	Error         string             `json:"error"`
	Attempt       int32              `json:"attempt"`
	ContainerID   string             `json:"container_id"`
	RollbackFrom  pgtype.UUID        `json:"rollback_from"`
	StartedAt     pgtype.Timestamptz `json:"started_at"`
	FinishedAt    pgtype.Timestamptz `json:"finished_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type DnsProvider struct {
	ID         pgtype.UUID        `json:"id"`
	Provider   string             `json:"provider"`
	Name       string             `json:"name"`
	Zones      []string           `json:"zones"`
	Ciphertext string             `json:"ciphertext"`
	Enabled    bool               `json:"enabled"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type DomainCertificate struct {
	ID            pgtype.UUID        `json:"id"`
	ApplicationID pgtype.UUID        `json:"application_id"`
	Domain        string             `json:"domain"`
	Enabled       bool               `json:"enabled"`
	Challenge     string             `json:"challenge"`
	DnsProviderID pgtype.UUID        `json:"dns_provider_id"`
	Wildcard      bool               `json:"wildcard"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type DomainRedirect struct {
	ID            pgtype.UUID        `json:"id"`
	ApplicationID pgtype.UUID        `json:"application_id"`
	SourceDomain  string             `json:"source_domain"`
	TargetDomain  string             `json:"target_domain"`
	Code          int16              `json:"code"`
	PreservePath  bool               `json:"preserve_path"`
	Enabled       bool               `json:"enabled"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type EnvVar struct {
	ID            pgtype.UUID        `json:"id"`
	ApplicationID pgtype.UUID        `json:"application_id"`
	Key           string             `json:"key"`
	Value         string             `json:"value"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type PrivateKey struct {
	ID           pgtype.UUID        `json:"id"`
	Name         string             `json:"name"`
	EncryptedKey string             `json:"encrypted_key"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type Provider struct {
	ID             pgtype.UUID        `json:"id"`
	UserID         pgtype.UUID        `json:"user_id"`
	Name           string             `json:"name"`
	BaseUrl        string             `json:"base_url"`
	ClientID       string             `json:"client_id"`
	ClientSecret   string             `json:"client_secret"`
	RedirectUrl    string             `json:"redirect_url"`
	AccessToken    string             `json:"access_token"`
	RefreshToken   string             `json:"refresh_token"`
	TokenExpiresAt pgtype.Timestamptz `json:"token_expires_at"`
	Scopes         string             `json:"scopes"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type ProxyConfigVersion struct {
	ID           pgtype.UUID        `json:"id"`
	ServerID     pgtype.UUID        `json:"server_id"`
	Files        []byte             `json:"files"`
	ContentHash  string             `json:"content_hash"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	Pending      bool               `json:"pending"`
	SupersededAt pgtype.Timestamptz `json:"superseded_at"`
}

type ReposCache struct {
	ID            pgtype.UUID        `json:"id"`
	ProviderID    pgtype.UUID        `json:"provider_id"`
	ExternalID    string             `json:"external_id"`
	Name          string             `json:"name"`
	FullName      string             `json:"full_name"`
	Private       bool               `json:"private"`
	DefaultBranch string             `json:"default_branch"`
	CloneUrl      string             `json:"clone_url"`
	SshUrl        string             `json:"ssh_url"`
	HtmlUrl       string             `json:"html_url"`
	CachedAt      pgtype.Timestamptz `json:"cached_at"`
}

type Secret struct {
	ID            pgtype.UUID        `json:"id"`
	ApplicationID pgtype.UUID        `json:"application_id"`
	Key           string             `json:"key"`
	Ciphertext    string             `json:"ciphertext"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type Server struct {
	ID             pgtype.UUID        `json:"id"`
	Name           string             `json:"name"`
	Ip             string             `json:"ip"`
	Port           int32              `json:"port"`
	SshUser        string             `json:"ssh_user"`
	SshKeyID       pgtype.UUID        `json:"ssh_key_id"`
	Status         string             `json:"status"`
	NodeID         *string            `json:"node_id"`
	Os             *string            `json:"os"`
	DockerVersion  *string            `json:"docker_version"`
	Arch           *string            `json:"arch"`
	TotalMem       *int64             `json:"total_mem"`
	TotalDisk      *int64             `json:"total_disk"`
	CpuUsage       *float64           `json:"cpu_usage"`
	MemUsage       *float64           `json:"mem_usage"`
	DiskUsage      *float64           `json:"disk_usage"`
	ContainerCount *int64             `json:"container_count"`
	LastSeen       pgtype.Timestamptz `json:"last_seen"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type Service struct {
	ID          pgtype.UUID        `json:"id"`
	UserID      pgtype.UUID        `json:"user_id"`
	ServerID    pgtype.UUID        `json:"server_id"`
	Name        string             `json:"name"`
	Status      string             `json:"status"`
	ComposeYaml string             `json:"compose_yaml"`
	Env         []byte             `json:"env"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	DeletedAt   pgtype.Timestamptz `json:"deleted_at"`
}

type ServiceDeploy struct {
	ID          pgtype.UUID        `json:"id"`
	ServiceID   pgtype.UUID        `json:"service_id"`
	State       string             `json:"state"`
	ComposeYaml string             `json:"compose_yaml"`
	Error       string             `json:"error"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	FinishedAt  pgtype.Timestamptz `json:"finished_at"`
}

type Session struct {
	ID          pgtype.UUID        `json:"id"`
	UserID      pgtype.UUID        `json:"user_id"`
	RefreshHash string             `json:"refresh_hash"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
	RevokedAt   pgtype.Timestamptz `json:"revoked_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Storage struct {
	ID            pgtype.UUID        `json:"id"`
	ApplicationID pgtype.UUID        `json:"application_id"`
	Name          string             `json:"name"`
	HostPath      string             `json:"host_path"`
	ContainerPath string             `json:"container_path"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID           pgtype.UUID        `json:"id"`
	Email        string             `json:"email"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	PasswordHash *string            `json:"password_hash"`
	Avatar       *string            `json:"avatar"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type WebhookEvent struct {
	ID            pgtype.UUID        `json:"id"`
	ApplicationID pgtype.UUID        `json:"application_id"`
	Provider      string             `json:"provider"`
	Event         string             `json:"event"`
	DeliveryID    string             `json:"delivery_id"`
	Ref           string             `json:"ref"`
	CommitSha     string             `json:"commit_sha"`
	DeploymentID  pgtype.UUID        `json:"deployment_id"`
	ReceivedAt    pgtype.Timestamptz `json:"received_at"`
}
