// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notifications.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createNotificationChannel = `-- name: CreateNotificationChannel :one
INSERT INTO notification_channels (
    id, team_id, name, kind, config, enabled, resource_type, resource_id, events
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, team_id, name, kind, config, enabled, resource_type, resource_id, events, created_at, updated_at
`

type CreateNotificationChannelParams struct {
	ID           pgtype.UUID `json:"id"`
	TeamID       pgtype.UUID `json:"team_id"`
	Name         string      `json:"name"`
	Kind         string      `json:"kind"`
	Config       string      `json:"config"`
	Enabled      bool        `json:"enabled"`
	ResourceType *string     `json:"resource_type"`
	ResourceID   pgtype.UUID `json:"resource_id"`
	Events       []string    `json:"events"`
}

func (q *Queries) CreateNotificationChannel(ctx context.Context, arg CreateNotificationChannelParams) (NotificationChannel, error) {
	row := q.db.QueryRow(ctx, createNotificationChannel,
		arg.ID,
		arg.TeamID,
		arg.Name,
		arg.Kind,
		arg.Config,
		arg.Enabled,
		arg.ResourceType,
		arg.ResourceID,
		arg.Events,
	)
	var i NotificationChannel
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Name,
		&i.Kind,
		&i.Config,
		&i.Enabled,
		&i.ResourceType,
		&i.ResourceID,
		&i.Events,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteNotificationChannel = `-- name: DeleteNotificationChannel :execrows
DELETE FROM notification_channels WHERE id = $1 AND team_id = $2
`

type DeleteNotificationChannelParams struct {
	ID     pgtype.UUID `json:"id"`
	TeamID pgtype.UUID `json:"team_id"`
}

func (q *Queries) DeleteNotificationChannel(ctx context.Context, arg DeleteNotificationChannelParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteNotificationChannel, arg.ID, arg.TeamID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getNotificationChannel = `-- name: GetNotificationChannel :one
SELECT id, team_id, name, kind, config, enabled, resource_type, resource_id, events, created_at, updated_at FROM notification_channels WHERE id = $1 AND team_id = $2
`

type GetNotificationChannelParams struct {
	ID     pgtype.UUID `json:"id"`
	TeamID pgtype.UUID `json:"team_id"`
}

// The team filter is what makes a foreign channel ID indistinguishable from a
// missing one (404).
func (q *Queries) GetNotificationChannel(ctx context.Context, arg GetNotificationChannelParams) (NotificationChannel, error) {
	row := q.db.QueryRow(ctx, getNotificationChannel, arg.ID, arg.TeamID)
	var i NotificationChannel
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Name,
		&i.Kind,
		&i.Config,
		&i.Enabled,
		&i.ResourceType,
		&i.ResourceID,
		&i.Events,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listNotificationChannels = `-- name: ListNotificationChannels :many
SELECT id, team_id, name, kind, config, enabled, resource_type, resource_id, events, created_at, updated_at FROM notification_channels
WHERE team_id = $1
ORDER BY created_at ASC, id ASC
`

func (q *Queries) ListNotificationChannels(ctx context.Context, teamID pgtype.UUID) ([]NotificationChannel, error) {
	rows, err := q.db.Query(ctx, listNotificationChannels, teamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NotificationChannel{}
	for rows.Next() {
		var i NotificationChannel
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.Name,
			&i.Kind,
			&i.Config,
			&i.Enabled,
			&i.ResourceType,
			&i.ResourceID,
			&i.Events,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotificationChannelsForEvent = `-- name: ListNotificationChannelsForEvent :many
SELECT id, team_id, name, kind, config, enabled, resource_type, resource_id, events, created_at, updated_at FROM notification_channels
WHERE team_id = $1
  AND enabled
  AND (resource_type IS NULL OR (resource_type = $2 AND resource_id = $3))
ORDER BY created_at ASC, id ASC
`

type ListNotificationChannelsForEventParams struct {
	TeamID       pgtype.UUID `json:"team_id"`
	ResourceType *string     `json:"resource_type"`
	ResourceID   pgtype.UUID `json:"resource_id"`
}

// The dispatcher read: enabled channels of the event's team that cover the
// event's resource — team-wide rows (resource_type IS NULL) plus the overrides
// scoped to that exact resource. Event-list filtering stays in Go.
func (q *Queries) ListNotificationChannelsForEvent(ctx context.Context, arg ListNotificationChannelsForEventParams) ([]NotificationChannel, error) {
	rows, err := q.db.Query(ctx, listNotificationChannelsForEvent, arg.TeamID, arg.ResourceType, arg.ResourceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NotificationChannel{}
	for rows.Next() {
		var i NotificationChannel
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.Name,
			&i.Kind,
			&i.Config,
			&i.Enabled,
			&i.ResourceType,
			&i.ResourceID,
			&i.Events,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateNotificationChannel = `-- name: UpdateNotificationChannel :one
UPDATE notification_channels
SET name = $3,
    kind = $4,
    config = $5,
    enabled = $6,
    resource_type = $7,
    resource_id = $8,
    events = $9,
    updated_at = now()
WHERE id = $1 AND team_id = $2
RETURNING id, team_id, name, kind, config, enabled, resource_type, resource_id, events, created_at, updated_at
`

type UpdateNotificationChannelParams struct {
	ID           pgtype.UUID `json:"id"`
	TeamID       pgtype.UUID `json:"team_id"`
	Name         string      `json:"name"`
	Kind         string      `json:"kind"`
	Config       string      `json:"config"`
	Enabled      bool        `json:"enabled"`
	ResourceType *string     `json:"resource_type"`
	ResourceID   pgtype.UUID `json:"resource_id"`
	Events       []string    `json:"events"`
}

func (q *Queries) UpdateNotificationChannel(ctx context.Context, arg UpdateNotificationChannelParams) (NotificationChannel, error) {
	row := q.db.QueryRow(ctx, updateNotificationChannel,
		arg.ID,
		arg.TeamID,
		arg.Name,
		arg.Kind,
		arg.Config,
		arg.Enabled,
		arg.ResourceType,
		arg.ResourceID,
		arg.Events,
	)
	var i NotificationChannel
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Name,
		&i.Kind,
		&i.Config,
		&i.Enabled,
		&i.ResourceType,
		&i.ResourceID,
		&i.Events,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
