// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: private_keys.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPrivateKey = `-- name: CreatePrivateKey :one
INSERT INTO private_keys (name, encrypted_key, team_id)
VALUES ($1, $2, $3)
RETURNING id, name, created_at
`

type CreatePrivateKeyParams struct {
	Name         string      `json:"name"`
	EncryptedKey string      `json:"encrypted_key"`
	TeamID       pgtype.UUID `json:"team_id"`
}

type CreatePrivateKeyRow struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreatePrivateKey(ctx context.Context, arg CreatePrivateKeyParams) (CreatePrivateKeyRow, error) {
	row := q.db.QueryRow(ctx, createPrivateKey, arg.Name, arg.EncryptedKey, arg.TeamID)
	var i CreatePrivateKeyRow
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const deletePrivateKey = `-- name: DeletePrivateKey :exec
DELETE FROM private_keys WHERE id = $1
`

func (q *Queries) DeletePrivateKey(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deletePrivateKey, id)
	return err
}

const getPrivateKeyByID = `-- name: GetPrivateKeyByID :one
SELECT id, name, encrypted_key, created_at, team_id FROM private_keys WHERE id = $1
`

func (q *Queries) GetPrivateKeyByID(ctx context.Context, id pgtype.UUID) (PrivateKey, error) {
	row := q.db.QueryRow(ctx, getPrivateKeyByID, id)
	var i PrivateKey
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.EncryptedKey,
		&i.CreatedAt,
		&i.TeamID,
	)
	return i, err
}

const listPrivateKeys = `-- name: ListPrivateKeys :many
SELECT id, name, created_at
FROM private_keys
ORDER BY created_at DESC, id DESC
`

type ListPrivateKeysRow struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListPrivateKeys(ctx context.Context) ([]ListPrivateKeysRow, error) {
	rows, err := q.db.Query(ctx, listPrivateKeys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPrivateKeysRow{}
	for rows.Next() {
		var i ListPrivateKeysRow
		if err := rows.Scan(&i.ID, &i.Name, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
