// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: projects.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countEnvironmentsByProject = `-- name: CountEnvironmentsByProject :one
SELECT count(*) FROM environments WHERE project_id = $1
`

func (q *Queries) CountEnvironmentsByProject(ctx context.Context, projectID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countEnvironmentsByProject, projectID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createEnvironment = `-- name: CreateEnvironment :one
INSERT INTO environments (id, project_id, name)
VALUES ($1, $2, $3)
RETURNING id, project_id, name, created_at, updated_at
`

type CreateEnvironmentParams struct {
	ID        pgtype.UUID `json:"id"`
	ProjectID pgtype.UUID `json:"project_id"`
	Name      string      `json:"name"`
}

func (q *Queries) CreateEnvironment(ctx context.Context, arg CreateEnvironmentParams) (Environment, error) {
	row := q.db.QueryRow(ctx, createEnvironment, arg.ID, arg.ProjectID, arg.Name)
	var i Environment
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createProject = `-- name: CreateProject :one
INSERT INTO projects (id, team_id, name, description)
VALUES ($1, $2, $3, $4)
RETURNING id, team_id, name, description, created_at, updated_at
`

type CreateProjectParams struct {
	ID          pgtype.UUID `json:"id"`
	TeamID      pgtype.UUID `json:"team_id"`
	Name        string      `json:"name"`
	Description string      `json:"description"`
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, createProject,
		arg.ID,
		arg.TeamID,
		arg.Name,
		arg.Description,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteEnvironment = `-- name: DeleteEnvironment :execrows
DELETE FROM environments e
USING projects p
WHERE e.id = $1 AND e.project_id = p.id AND p.team_id = $2
`

type DeleteEnvironmentParams struct {
	ID     pgtype.UUID `json:"id"`
	TeamID pgtype.UUID `json:"team_id"`
}

func (q *Queries) DeleteEnvironment(ctx context.Context, arg DeleteEnvironmentParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteEnvironment, arg.ID, arg.TeamID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteProject = `-- name: DeleteProject :execrows
DELETE FROM projects WHERE id = $1 AND team_id = $2
`

type DeleteProjectParams struct {
	ID     pgtype.UUID `json:"id"`
	TeamID pgtype.UUID `json:"team_id"`
}

func (q *Queries) DeleteProject(ctx context.Context, arg DeleteProjectParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteProject, arg.ID, arg.TeamID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteSharedVariables = `-- name: DeleteSharedVariables :exec
DELETE FROM shared_variables
WHERE project_id = $1 AND environment_id IS NOT DISTINCT FROM $2
`

type DeleteSharedVariablesParams struct {
	ProjectID     pgtype.UUID `json:"project_id"`
	EnvironmentID pgtype.UUID `json:"environment_id"`
}

// DeleteSharedVariables clears one scope's whole set; the replace path
// re-inserts the new set in the same transaction.
func (q *Queries) DeleteSharedVariables(ctx context.Context, arg DeleteSharedVariablesParams) error {
	_, err := q.db.Exec(ctx, deleteSharedVariables, arg.ProjectID, arg.EnvironmentID)
	return err
}

const getEnvironment = `-- name: GetEnvironment :one
SELECT e.id, e.project_id, e.name, e.created_at, e.updated_at
FROM environments e
JOIN projects p ON p.id = e.project_id
WHERE e.id = $1 AND p.team_id = $2
`

type GetEnvironmentParams struct {
	ID     pgtype.UUID `json:"id"`
	TeamID pgtype.UUID `json:"team_id"`
}

// GetEnvironment returns one environment of a team, joining the parent
// project so a foreign environment ID is indistinguishable from a missing one
// (404). PE-2 uses the same read for the environment resources surface.
func (q *Queries) GetEnvironment(ctx context.Context, arg GetEnvironmentParams) (Environment, error) {
	row := q.db.QueryRow(ctx, getEnvironment, arg.ID, arg.TeamID)
	var i Environment
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProject = `-- name: GetProject :one
SELECT id, team_id, name, description, created_at, updated_at FROM projects WHERE id = $1 AND team_id = $2
`

type GetProjectParams struct {
	ID     pgtype.UUID `json:"id"`
	TeamID pgtype.UUID `json:"team_id"`
}

// The team filter is what makes a foreign project ID indistinguishable from a
// missing one (404).
func (q *Queries) GetProject(ctx context.Context, arg GetProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, getProject, arg.ID, arg.TeamID)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProjectForUpdate = `-- name: GetProjectForUpdate :one
SELECT id, team_id, name, description, created_at, updated_at FROM projects WHERE id = $1 FOR UPDATE
`

// GetProjectForUpdate locks the project row for the duration of a guarded
// environment delete, so two concurrent deletes of one project's last two
// environments serialize and the survivor check cannot race.
func (q *Queries) GetProjectForUpdate(ctx context.Context, id pgtype.UUID) (Project, error) {
	row := q.db.QueryRow(ctx, getProjectForUpdate, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertSharedVariable = `-- name: InsertSharedVariable :one
INSERT INTO shared_variables (id, project_id, environment_id, key, value, ciphertext, secret)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, project_id, environment_id, key, value, ciphertext, secret, created_at, updated_at
`

type InsertSharedVariableParams struct {
	ID            pgtype.UUID `json:"id"`
	ProjectID     pgtype.UUID `json:"project_id"`
	EnvironmentID pgtype.UUID `json:"environment_id"`
	Key           string      `json:"key"`
	Value         string      `json:"value"`
	Ciphertext    string      `json:"ciphertext"`
	Secret        bool        `json:"secret"`
}

func (q *Queries) InsertSharedVariable(ctx context.Context, arg InsertSharedVariableParams) (SharedVariable, error) {
	row := q.db.QueryRow(ctx, insertSharedVariable,
		arg.ID,
		arg.ProjectID,
		arg.EnvironmentID,
		arg.Key,
		arg.Value,
		arg.Ciphertext,
		arg.Secret,
	)
	var i SharedVariable
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.EnvironmentID,
		&i.Key,
		&i.Value,
		&i.Ciphertext,
		&i.Secret,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listEnvironmentsByProject = `-- name: ListEnvironmentsByProject :many
SELECT id, project_id, name, created_at, updated_at FROM environments
WHERE project_id = $1
ORDER BY created_at ASC, id ASC
`

func (q *Queries) ListEnvironmentsByProject(ctx context.Context, projectID pgtype.UUID) ([]Environment, error) {
	rows, err := q.db.Query(ctx, listEnvironmentsByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Environment{}
	for rows.Next() {
		var i Environment
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPreviewBases = `-- name: ListPreviewBases :many
SELECT application_id, preview_application_id
FROM preview_deploys
WHERE preview_application_id = ANY($1)
  AND team_id = $2
  AND deleted_at IS NULL
`

type ListPreviewBasesParams struct {
	PreviewAppIds []pgtype.UUID `json:"preview_app_ids"`
	TeamID        pgtype.UUID   `json:"team_id"`
}

type ListPreviewBasesRow struct {
	ApplicationID        pgtype.UUID `json:"application_id"`
	PreviewApplicationID pgtype.UUID `json:"preview_application_id"`
}

// ListPreviewBases maps preview application rows to their base application
// for the environment resources surface (PE-5 M1): the preview marker rides
// the applications row itself, but the base id lives in preview_deploys.
// Team-scoped, so a foreign preview id simply resolves to no row.
func (q *Queries) ListPreviewBases(ctx context.Context, arg ListPreviewBasesParams) ([]ListPreviewBasesRow, error) {
	rows, err := q.db.Query(ctx, listPreviewBases, arg.PreviewAppIds, arg.TeamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPreviewBasesRow{}
	for rows.Next() {
		var i ListPreviewBasesRow
		if err := rows.Scan(&i.ApplicationID, &i.PreviewApplicationID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectsByTeam = `-- name: ListProjectsByTeam :many
SELECT id, team_id, name, description, created_at, updated_at FROM projects
WHERE team_id = $1
ORDER BY created_at DESC, id DESC
`

func (q *Queries) ListProjectsByTeam(ctx context.Context, teamID pgtype.UUID) ([]Project, error) {
	rows, err := q.db.Query(ctx, listProjectsByTeam, teamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Project{}
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSharedVariables = `-- name: ListSharedVariables :many
SELECT id, project_id, environment_id, key, value, ciphertext, secret, created_at, updated_at FROM shared_variables
WHERE project_id = $1 AND environment_id IS NOT DISTINCT FROM $2
ORDER BY key ASC
`

type ListSharedVariablesParams struct {
	ProjectID     pgtype.UUID `json:"project_id"`
	EnvironmentID pgtype.UUID `json:"environment_id"`
}

// ListSharedVariables returns one scope's variables (environment_id NULL for
// the project level), ordered by key. A NULL parameter matches the project
// level through IS NOT DISTINCT FROM.
func (q *Queries) ListSharedVariables(ctx context.Context, arg ListSharedVariablesParams) ([]SharedVariable, error) {
	rows, err := q.db.Query(ctx, listSharedVariables, arg.ProjectID, arg.EnvironmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SharedVariable{}
	for rows.Next() {
		var i SharedVariable
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.EnvironmentID,
			&i.Key,
			&i.Value,
			&i.Ciphertext,
			&i.Secret,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSharedVariablesForEnvironment = `-- name: ListSharedVariablesForEnvironment :many
SELECT id, project_id, environment_id, key, value, ciphertext, secret, created_at, updated_at FROM shared_variables
WHERE project_id = $1 AND (environment_id IS NULL OR environment_id = $2)
ORDER BY key ASC
`

type ListSharedVariablesForEnvironmentParams struct {
	ProjectID     pgtype.UUID `json:"project_id"`
	EnvironmentID pgtype.UUID `json:"environment_id"`
}

// ListSharedVariablesForEnvironment returns the project-level rows plus one
// environment's rows in a single snapshot, so the deploy merge reads both
// scopes without a concurrent replace slipping between two reads.
func (q *Queries) ListSharedVariablesForEnvironment(ctx context.Context, arg ListSharedVariablesForEnvironmentParams) ([]SharedVariable, error) {
	rows, err := q.db.Query(ctx, listSharedVariablesForEnvironment, arg.ProjectID, arg.EnvironmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SharedVariable{}
	for rows.Next() {
		var i SharedVariable
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.EnvironmentID,
			&i.Key,
			&i.Value,
			&i.Ciphertext,
			&i.Secret,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEnvironment = `-- name: UpdateEnvironment :one
UPDATE environments e
SET name = $2,
    updated_at = now()
FROM projects p
WHERE e.id = $1 AND e.project_id = p.id AND p.team_id = $3
RETURNING e.id, e.project_id, e.name, e.created_at, e.updated_at
`

type UpdateEnvironmentParams struct {
	ID     pgtype.UUID `json:"id"`
	Name   string      `json:"name"`
	TeamID pgtype.UUID `json:"team_id"`
}

func (q *Queries) UpdateEnvironment(ctx context.Context, arg UpdateEnvironmentParams) (Environment, error) {
	row := q.db.QueryRow(ctx, updateEnvironment, arg.ID, arg.Name, arg.TeamID)
	var i Environment
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateProject = `-- name: UpdateProject :one
UPDATE projects
SET name = $3,
    description = $4,
    updated_at = now()
WHERE id = $1 AND team_id = $2
RETURNING id, team_id, name, description, created_at, updated_at
`

type UpdateProjectParams struct {
	ID          pgtype.UUID `json:"id"`
	TeamID      pgtype.UUID `json:"team_id"`
	Name        string      `json:"name"`
	Description string      `json:"description"`
}

func (q *Queries) UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, updateProject,
		arg.ID,
		arg.TeamID,
		arg.Name,
		arg.Description,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
