// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: providers.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createProvider = `-- name: CreateProvider :one
INSERT INTO providers (
    user_id, name, base_url, client_id, client_secret, redirect_url,
    access_token, refresh_token, token_expires_at, scopes
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, user_id, name, base_url, client_id, client_secret, redirect_url, access_token, refresh_token, token_expires_at, scopes, created_at, updated_at
`

type CreateProviderParams struct {
	UserID         pgtype.UUID        `json:"user_id"`
	Name           string             `json:"name"`
	BaseUrl        string             `json:"base_url"`
	ClientID       string             `json:"client_id"`
	ClientSecret   string             `json:"client_secret"`
	RedirectUrl    string             `json:"redirect_url"`
	AccessToken    string             `json:"access_token"`
	RefreshToken   string             `json:"refresh_token"`
	TokenExpiresAt pgtype.Timestamptz `json:"token_expires_at"`
	Scopes         string             `json:"scopes"`
}

func (q *Queries) CreateProvider(ctx context.Context, arg CreateProviderParams) (Provider, error) {
	row := q.db.QueryRow(ctx, createProvider,
		arg.UserID,
		arg.Name,
		arg.BaseUrl,
		arg.ClientID,
		arg.ClientSecret,
		arg.RedirectUrl,
		arg.AccessToken,
		arg.RefreshToken,
		arg.TokenExpiresAt,
		arg.Scopes,
	)
	var i Provider
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.BaseUrl,
		&i.ClientID,
		&i.ClientSecret,
		&i.RedirectUrl,
		&i.AccessToken,
		&i.RefreshToken,
		&i.TokenExpiresAt,
		&i.Scopes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteProviderByIDAndUser = `-- name: DeleteProviderByIDAndUser :exec
DELETE FROM providers WHERE id = $1 AND user_id = $2
`

type DeleteProviderByIDAndUserParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) DeleteProviderByIDAndUser(ctx context.Context, arg DeleteProviderByIDAndUserParams) error {
	_, err := q.db.Exec(ctx, deleteProviderByIDAndUser, arg.ID, arg.UserID)
	return err
}

const deleteRepoCacheByProvider = `-- name: DeleteRepoCacheByProvider :exec
DELETE FROM repos_cache WHERE provider_id = $1
`

func (q *Queries) DeleteRepoCacheByProvider(ctx context.Context, providerID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteRepoCacheByProvider, providerID)
	return err
}

const getProviderByIDAndUser = `-- name: GetProviderByIDAndUser :one
SELECT id, user_id, name, base_url, client_id, client_secret, redirect_url, access_token, refresh_token, token_expires_at, scopes, created_at, updated_at FROM providers WHERE id = $1 AND user_id = $2
`

type GetProviderByIDAndUserParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) GetProviderByIDAndUser(ctx context.Context, arg GetProviderByIDAndUserParams) (Provider, error) {
	row := q.db.QueryRow(ctx, getProviderByIDAndUser, arg.ID, arg.UserID)
	var i Provider
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.BaseUrl,
		&i.ClientID,
		&i.ClientSecret,
		&i.RedirectUrl,
		&i.AccessToken,
		&i.RefreshToken,
		&i.TokenExpiresAt,
		&i.Scopes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listProvidersByUser = `-- name: ListProvidersByUser :many
SELECT id, user_id, name, base_url, client_id, client_secret, redirect_url, access_token, refresh_token, token_expires_at, scopes, created_at, updated_at FROM providers
WHERE user_id = $1
ORDER BY created_at DESC, id DESC
`

func (q *Queries) ListProvidersByUser(ctx context.Context, userID pgtype.UUID) ([]Provider, error) {
	rows, err := q.db.Query(ctx, listProvidersByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Provider{}
	for rows.Next() {
		var i Provider
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.BaseUrl,
			&i.ClientID,
			&i.ClientSecret,
			&i.RedirectUrl,
			&i.AccessToken,
			&i.RefreshToken,
			&i.TokenExpiresAt,
			&i.Scopes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRepoCacheByProvider = `-- name: ListRepoCacheByProvider :many
SELECT id, provider_id, external_id, name, full_name, private, default_branch, clone_url, ssh_url, html_url, cached_at FROM repos_cache
WHERE provider_id = $1
ORDER BY full_name ASC
`

func (q *Queries) ListRepoCacheByProvider(ctx context.Context, providerID pgtype.UUID) ([]ReposCache, error) {
	rows, err := q.db.Query(ctx, listRepoCacheByProvider, providerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReposCache{}
	for rows.Next() {
		var i ReposCache
		if err := rows.Scan(
			&i.ID,
			&i.ProviderID,
			&i.ExternalID,
			&i.Name,
			&i.FullName,
			&i.Private,
			&i.DefaultBranch,
			&i.CloneUrl,
			&i.SshUrl,
			&i.HtmlUrl,
			&i.CachedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProviderToken = `-- name: UpdateProviderToken :one
UPDATE providers
SET access_token = $2,
    refresh_token = $3,
    token_expires_at = $4,
    updated_at = now()
WHERE id = $1
RETURNING id, user_id, name, base_url, client_id, client_secret, redirect_url, access_token, refresh_token, token_expires_at, scopes, created_at, updated_at
`

type UpdateProviderTokenParams struct {
	ID             pgtype.UUID        `json:"id"`
	AccessToken    string             `json:"access_token"`
	RefreshToken   string             `json:"refresh_token"`
	TokenExpiresAt pgtype.Timestamptz `json:"token_expires_at"`
}

func (q *Queries) UpdateProviderToken(ctx context.Context, arg UpdateProviderTokenParams) (Provider, error) {
	row := q.db.QueryRow(ctx, updateProviderToken,
		arg.ID,
		arg.AccessToken,
		arg.RefreshToken,
		arg.TokenExpiresAt,
	)
	var i Provider
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.BaseUrl,
		&i.ClientID,
		&i.ClientSecret,
		&i.RedirectUrl,
		&i.AccessToken,
		&i.RefreshToken,
		&i.TokenExpiresAt,
		&i.Scopes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertRepoCache = `-- name: UpsertRepoCache :one
INSERT INTO repos_cache (
    provider_id, external_id, name, full_name, private,
    default_branch, clone_url, ssh_url, html_url, cached_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, now())
ON CONFLICT (provider_id, external_id) DO UPDATE
SET name = EXCLUDED.name,
    full_name = EXCLUDED.full_name,
    private = EXCLUDED.private,
    default_branch = EXCLUDED.default_branch,
    clone_url = EXCLUDED.clone_url,
    ssh_url = EXCLUDED.ssh_url,
    html_url = EXCLUDED.html_url,
    cached_at = now()
RETURNING id, provider_id, external_id, name, full_name, private, default_branch, clone_url, ssh_url, html_url, cached_at
`

type UpsertRepoCacheParams struct {
	ProviderID    pgtype.UUID `json:"provider_id"`
	ExternalID    string      `json:"external_id"`
	Name          string      `json:"name"`
	FullName      string      `json:"full_name"`
	Private       bool        `json:"private"`
	DefaultBranch string      `json:"default_branch"`
	CloneUrl      string      `json:"clone_url"`
	SshUrl        string      `json:"ssh_url"`
	HtmlUrl       string      `json:"html_url"`
}

func (q *Queries) UpsertRepoCache(ctx context.Context, arg UpsertRepoCacheParams) (ReposCache, error) {
	row := q.db.QueryRow(ctx, upsertRepoCache,
		arg.ProviderID,
		arg.ExternalID,
		arg.Name,
		arg.FullName,
		arg.Private,
		arg.DefaultBranch,
		arg.CloneUrl,
		arg.SshUrl,
		arg.HtmlUrl,
	)
	var i ReposCache
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.ExternalID,
		&i.Name,
		&i.FullName,
		&i.Private,
		&i.DefaultBranch,
		&i.CloneUrl,
		&i.SshUrl,
		&i.HtmlUrl,
		&i.CachedAt,
	)
	return i, err
}
