// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: proxy.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const clearPendingProxyConfigVersions = `-- name: ClearPendingProxyConfigVersions :exec
DELETE FROM proxy_config_versions WHERE server_id = $1 AND pending
`

// ClearPendingProxyConfigVersions drops stale pending rows (a newer intent
// replaces an older un-promoted one).
func (q *Queries) ClearPendingProxyConfigVersions(ctx context.Context, serverID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, clearPendingProxyConfigVersions, serverID)
	return err
}

const countDomainCertificatesByProvider = `-- name: CountDomainCertificatesByProvider :one
SELECT count(*) FROM domain_certificates
WHERE dns_provider_id = $1
`

// CountDomainCertificatesByProvider guards provider deletion, which the
// foreign key would otherwise reject after the fact.
func (q *Queries) CountDomainCertificatesByProvider(ctx context.Context, dnsProviderID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countDomainCertificatesByProvider, dnsProviderID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countEnabledDomainCertificatesByProvider = `-- name: CountEnabledDomainCertificatesByProvider :one
SELECT count(*) FROM domain_certificates
WHERE dns_provider_id = $1 AND enabled
`

// CountEnabledDomainCertificatesByProvider guards provider disable/delete/type
// changes: an enabled certificate config must never lose its provider
// silently.
func (q *Queries) CountEnabledDomainCertificatesByProvider(ctx context.Context, dnsProviderID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countEnabledDomainCertificatesByProvider, dnsProviderID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createDNSProvider = `-- name: CreateDNSProvider :one
INSERT INTO dns_providers (provider, name, zones, ciphertext, enabled)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, provider, name, zones, ciphertext, enabled, created_at, updated_at
`

type CreateDNSProviderParams struct {
	Provider   string   `json:"provider"`
	Name       string   `json:"name"`
	Zones      []string `json:"zones"`
	Ciphertext string   `json:"ciphertext"`
	Enabled    bool     `json:"enabled"`
}

func (q *Queries) CreateDNSProvider(ctx context.Context, arg CreateDNSProviderParams) (DnsProvider, error) {
	row := q.db.QueryRow(ctx, createDNSProvider,
		arg.Provider,
		arg.Name,
		arg.Zones,
		arg.Ciphertext,
		arg.Enabled,
	)
	var i DnsProvider
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.Name,
		&i.Zones,
		&i.Ciphertext,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createDomainCertificate = `-- name: CreateDomainCertificate :one
INSERT INTO domain_certificates (application_id, domain, enabled, challenge, dns_provider_id, wildcard)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, application_id, domain, enabled, challenge, dns_provider_id, wildcard, created_at, updated_at
`

type CreateDomainCertificateParams struct {
	ApplicationID pgtype.UUID `json:"application_id"`
	Domain        string      `json:"domain"`
	Enabled       bool        `json:"enabled"`
	Challenge     string      `json:"challenge"`
	DnsProviderID pgtype.UUID `json:"dns_provider_id"`
	Wildcard      bool        `json:"wildcard"`
}

func (q *Queries) CreateDomainCertificate(ctx context.Context, arg CreateDomainCertificateParams) (DomainCertificate, error) {
	row := q.db.QueryRow(ctx, createDomainCertificate,
		arg.ApplicationID,
		arg.Domain,
		arg.Enabled,
		arg.Challenge,
		arg.DnsProviderID,
		arg.Wildcard,
	)
	var i DomainCertificate
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.Domain,
		&i.Enabled,
		&i.Challenge,
		&i.DnsProviderID,
		&i.Wildcard,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createDomainRedirect = `-- name: CreateDomainRedirect :one
INSERT INTO domain_redirects (application_id, source_domain, target_domain, code, preserve_path, enabled)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, application_id, source_domain, target_domain, code, preserve_path, enabled, created_at, updated_at
`

type CreateDomainRedirectParams struct {
	ApplicationID pgtype.UUID `json:"application_id"`
	SourceDomain  string      `json:"source_domain"`
	TargetDomain  string      `json:"target_domain"`
	Code          int16       `json:"code"`
	PreservePath  bool        `json:"preserve_path"`
	Enabled       bool        `json:"enabled"`
}

func (q *Queries) CreateDomainRedirect(ctx context.Context, arg CreateDomainRedirectParams) (DomainRedirect, error) {
	row := q.db.QueryRow(ctx, createDomainRedirect,
		arg.ApplicationID,
		arg.SourceDomain,
		arg.TargetDomain,
		arg.Code,
		arg.PreservePath,
		arg.Enabled,
	)
	var i DomainRedirect
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.SourceDomain,
		&i.TargetDomain,
		&i.Code,
		&i.PreservePath,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteDNSProvider = `-- name: DeleteDNSProvider :exec
DELETE FROM dns_providers WHERE id = $1
`

func (q *Queries) DeleteDNSProvider(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteDNSProvider, id)
	return err
}

const deleteDomainCertificate = `-- name: DeleteDomainCertificate :exec
DELETE FROM domain_certificates WHERE id = $1
`

func (q *Queries) DeleteDomainCertificate(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteDomainCertificate, id)
	return err
}

const deleteDomainRedirect = `-- name: DeleteDomainRedirect :exec
DELETE FROM domain_redirects WHERE id = $1
`

func (q *Queries) DeleteDomainRedirect(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteDomainRedirect, id)
	return err
}

const deleteProxyConfigVersion = `-- name: DeleteProxyConfigVersion :exec
DELETE FROM proxy_config_versions WHERE id = $1 AND server_id = $2 AND pending
`

type DeleteProxyConfigVersionParams struct {
	ID       pgtype.UUID `json:"id"`
	ServerID pgtype.UUID `json:"server_id"`
}

// DeleteProxyConfigVersion drops one PENDING version (used to abort a record
// after a push that provably never touched the node). The active snapshot can
// never be deleted through this query.
func (q *Queries) DeleteProxyConfigVersion(ctx context.Context, arg DeleteProxyConfigVersionParams) error {
	_, err := q.db.Exec(ctx, deleteProxyConfigVersion, arg.ID, arg.ServerID)
	return err
}

const getDNSProvider = `-- name: GetDNSProvider :one
SELECT id, provider, name, zones, ciphertext, enabled, created_at, updated_at FROM dns_providers WHERE id = $1
`

func (q *Queries) GetDNSProvider(ctx context.Context, id pgtype.UUID) (DnsProvider, error) {
	row := q.db.QueryRow(ctx, getDNSProvider, id)
	var i DnsProvider
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.Name,
		&i.Zones,
		&i.Ciphertext,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDomainCertificate = `-- name: GetDomainCertificate :one
SELECT id, application_id, domain, enabled, challenge, dns_provider_id, wildcard, created_at, updated_at FROM domain_certificates WHERE id = $1
`

func (q *Queries) GetDomainCertificate(ctx context.Context, id pgtype.UUID) (DomainCertificate, error) {
	row := q.db.QueryRow(ctx, getDomainCertificate, id)
	var i DomainCertificate
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.Domain,
		&i.Enabled,
		&i.Challenge,
		&i.DnsProviderID,
		&i.Wildcard,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDomainCertificateByApplication = `-- name: GetDomainCertificateByApplication :one
SELECT id, application_id, domain, enabled, challenge, dns_provider_id, wildcard, created_at, updated_at FROM domain_certificates WHERE application_id = $1
`

func (q *Queries) GetDomainCertificateByApplication(ctx context.Context, applicationID pgtype.UUID) (DomainCertificate, error) {
	row := q.db.QueryRow(ctx, getDomainCertificateByApplication, applicationID)
	var i DomainCertificate
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.Domain,
		&i.Enabled,
		&i.Challenge,
		&i.DnsProviderID,
		&i.Wildcard,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDomainRedirect = `-- name: GetDomainRedirect :one
SELECT id, application_id, source_domain, target_domain, code, preserve_path, enabled, created_at, updated_at FROM domain_redirects WHERE id = $1
`

func (q *Queries) GetDomainRedirect(ctx context.Context, id pgtype.UUID) (DomainRedirect, error) {
	row := q.db.QueryRow(ctx, getDomainRedirect, id)
	var i DomainRedirect
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.SourceDomain,
		&i.TargetDomain,
		&i.Code,
		&i.PreservePath,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDomainRedirectBySource = `-- name: GetDomainRedirectBySource :one
SELECT id, application_id, source_domain, target_domain, code, preserve_path, enabled, created_at, updated_at FROM domain_redirects WHERE source_domain = $1
`

// GetDomainRedirectBySource resolves the unique source-host claim.
func (q *Queries) GetDomainRedirectBySource(ctx context.Context, sourceDomain string) (DomainRedirect, error) {
	row := q.db.QueryRow(ctx, getDomainRedirectBySource, sourceDomain)
	var i DomainRedirect
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.SourceDomain,
		&i.TargetDomain,
		&i.Code,
		&i.PreservePath,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertPendingProxyConfigVersion = `-- name: InsertPendingProxyConfigVersion :one
INSERT INTO proxy_config_versions (server_id, files, content_hash, pending)
VALUES ($1, $2, $3, true)
RETURNING id, server_id, files, content_hash, created_at, pending, superseded_at
`

type InsertPendingProxyConfigVersionParams struct {
	ServerID    pgtype.UUID `json:"server_id"`
	Files       []byte      `json:"files"`
	ContentHash string      `json:"content_hash"`
}

// InsertPendingProxyConfigVersion durably records a configuration about to be
// pushed to the node, before the node is touched.
func (q *Queries) InsertPendingProxyConfigVersion(ctx context.Context, arg InsertPendingProxyConfigVersionParams) (ProxyConfigVersion, error) {
	row := q.db.QueryRow(ctx, insertPendingProxyConfigVersion, arg.ServerID, arg.Files, arg.ContentHash)
	var i ProxyConfigVersion
	err := row.Scan(
		&i.ID,
		&i.ServerID,
		&i.Files,
		&i.ContentHash,
		&i.CreatedAt,
		&i.Pending,
		&i.SupersededAt,
	)
	return i, err
}

const listApplicationBaseDomains = `-- name: ListApplicationBaseDomains :many
SELECT id, base_domain FROM applications WHERE base_domain <> ''
`

type ListApplicationBaseDomainsRow struct {
	ID         pgtype.UUID `json:"id"`
	BaseDomain string      `json:"base_domain"`
}

// ListApplicationBaseDomains feeds the redirect ownership guard: a redirect
// source must never shadow any application's base domain (on any node), so
// the two routers can never match the same host.
func (q *Queries) ListApplicationBaseDomains(ctx context.Context) ([]ListApplicationBaseDomainsRow, error) {
	rows, err := q.db.Query(ctx, listApplicationBaseDomains)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListApplicationBaseDomainsRow{}
	for rows.Next() {
		var i ListApplicationBaseDomainsRow
		if err := rows.Scan(&i.ID, &i.BaseDomain); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCertificateStatusTargets = `-- name: ListCertificateStatusTargets :many
SELECT c.id AS certificate_id, c.domain, a.server_id
FROM domain_certificates c
JOIN applications a ON a.id = c.application_id
ORDER BY c.id
`

type ListCertificateStatusTargetsRow struct {
	CertificateID pgtype.UUID `json:"certificate_id"`
	Domain        string      `json:"domain"`
	ServerID      pgtype.UUID `json:"server_id"`
}

// ListCertificateStatusTargets joins every certificate intent to the node
// hosting its application, so the status service can read each node's ACME
// storage once and map certificates to it. Disabled intents are included:
// status is a fact about the node's storage, not about the intent.
func (q *Queries) ListCertificateStatusTargets(ctx context.Context) ([]ListCertificateStatusTargetsRow, error) {
	rows, err := q.db.Query(ctx, listCertificateStatusTargets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCertificateStatusTargetsRow{}
	for rows.Next() {
		var i ListCertificateStatusTargetsRow
		if err := rows.Scan(&i.CertificateID, &i.Domain, &i.ServerID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDNSProviders = `-- name: ListDNSProviders :many
SELECT id, provider, name, zones, ciphertext, enabled, created_at, updated_at FROM dns_providers
ORDER BY created_at DESC, id DESC
`

// ListDNSProviders returns every configured DNS provider, newest first. The
// sealed credential is read by the proxy service to build the Traefik
// container environment; it is never returned through the API.
func (q *Queries) ListDNSProviders(ctx context.Context) ([]DnsProvider, error) {
	rows, err := q.db.Query(ctx, listDNSProviders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DnsProvider{}
	for rows.Next() {
		var i DnsProvider
		if err := rows.Scan(
			&i.ID,
			&i.Provider,
			&i.Name,
			&i.Zones,
			&i.Ciphertext,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDomainCertificates = `-- name: ListDomainCertificates :many
SELECT id, application_id, domain, enabled, challenge, dns_provider_id, wildcard, created_at, updated_at FROM domain_certificates
ORDER BY created_at DESC, id DESC
`

func (q *Queries) ListDomainCertificates(ctx context.Context) ([]DomainCertificate, error) {
	rows, err := q.db.Query(ctx, listDomainCertificates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DomainCertificate{}
	for rows.Next() {
		var i DomainCertificate
		if err := rows.Scan(
			&i.ID,
			&i.ApplicationID,
			&i.Domain,
			&i.Enabled,
			&i.Challenge,
			&i.DnsProviderID,
			&i.Wildcard,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDomainRedirects = `-- name: ListDomainRedirects :many
SELECT id, application_id, source_domain, target_domain, code, preserve_path, enabled, created_at, updated_at FROM domain_redirects
ORDER BY created_at DESC, id DESC
`

// ListDomainRedirects returns every redirect rule, newest first.
func (q *Queries) ListDomainRedirects(ctx context.Context) ([]DomainRedirect, error) {
	rows, err := q.db.Query(ctx, listDomainRedirects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DomainRedirect{}
	for rows.Next() {
		var i DomainRedirect
		if err := rows.Scan(
			&i.ID,
			&i.ApplicationID,
			&i.SourceDomain,
			&i.TargetDomain,
			&i.Code,
			&i.PreservePath,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDomainRedirectsByApplication = `-- name: ListDomainRedirectsByApplication :many
SELECT id, application_id, source_domain, target_domain, code, preserve_path, enabled, created_at, updated_at FROM domain_redirects
WHERE application_id = $1
ORDER BY created_at DESC, id DESC
`

// ListDomainRedirectsByApplication returns one application's rules, newest
// first.
func (q *Queries) ListDomainRedirectsByApplication(ctx context.Context, applicationID pgtype.UUID) ([]DomainRedirect, error) {
	rows, err := q.db.Query(ctx, listDomainRedirectsByApplication, applicationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DomainRedirect{}
	for rows.Next() {
		var i DomainRedirect
		if err := rows.Scan(
			&i.ID,
			&i.ApplicationID,
			&i.SourceDomain,
			&i.TargetDomain,
			&i.Code,
			&i.PreservePath,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnabledDomainCertificatesByProvider = `-- name: ListEnabledDomainCertificatesByProvider :many
SELECT id, application_id, domain, enabled, challenge, dns_provider_id, wildcard, created_at, updated_at FROM domain_certificates
WHERE dns_provider_id = $1 AND enabled
ORDER BY created_at, id
`

// ListEnabledDomainCertificatesByProvider feeds the zone-narrowing guard.
func (q *Queries) ListEnabledDomainCertificatesByProvider(ctx context.Context, dnsProviderID pgtype.UUID) ([]DomainCertificate, error) {
	rows, err := q.db.Query(ctx, listEnabledDomainCertificatesByProvider, dnsProviderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DomainCertificate{}
	for rows.Next() {
		var i DomainCertificate
		if err := rows.Scan(
			&i.ID,
			&i.ApplicationID,
			&i.Domain,
			&i.Enabled,
			&i.Challenge,
			&i.DnsProviderID,
			&i.Wildcard,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnabledRedirects = `-- name: ListEnabledRedirects :many
SELECT id, source_domain, target_domain FROM domain_redirects WHERE enabled
`

type ListEnabledRedirectsRow struct {
	ID           pgtype.UUID `json:"id"`
	SourceDomain string      `json:"source_domain"`
	TargetDomain string      `json:"target_domain"`
}

// ListEnabledRedirects returns the endpoints of every enabled redirect rule.
// It feeds the no-chain guard in both directions (a proposed target must not
// be another enabled rule's source, and a proposed source must not be another
// enabled rule's target), so a chain can never be introduced by a create,
// update or enable.
func (q *Queries) ListEnabledRedirects(ctx context.Context) ([]ListEnabledRedirectsRow, error) {
	rows, err := q.db.Query(ctx, listEnabledRedirects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEnabledRedirectsRow{}
	for rows.Next() {
		var i ListEnabledRedirectsRow
		if err := rows.Scan(&i.ID, &i.SourceDomain, &i.TargetDomain); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProxiedApplications = `-- name: ListProxiedApplications :many
SELECT a.id, a.server_id, a.base_domain, a.base_domain_disabled, a.port, a.host_port,
       COALESCE(d.container_id, '')::text AS container_id,
       (c.id IS NOT NULL)::boolean AS certificate_configured,
       COALESCE(c.domain, '')::text AS certificate_domain,
       COALESCE(c.enabled, false) AS certificate_enabled,
       COALESCE(c.challenge, '')::text AS certificate_challenge,
       COALESCE(c.wildcard, false) AS certificate_wildcard,
       c.dns_provider_id AS certificate_dns_provider_id
FROM applications a
LEFT JOIN domain_certificates c ON c.application_id = a.id
LEFT JOIN LATERAL (
    SELECT container_id FROM deployments
    WHERE application_id = a.id AND state = 'running' AND container_id <> ''
    ORDER BY created_at DESC
    LIMIT 1
) d ON true
WHERE a.base_domain <> ''
ORDER BY a.created_at, a.id
`

type ListProxiedApplicationsRow struct {
	ID                       pgtype.UUID `json:"id"`
	ServerID                 pgtype.UUID `json:"server_id"`
	BaseDomain               string      `json:"base_domain"`
	BaseDomainDisabled       bool        `json:"base_domain_disabled"`
	Port                     int32       `json:"port"`
	HostPort                 int32       `json:"host_port"`
	ContainerID              string      `json:"container_id"`
	CertificateConfigured    bool        `json:"certificate_configured"`
	CertificateDomain        string      `json:"certificate_domain"`
	CertificateEnabled       bool        `json:"certificate_enabled"`
	CertificateChallenge     string      `json:"certificate_challenge"`
	CertificateWildcard      bool        `json:"certificate_wildcard"`
	CertificateDnsProviderID pgtype.UUID `json:"certificate_dns_provider_id"`
}

// ProxiedApplications feeds the Traefik config generator (Phase 6, BE-6.1):
// every application that declares a base_domain must be routed, on the node
// that hosts it, from the endpoint of its newest running deployment. Rows are
// ordered by creation time so duplicate-domain dispositions and generation
// input stay deterministic.
//
// The certificate columns (BE-6.2) carry the per-application certificate
// intent. They are NULL-joined as empty values: certificate_configured tells
// the generator whether an intent exists at all, and the recorded domain
// lets it refuse to activate a certificate whose host no longer matches.
func (q *Queries) ListProxiedApplications(ctx context.Context) ([]ListProxiedApplicationsRow, error) {
	rows, err := q.db.Query(ctx, listProxiedApplications)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProxiedApplicationsRow{}
	for rows.Next() {
		var i ListProxiedApplicationsRow
		if err := rows.Scan(
			&i.ID,
			&i.ServerID,
			&i.BaseDomain,
			&i.BaseDomainDisabled,
			&i.Port,
			&i.HostPort,
			&i.ContainerID,
			&i.CertificateConfigured,
			&i.CertificateDomain,
			&i.CertificateEnabled,
			&i.CertificateChallenge,
			&i.CertificateWildcard,
			&i.CertificateDnsProviderID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRedirectRules = `-- name: ListRedirectRules :many
SELECT r.id, r.application_id, r.source_domain, r.target_domain, r.code,
       r.preserve_path, r.enabled, r.created_at, r.updated_at,
       a.server_id, a.base_domain_disabled
FROM domain_redirects r
JOIN applications a ON a.id = r.application_id
ORDER BY r.created_at, r.id
`

type ListRedirectRulesRow struct {
	ID                 pgtype.UUID        `json:"id"`
	ApplicationID      pgtype.UUID        `json:"application_id"`
	SourceDomain       string             `json:"source_domain"`
	TargetDomain       string             `json:"target_domain"`
	Code               int16              `json:"code"`
	PreservePath       bool               `json:"preserve_path"`
	Enabled            bool               `json:"enabled"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	ServerID           pgtype.UUID        `json:"server_id"`
	BaseDomainDisabled bool               `json:"base_domain_disabled"`
}

// ListRedirectRules joins every redirect rule to its application's node state
// for the proxy generator: the owning node decides which Traefik instance
// serves the rule, and the domain-disabled flag holds back rules of an
// application whose route is already excluded by the uniqueness conflict.
func (q *Queries) ListRedirectRules(ctx context.Context) ([]ListRedirectRulesRow, error) {
	rows, err := q.db.Query(ctx, listRedirectRules)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRedirectRulesRow{}
	for rows.Next() {
		var i ListRedirectRulesRow
		if err := rows.Scan(
			&i.ID,
			&i.ApplicationID,
			&i.SourceDomain,
			&i.TargetDomain,
			&i.Code,
			&i.PreservePath,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ServerID,
			&i.BaseDomainDisabled,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const newestActiveProxyConfigVersion = `-- name: NewestActiveProxyConfigVersion :one
SELECT id, server_id, files, content_hash, created_at, pending, superseded_at FROM proxy_config_versions
WHERE server_id = $1 AND NOT pending AND superseded_at IS NULL
ORDER BY created_at DESC, id DESC
LIMIT 1
`

// NewestActiveProxyConfigVersion returns the configuration the node is
// believed to serve: the newest promoted, not-yet-superseded version.
func (q *Queries) NewestActiveProxyConfigVersion(ctx context.Context, serverID pgtype.UUID) (ProxyConfigVersion, error) {
	row := q.db.QueryRow(ctx, newestActiveProxyConfigVersion, serverID)
	var i ProxyConfigVersion
	err := row.Scan(
		&i.ID,
		&i.ServerID,
		&i.Files,
		&i.ContentHash,
		&i.CreatedAt,
		&i.Pending,
		&i.SupersededAt,
	)
	return i, err
}

const pendingProxyConfigVersion = `-- name: PendingProxyConfigVersion :one
SELECT id, server_id, files, content_hash, created_at, pending, superseded_at FROM proxy_config_versions
WHERE server_id = $1 AND pending
ORDER BY created_at DESC, id DESC
LIMIT 1
`

// PendingProxyConfigVersion returns the newest version recorded but not yet
// promoted (the intent to replace the active configuration).
func (q *Queries) PendingProxyConfigVersion(ctx context.Context, serverID pgtype.UUID) (ProxyConfigVersion, error) {
	row := q.db.QueryRow(ctx, pendingProxyConfigVersion, serverID)
	var i ProxyConfigVersion
	err := row.Scan(
		&i.ID,
		&i.ServerID,
		&i.Files,
		&i.ContentHash,
		&i.CreatedAt,
		&i.Pending,
		&i.SupersededAt,
	)
	return i, err
}

const previousProxyConfigVersion = `-- name: PreviousProxyConfigVersion :one
SELECT id, server_id, files, content_hash, created_at, pending, superseded_at FROM proxy_config_versions
WHERE server_id = $1 AND NOT pending AND superseded_at IS NOT NULL
ORDER BY superseded_at DESC, id DESC
LIMIT 1
`

// PreviousProxyConfigVersion returns the newest replaced predecessor.
func (q *Queries) PreviousProxyConfigVersion(ctx context.Context, serverID pgtype.UUID) (ProxyConfigVersion, error) {
	row := q.db.QueryRow(ctx, previousProxyConfigVersion, serverID)
	var i ProxyConfigVersion
	err := row.Scan(
		&i.ID,
		&i.ServerID,
		&i.Files,
		&i.ContentHash,
		&i.CreatedAt,
		&i.Pending,
		&i.SupersededAt,
	)
	return i, err
}

const promoteProxyConfigVersion = `-- name: PromoteProxyConfigVersion :exec
UPDATE proxy_config_versions SET pending = false WHERE id = $1
`

// PromoteProxyConfigVersion marks a pending version as the active one.
func (q *Queries) PromoteProxyConfigVersion(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, promoteProxyConfigVersion, id)
	return err
}

const pruneSupersededProxyConfigVersions = `-- name: PruneSupersededProxyConfigVersions :exec
DELETE FROM proxy_config_versions
WHERE server_id = $1 AND superseded_at IS NOT NULL AND superseded_at < $2
`

type PruneSupersededProxyConfigVersionsParams struct {
	ServerID     pgtype.UUID        `json:"server_id"`
	SupersededAt pgtype.Timestamptz `json:"superseded_at"`
}

// PruneSupersededProxyConfigVersions drops predecessors whose retention
// window has elapsed; the active version is never pruned.
func (q *Queries) PruneSupersededProxyConfigVersions(ctx context.Context, arg PruneSupersededProxyConfigVersionsParams) error {
	_, err := q.db.Exec(ctx, pruneSupersededProxyConfigVersions, arg.ServerID, arg.SupersededAt)
	return err
}

const supersedeActiveProxyConfigVersions = `-- name: SupersedeActiveProxyConfigVersions :exec
UPDATE proxy_config_versions
SET superseded_at = now()
WHERE server_id = $1 AND NOT pending AND superseded_at IS NULL AND id <> $2
`

type SupersedeActiveProxyConfigVersionsParams struct {
	ServerID pgtype.UUID `json:"server_id"`
	ID       pgtype.UUID `json:"id"`
}

// SupersedeActiveProxyConfigVersions retires the previous active version the
// moment its replacement is promoted, starting its retention window.
func (q *Queries) SupersedeActiveProxyConfigVersions(ctx context.Context, arg SupersedeActiveProxyConfigVersionsParams) error {
	_, err := q.db.Exec(ctx, supersedeActiveProxyConfigVersions, arg.ServerID, arg.ID)
	return err
}

const updateDNSProvider = `-- name: UpdateDNSProvider :one
UPDATE dns_providers
SET provider = $2,
    name = $3,
    zones = $4,
    ciphertext = $5,
    enabled = $6,
    updated_at = now()
WHERE id = $1
RETURNING id, provider, name, zones, ciphertext, enabled, created_at, updated_at
`

type UpdateDNSProviderParams struct {
	ID         pgtype.UUID `json:"id"`
	Provider   string      `json:"provider"`
	Name       string      `json:"name"`
	Zones      []string    `json:"zones"`
	Ciphertext string      `json:"ciphertext"`
	Enabled    bool        `json:"enabled"`
}

func (q *Queries) UpdateDNSProvider(ctx context.Context, arg UpdateDNSProviderParams) (DnsProvider, error) {
	row := q.db.QueryRow(ctx, updateDNSProvider,
		arg.ID,
		arg.Provider,
		arg.Name,
		arg.Zones,
		arg.Ciphertext,
		arg.Enabled,
	)
	var i DnsProvider
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.Name,
		&i.Zones,
		&i.Ciphertext,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateDNSProviderMeta = `-- name: UpdateDNSProviderMeta :one
UPDATE dns_providers
SET provider = $2,
    name = $3,
    zones = $4,
    enabled = $5,
    updated_at = now()
WHERE id = $1
RETURNING id, provider, name, zones, ciphertext, enabled, created_at, updated_at
`

type UpdateDNSProviderMetaParams struct {
	ID       pgtype.UUID `json:"id"`
	Provider string      `json:"provider"`
	Name     string      `json:"name"`
	Zones    []string    `json:"zones"`
	Enabled  bool        `json:"enabled"`
}

// UpdateDNSProviderMeta writes everything but the sealed credential, so an
// update that does not rotate can never restore an older ciphertext after a
// concurrent rotation.
func (q *Queries) UpdateDNSProviderMeta(ctx context.Context, arg UpdateDNSProviderMetaParams) (DnsProvider, error) {
	row := q.db.QueryRow(ctx, updateDNSProviderMeta,
		arg.ID,
		arg.Provider,
		arg.Name,
		arg.Zones,
		arg.Enabled,
	)
	var i DnsProvider
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.Name,
		&i.Zones,
		&i.Ciphertext,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateDomainCertificate = `-- name: UpdateDomainCertificate :one
UPDATE domain_certificates
SET domain = $2,
    enabled = $3,
    challenge = $4,
    dns_provider_id = $5,
    wildcard = $6,
    updated_at = now()
WHERE id = $1
RETURNING id, application_id, domain, enabled, challenge, dns_provider_id, wildcard, created_at, updated_at
`

type UpdateDomainCertificateParams struct {
	ID            pgtype.UUID `json:"id"`
	Domain        string      `json:"domain"`
	Enabled       bool        `json:"enabled"`
	Challenge     string      `json:"challenge"`
	DnsProviderID pgtype.UUID `json:"dns_provider_id"`
	Wildcard      bool        `json:"wildcard"`
}

func (q *Queries) UpdateDomainCertificate(ctx context.Context, arg UpdateDomainCertificateParams) (DomainCertificate, error) {
	row := q.db.QueryRow(ctx, updateDomainCertificate,
		arg.ID,
		arg.Domain,
		arg.Enabled,
		arg.Challenge,
		arg.DnsProviderID,
		arg.Wildcard,
	)
	var i DomainCertificate
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.Domain,
		&i.Enabled,
		&i.Challenge,
		&i.DnsProviderID,
		&i.Wildcard,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateDomainRedirect = `-- name: UpdateDomainRedirect :one
UPDATE domain_redirects
SET source_domain = $2,
    target_domain = $3,
    code = $4,
    preserve_path = $5,
    enabled = $6,
    updated_at = now()
WHERE id = $1
RETURNING id, application_id, source_domain, target_domain, code, preserve_path, enabled, created_at, updated_at
`

type UpdateDomainRedirectParams struct {
	ID           pgtype.UUID `json:"id"`
	SourceDomain string      `json:"source_domain"`
	TargetDomain string      `json:"target_domain"`
	Code         int16       `json:"code"`
	PreservePath bool        `json:"preserve_path"`
	Enabled      bool        `json:"enabled"`
}

func (q *Queries) UpdateDomainRedirect(ctx context.Context, arg UpdateDomainRedirectParams) (DomainRedirect, error) {
	row := q.db.QueryRow(ctx, updateDomainRedirect,
		arg.ID,
		arg.SourceDomain,
		arg.TargetDomain,
		arg.Code,
		arg.PreservePath,
		arg.Enabled,
	)
	var i DomainRedirect
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.SourceDomain,
		&i.TargetDomain,
		&i.Code,
		&i.PreservePath,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
