// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: servers.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimServerByNodeID = `-- name: ClaimServerByNodeID :one
UPDATE servers
SET node_id = $1,
    updated_at = now()
WHERE id = (
    SELECT s.id FROM servers s
    WHERE s.node_id IS NULL AND s.ip <> '' AND s.ip = $2
    ORDER BY s.created_at ASC
    LIMIT 1
    FOR UPDATE
)
RETURNING id, name, ip, port, ssh_user, ssh_key_id, status, node_id, os, docker_version, arch, total_mem, total_disk, cpu_usage, mem_usage, disk_usage, container_count, last_seen, created_at, updated_at, team_id, host_key_fingerprint, encrypted_password
`

type ClaimServerByNodeIDParams struct {
	NodeID *string `json:"node_id"`
	Ip     string  `json:"ip"`
}

// Claims an operator-created server row (node_id still NULL) whose address
// matches the registering node, so enrollment updates that existing row instead
// of inserting a duplicate. The row lock serializes two concurrent
// registrations: the loser's subquery re-reads the claimed row, finds no
// candidate, and falls back to the node-id upsert.
func (q *Queries) ClaimServerByNodeID(ctx context.Context, arg ClaimServerByNodeIDParams) (Server, error) {
	row := q.db.QueryRow(ctx, claimServerByNodeID, arg.NodeID, arg.Ip)
	var i Server
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Ip,
		&i.Port,
		&i.SshUser,
		&i.SshKeyID,
		&i.Status,
		&i.NodeID,
		&i.Os,
		&i.DockerVersion,
		&i.Arch,
		&i.TotalMem,
		&i.TotalDisk,
		&i.CpuUsage,
		&i.MemUsage,
		&i.DiskUsage,
		&i.ContainerCount,
		&i.LastSeen,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TeamID,
		&i.HostKeyFingerprint,
		&i.EncryptedPassword,
	)
	return i, err
}

const clearServerHostKey = `-- name: ClearServerHostKey :one
UPDATE servers
SET host_key_fingerprint = NULL,
    updated_at = now()
WHERE id = $1
RETURNING id, name, ip, port, ssh_user, ssh_key_id, status, node_id, os, docker_version, arch, total_mem, total_disk, cpu_usage, mem_usage, disk_usage, container_count, last_seen, created_at, updated_at, team_id, host_key_fingerprint, encrypted_password
`

// Forgets the pinned host key so the next validation re-pins it (operator reset
// after a legitimate host key rotation).
func (q *Queries) ClearServerHostKey(ctx context.Context, id pgtype.UUID) (Server, error) {
	row := q.db.QueryRow(ctx, clearServerHostKey, id)
	var i Server
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Ip,
		&i.Port,
		&i.SshUser,
		&i.SshKeyID,
		&i.Status,
		&i.NodeID,
		&i.Os,
		&i.DockerVersion,
		&i.Arch,
		&i.TotalMem,
		&i.TotalDisk,
		&i.CpuUsage,
		&i.MemUsage,
		&i.DiskUsage,
		&i.ContainerCount,
		&i.LastSeen,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TeamID,
		&i.HostKeyFingerprint,
		&i.EncryptedPassword,
	)
	return i, err
}

const createServer = `-- name: CreateServer :one
INSERT INTO servers (name, ip, port, ssh_user, ssh_key_id, team_id, encrypted_password)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, name, ip, port, ssh_user, ssh_key_id, status, node_id, os, docker_version, arch, total_mem, total_disk, cpu_usage, mem_usage, disk_usage, container_count, last_seen, created_at, updated_at, team_id, host_key_fingerprint, encrypted_password
`

type CreateServerParams struct {
	Name              string      `json:"name"`
	Ip                string      `json:"ip"`
	Port              int32       `json:"port"`
	SshUser           string      `json:"ssh_user"`
	SshKeyID          pgtype.UUID `json:"ssh_key_id"`
	TeamID            pgtype.UUID `json:"team_id"`
	EncryptedPassword *string     `json:"encrypted_password"`
}

func (q *Queries) CreateServer(ctx context.Context, arg CreateServerParams) (Server, error) {
	row := q.db.QueryRow(ctx, createServer,
		arg.Name,
		arg.Ip,
		arg.Port,
		arg.SshUser,
		arg.SshKeyID,
		arg.TeamID,
		arg.EncryptedPassword,
	)
	var i Server
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Ip,
		&i.Port,
		&i.SshUser,
		&i.SshKeyID,
		&i.Status,
		&i.NodeID,
		&i.Os,
		&i.DockerVersion,
		&i.Arch,
		&i.TotalMem,
		&i.TotalDisk,
		&i.CpuUsage,
		&i.MemUsage,
		&i.DiskUsage,
		&i.ContainerCount,
		&i.LastSeen,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TeamID,
		&i.HostKeyFingerprint,
		&i.EncryptedPassword,
	)
	return i, err
}

const deleteServer = `-- name: DeleteServer :exec
DELETE FROM servers WHERE id = $1
`

func (q *Queries) DeleteServer(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteServer, id)
	return err
}

const getServerByID = `-- name: GetServerByID :one
SELECT id, name, ip, port, ssh_user, ssh_key_id, status, node_id, os, docker_version, arch, total_mem, total_disk, cpu_usage, mem_usage, disk_usage, container_count, last_seen, created_at, updated_at, team_id, host_key_fingerprint, encrypted_password FROM servers WHERE id = $1
`

func (q *Queries) GetServerByID(ctx context.Context, id pgtype.UUID) (Server, error) {
	row := q.db.QueryRow(ctx, getServerByID, id)
	var i Server
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Ip,
		&i.Port,
		&i.SshUser,
		&i.SshKeyID,
		&i.Status,
		&i.NodeID,
		&i.Os,
		&i.DockerVersion,
		&i.Arch,
		&i.TotalMem,
		&i.TotalDisk,
		&i.CpuUsage,
		&i.MemUsage,
		&i.DiskUsage,
		&i.ContainerCount,
		&i.LastSeen,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TeamID,
		&i.HostKeyFingerprint,
		&i.EncryptedPassword,
	)
	return i, err
}

const getServerByIDForUpdate = `-- name: GetServerByIDForUpdate :one
SELECT id, name, ip, port, ssh_user, ssh_key_id, status, node_id, os, docker_version, arch, total_mem, total_disk, cpu_usage, mem_usage, disk_usage, container_count, last_seen, created_at, updated_at, team_id, host_key_fingerprint, encrypted_password FROM servers WHERE id = $1 FOR UPDATE
`

// Locks the node row for a PATCH edit (Update): the service re-reads under
// this lock and computes the write from the locked row, so a concurrent
// heartbeat/RegisterNode/ResetHostKey/Validate write cannot be reverted by a
// stale read (JUS-5 fix round 1, defect 2).
func (q *Queries) GetServerByIDForUpdate(ctx context.Context, id pgtype.UUID) (Server, error) {
	row := q.db.QueryRow(ctx, getServerByIDForUpdate, id)
	var i Server
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Ip,
		&i.Port,
		&i.SshUser,
		&i.SshKeyID,
		&i.Status,
		&i.NodeID,
		&i.Os,
		&i.DockerVersion,
		&i.Arch,
		&i.TotalMem,
		&i.TotalDisk,
		&i.CpuUsage,
		&i.MemUsage,
		&i.DiskUsage,
		&i.ContainerCount,
		&i.LastSeen,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TeamID,
		&i.HostKeyFingerprint,
		&i.EncryptedPassword,
	)
	return i, err
}

const getServerByNodeID = `-- name: GetServerByNodeID :one
SELECT id, name, ip, port, ssh_user, ssh_key_id, status, node_id, os, docker_version, arch, total_mem, total_disk, cpu_usage, mem_usage, disk_usage, container_count, last_seen, created_at, updated_at, team_id, host_key_fingerprint, encrypted_password FROM servers WHERE node_id = $1
`

func (q *Queries) GetServerByNodeID(ctx context.Context, nodeID *string) (Server, error) {
	row := q.db.QueryRow(ctx, getServerByNodeID, nodeID)
	var i Server
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Ip,
		&i.Port,
		&i.SshUser,
		&i.SshKeyID,
		&i.Status,
		&i.NodeID,
		&i.Os,
		&i.DockerVersion,
		&i.Arch,
		&i.TotalMem,
		&i.TotalDisk,
		&i.CpuUsage,
		&i.MemUsage,
		&i.DiskUsage,
		&i.ContainerCount,
		&i.LastSeen,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TeamID,
		&i.HostKeyFingerprint,
		&i.EncryptedPassword,
	)
	return i, err
}

const listServers = `-- name: ListServers :many
SELECT id, name, ip, port, ssh_user, ssh_key_id, status, node_id, os, docker_version, arch, total_mem, total_disk, cpu_usage, mem_usage, disk_usage, container_count, last_seen, created_at, updated_at, team_id, host_key_fingerprint, encrypted_password FROM servers ORDER BY created_at DESC, id DESC
`

func (q *Queries) ListServers(ctx context.Context) ([]Server, error) {
	rows, err := q.db.Query(ctx, listServers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Server{}
	for rows.Next() {
		var i Server
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Ip,
			&i.Port,
			&i.SshUser,
			&i.SshKeyID,
			&i.Status,
			&i.NodeID,
			&i.Os,
			&i.DockerVersion,
			&i.Arch,
			&i.TotalMem,
			&i.TotalDisk,
			&i.CpuUsage,
			&i.MemUsage,
			&i.DiskUsage,
			&i.ContainerCount,
			&i.LastSeen,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TeamID,
			&i.HostKeyFingerprint,
			&i.EncryptedPassword,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listServersByTeam = `-- name: ListServersByTeam :many
SELECT id, name, ip, port, ssh_user, ssh_key_id, status, node_id, os, docker_version, arch, total_mem, total_disk, cpu_usage, mem_usage, disk_usage, container_count, last_seen, created_at, updated_at, team_id, host_key_fingerprint, encrypted_password FROM servers
WHERE team_id = $1 OR team_id IS NULL
ORDER BY created_at DESC, id DESC
`

// A legacy node (team_id NULL) predates teams and stays visible to every
// authenticated caller; a team node belongs to its team only.
func (q *Queries) ListServersByTeam(ctx context.Context, teamID pgtype.UUID) ([]Server, error) {
	rows, err := q.db.Query(ctx, listServersByTeam, teamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Server{}
	for rows.Next() {
		var i Server
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Ip,
			&i.Port,
			&i.SshUser,
			&i.SshKeyID,
			&i.Status,
			&i.NodeID,
			&i.Os,
			&i.DockerVersion,
			&i.Arch,
			&i.TotalMem,
			&i.TotalDisk,
			&i.CpuUsage,
			&i.MemUsage,
			&i.DiskUsage,
			&i.ContainerCount,
			&i.LastSeen,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TeamID,
			&i.HostKeyFingerprint,
			&i.EncryptedPassword,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markStaleServersOffline = `-- name: MarkStaleServersOffline :exec
UPDATE servers
SET status = 'offline',
    updated_at = now()
WHERE status = 'ready' AND (last_seen IS NULL OR last_seen < $1)
`

// Flips nodes that were ready but have not heartbeated since the cutoff to
// offline, so the read path always reports the live status the FE understands
// (A4-6). A ready row with no last_seen is stale by definition.
func (q *Queries) MarkStaleServersOffline(ctx context.Context, lastSeen pgtype.Timestamptz) error {
	_, err := q.db.Exec(ctx, markStaleServersOffline, lastSeen)
	return err
}

const pinServerHostKey = `-- name: PinServerHostKey :one
UPDATE servers
SET host_key_fingerprint = $2,
    updated_at = now()
WHERE id = $1 AND host_key_fingerprint IS NULL
RETURNING id, name, ip, port, ssh_user, ssh_key_id, status, node_id, os, docker_version, arch, total_mem, total_disk, cpu_usage, mem_usage, disk_usage, container_count, last_seen, created_at, updated_at, team_id, host_key_fingerprint, encrypted_password
`

type PinServerHostKeyParams struct {
	ID                 pgtype.UUID `json:"id"`
	HostKeyFingerprint *string     `json:"host_key_fingerprint"`
}

// Pins the TOFU host key fingerprint of a node only when it is still unpinned.
// A stale first-use validation then cannot overwrite a pin written by a racing
// validation; 0 rows means the node was pinned in the meantime and the caller
// must re-read and fail closed on a mismatch.
func (q *Queries) PinServerHostKey(ctx context.Context, arg PinServerHostKeyParams) (Server, error) {
	row := q.db.QueryRow(ctx, pinServerHostKey, arg.ID, arg.HostKeyFingerprint)
	var i Server
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Ip,
		&i.Port,
		&i.SshUser,
		&i.SshKeyID,
		&i.Status,
		&i.NodeID,
		&i.Os,
		&i.DockerVersion,
		&i.Arch,
		&i.TotalMem,
		&i.TotalDisk,
		&i.CpuUsage,
		&i.MemUsage,
		&i.DiskUsage,
		&i.ContainerCount,
		&i.LastSeen,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TeamID,
		&i.HostKeyFingerprint,
		&i.EncryptedPassword,
	)
	return i, err
}

const pinServerHostKeyGuarded = `-- name: PinServerHostKeyGuarded :one
UPDATE servers
SET host_key_fingerprint = $2,
    updated_at = now()
WHERE id = $1 AND host_key_fingerprint IS NULL
  AND ip = $3
  AND port = $4
  AND ssh_user = $5
  AND ssh_key_id IS NOT DISTINCT FROM $6
  AND encrypted_password IS NOT DISTINCT FROM $7
RETURNING id, name, ip, port, ssh_user, ssh_key_id, status, node_id, os, docker_version, arch, total_mem, total_disk, cpu_usage, mem_usage, disk_usage, container_count, last_seen, created_at, updated_at, team_id, host_key_fingerprint, encrypted_password
`

type PinServerHostKeyGuardedParams struct {
	ID                 pgtype.UUID `json:"id"`
	HostKeyFingerprint *string     `json:"host_key_fingerprint"`
	Ip                 string      `json:"ip"`
	Port               int32       `json:"port"`
	SshUser            string      `json:"ssh_user"`
	SshKeyID           pgtype.UUID `json:"ssh_key_id"`
	EncryptedPassword  *string     `json:"encrypted_password"`
}

// Pins like PinServerHostKey, but only when the row still matches the endpoint
// and credentials the validation ran against (JUS-5 fix round 1, defect 1). A
// concurrent PATCH that changed the address or credentials clears the pin and
// returns the node to pending; the stale validation's pin then affects 0 rows
// and must be dropped instead of pinning the OLD host's key onto the NEW
// address. A heartbeat or inventory write touches none of the guarded columns,
// so it never blocks a legitimate pin.
func (q *Queries) PinServerHostKeyGuarded(ctx context.Context, arg PinServerHostKeyGuardedParams) (Server, error) {
	row := q.db.QueryRow(ctx, pinServerHostKeyGuarded,
		arg.ID,
		arg.HostKeyFingerprint,
		arg.Ip,
		arg.Port,
		arg.SshUser,
		arg.SshKeyID,
		arg.EncryptedPassword,
	)
	var i Server
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Ip,
		&i.Port,
		&i.SshUser,
		&i.SshKeyID,
		&i.Status,
		&i.NodeID,
		&i.Os,
		&i.DockerVersion,
		&i.Arch,
		&i.TotalMem,
		&i.TotalDisk,
		&i.CpuUsage,
		&i.MemUsage,
		&i.DiskUsage,
		&i.ContainerCount,
		&i.LastSeen,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TeamID,
		&i.HostKeyFingerprint,
		&i.EncryptedPassword,
	)
	return i, err
}

const setServerStatus = `-- name: SetServerStatus :one
UPDATE servers
SET status = $2,
    updated_at = now()
WHERE id = $1
RETURNING id, name, ip, port, ssh_user, ssh_key_id, status, node_id, os, docker_version, arch, total_mem, total_disk, cpu_usage, mem_usage, disk_usage, container_count, last_seen, created_at, updated_at, team_id, host_key_fingerprint, encrypted_password
`

type SetServerStatusParams struct {
	ID     pgtype.UUID `json:"id"`
	Status string      `json:"status"`
}

func (q *Queries) SetServerStatus(ctx context.Context, arg SetServerStatusParams) (Server, error) {
	row := q.db.QueryRow(ctx, setServerStatus, arg.ID, arg.Status)
	var i Server
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Ip,
		&i.Port,
		&i.SshUser,
		&i.SshKeyID,
		&i.Status,
		&i.NodeID,
		&i.Os,
		&i.DockerVersion,
		&i.Arch,
		&i.TotalMem,
		&i.TotalDisk,
		&i.CpuUsage,
		&i.MemUsage,
		&i.DiskUsage,
		&i.ContainerCount,
		&i.LastSeen,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TeamID,
		&i.HostKeyFingerprint,
		&i.EncryptedPassword,
	)
	return i, err
}

const setServerStatusAfterValidation = `-- name: SetServerStatusAfterValidation :one
UPDATE servers
SET status = CASE
        WHEN last_seen IS NOT NULL AND last_seen >= $2 THEN 'ready'
        WHEN last_seen IS NOT NULL THEN 'offline'
        ELSE 'pending'
    END,
    updated_at = now()
WHERE id = $1
RETURNING id, name, ip, port, ssh_user, ssh_key_id, status, node_id, os, docker_version, arch, total_mem, total_disk, cpu_usage, mem_usage, disk_usage, container_count, last_seen, created_at, updated_at, team_id, host_key_fingerprint, encrypted_password
`

type SetServerStatusAfterValidationParams struct {
	ID       pgtype.UUID        `json:"id"`
	LastSeen pgtype.Timestamptz `json:"last_seen"`
}

// Restores a node's status after a successful SSH validation. Ready is reserved
// for a live agent heartbeat, so the status is derived from last_seen at the
// moment of the write: a heartbeat that landed during the validation (fresh
// last_seen) keeps the node ready, a node seen before but now past the window
// goes offline, and a node never seen stays pending. Deriving it in one
// statement means a concurrent heartbeat cannot be clobbered by a stale read
// (A4-15/B4-9, fix round 1 U2).
func (q *Queries) SetServerStatusAfterValidation(ctx context.Context, arg SetServerStatusAfterValidationParams) (Server, error) {
	row := q.db.QueryRow(ctx, setServerStatusAfterValidation, arg.ID, arg.LastSeen)
	var i Server
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Ip,
		&i.Port,
		&i.SshUser,
		&i.SshKeyID,
		&i.Status,
		&i.NodeID,
		&i.Os,
		&i.DockerVersion,
		&i.Arch,
		&i.TotalMem,
		&i.TotalDisk,
		&i.CpuUsage,
		&i.MemUsage,
		&i.DiskUsage,
		&i.ContainerCount,
		&i.LastSeen,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TeamID,
		&i.HostKeyFingerprint,
		&i.EncryptedPassword,
	)
	return i, err
}

const setServerStatusAfterValidationGuarded = `-- name: SetServerStatusAfterValidationGuarded :one
UPDATE servers
SET status = CASE
        WHEN last_seen IS NOT NULL AND last_seen >= $2 THEN 'ready'
        WHEN last_seen IS NOT NULL THEN 'offline'
        ELSE 'pending'
    END,
    updated_at = now()
WHERE id = $1
  AND ip = $3
  AND port = $4
  AND ssh_user = $5
  AND ssh_key_id IS NOT DISTINCT FROM $6
  AND encrypted_password IS NOT DISTINCT FROM $7
RETURNING id, name, ip, port, ssh_user, ssh_key_id, status, node_id, os, docker_version, arch, total_mem, total_disk, cpu_usage, mem_usage, disk_usage, container_count, last_seen, created_at, updated_at, team_id, host_key_fingerprint, encrypted_password
`

type SetServerStatusAfterValidationGuardedParams struct {
	ID                pgtype.UUID        `json:"id"`
	LastSeen          pgtype.Timestamptz `json:"last_seen"`
	Ip                string             `json:"ip"`
	Port              int32              `json:"port"`
	SshUser           string             `json:"ssh_user"`
	SshKeyID          pgtype.UUID        `json:"ssh_key_id"`
	EncryptedPassword *string            `json:"encrypted_password"`
}

// Restores the heartbeat-derived status like SetServerStatusAfterValidation,
// but only when the row still matches the endpoint and credentials the
// validation ran against (JUS-5 fix round 1, defect 1). A concurrent PATCH
// that moved the node to a new address (and back to pending) is left alone;
// 0 rows means the endpoint moved on and the caller drops the write. A
// heartbeat during the validation touches none of the guarded columns, so the
// live-agent derivation still lands.
func (q *Queries) SetServerStatusAfterValidationGuarded(ctx context.Context, arg SetServerStatusAfterValidationGuardedParams) (Server, error) {
	row := q.db.QueryRow(ctx, setServerStatusAfterValidationGuarded,
		arg.ID,
		arg.LastSeen,
		arg.Ip,
		arg.Port,
		arg.SshUser,
		arg.SshKeyID,
		arg.EncryptedPassword,
	)
	var i Server
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Ip,
		&i.Port,
		&i.SshUser,
		&i.SshKeyID,
		&i.Status,
		&i.NodeID,
		&i.Os,
		&i.DockerVersion,
		&i.Arch,
		&i.TotalMem,
		&i.TotalDisk,
		&i.CpuUsage,
		&i.MemUsage,
		&i.DiskUsage,
		&i.ContainerCount,
		&i.LastSeen,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TeamID,
		&i.HostKeyFingerprint,
		&i.EncryptedPassword,
	)
	return i, err
}

const setServerStatusGuarded = `-- name: SetServerStatusGuarded :one
UPDATE servers
SET status = $2,
    updated_at = now()
WHERE id = $1
  AND ip = $3
  AND port = $4
  AND ssh_user = $5
  AND ssh_key_id IS NOT DISTINCT FROM $6
  AND encrypted_password IS NOT DISTINCT FROM $7
RETURNING id, name, ip, port, ssh_user, ssh_key_id, status, node_id, os, docker_version, arch, total_mem, total_disk, cpu_usage, mem_usage, disk_usage, container_count, last_seen, created_at, updated_at, team_id, host_key_fingerprint, encrypted_password
`

type SetServerStatusGuardedParams struct {
	ID                pgtype.UUID `json:"id"`
	Status            string      `json:"status"`
	Ip                string      `json:"ip"`
	Port              int32       `json:"port"`
	SshUser           string      `json:"ssh_user"`
	SshKeyID          pgtype.UUID `json:"ssh_key_id"`
	EncryptedPassword *string     `json:"encrypted_password"`
}

// Sets the status only when the row still matches the endpoint and credentials
// the caller acted on (JUS-5 fix round 1, defect 1): a stale validation must
// not overwrite the pending status a concurrent PATCH set. 0 rows means the
// endpoint moved on; the caller drops the write.
func (q *Queries) SetServerStatusGuarded(ctx context.Context, arg SetServerStatusGuardedParams) (Server, error) {
	row := q.db.QueryRow(ctx, setServerStatusGuarded,
		arg.ID,
		arg.Status,
		arg.Ip,
		arg.Port,
		arg.SshUser,
		arg.SshKeyID,
		arg.EncryptedPassword,
	)
	var i Server
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Ip,
		&i.Port,
		&i.SshUser,
		&i.SshKeyID,
		&i.Status,
		&i.NodeID,
		&i.Os,
		&i.DockerVersion,
		&i.Arch,
		&i.TotalMem,
		&i.TotalDisk,
		&i.CpuUsage,
		&i.MemUsage,
		&i.DiskUsage,
		&i.ContainerCount,
		&i.LastSeen,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TeamID,
		&i.HostKeyFingerprint,
		&i.EncryptedPassword,
	)
	return i, err
}

const updateServer = `-- name: UpdateServer :one
UPDATE servers
SET name = $2,
    ip = $3,
    port = $4,
    ssh_user = $5,
    ssh_key_id = $6,
    encrypted_password = $7,
    host_key_fingerprint = $8,
    status = $9,
    updated_at = now()
WHERE id = $1
RETURNING id, name, ip, port, ssh_user, ssh_key_id, status, node_id, os, docker_version, arch, total_mem, total_disk, cpu_usage, mem_usage, disk_usage, container_count, last_seen, created_at, updated_at, team_id, host_key_fingerprint, encrypted_password
`

type UpdateServerParams struct {
	ID                 pgtype.UUID `json:"id"`
	Name               string      `json:"name"`
	Ip                 string      `json:"ip"`
	Port               int32       `json:"port"`
	SshUser            string      `json:"ssh_user"`
	SshKeyID           pgtype.UUID `json:"ssh_key_id"`
	EncryptedPassword  *string     `json:"encrypted_password"`
	HostKeyFingerprint *string     `json:"host_key_fingerprint"`
	Status             string      `json:"status"`
}

// Applies a PATCH edit computed by the domain service: every column is written
// as given, so the service owns the merge (field-by-field COALESCE would hide
// the difference between "unchanged" and "cleared to NULL"). host key and
// status arrive already derived: an address/identity/auth change clears the pin
// and returns the node to pending for revalidation.
func (q *Queries) UpdateServer(ctx context.Context, arg UpdateServerParams) (Server, error) {
	row := q.db.QueryRow(ctx, updateServer,
		arg.ID,
		arg.Name,
		arg.Ip,
		arg.Port,
		arg.SshUser,
		arg.SshKeyID,
		arg.EncryptedPassword,
		arg.HostKeyFingerprint,
		arg.Status,
	)
	var i Server
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Ip,
		&i.Port,
		&i.SshUser,
		&i.SshKeyID,
		&i.Status,
		&i.NodeID,
		&i.Os,
		&i.DockerVersion,
		&i.Arch,
		&i.TotalMem,
		&i.TotalDisk,
		&i.CpuUsage,
		&i.MemUsage,
		&i.DiskUsage,
		&i.ContainerCount,
		&i.LastSeen,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TeamID,
		&i.HostKeyFingerprint,
		&i.EncryptedPassword,
	)
	return i, err
}

const updateServerAgentInfo = `-- name: UpdateServerAgentInfo :one
UPDATE servers
SET node_id = $2,
    os = $3,
    docker_version = $4,
    arch = $5,
    total_mem = $6,
    total_disk = $7,
    updated_at = now()
WHERE id = $1
RETURNING id, name, ip, port, ssh_user, ssh_key_id, status, node_id, os, docker_version, arch, total_mem, total_disk, cpu_usage, mem_usage, disk_usage, container_count, last_seen, created_at, updated_at, team_id, host_key_fingerprint, encrypted_password
`

type UpdateServerAgentInfoParams struct {
	ID            pgtype.UUID `json:"id"`
	NodeID        *string     `json:"node_id"`
	Os            *string     `json:"os"`
	DockerVersion *string     `json:"docker_version"`
	Arch          *string     `json:"arch"`
	TotalMem      *int64      `json:"total_mem"`
	TotalDisk     *int64      `json:"total_disk"`
}

// Records the capabilities an SSH validation or agent registration reported. It
// deliberately does NOT touch status or last_seen: ready means a live agent
// heartbeat, so SSH reachability or a one-off registration must never flip a
// node ready on its own (A4-15/B4-9).
func (q *Queries) UpdateServerAgentInfo(ctx context.Context, arg UpdateServerAgentInfoParams) (Server, error) {
	row := q.db.QueryRow(ctx, updateServerAgentInfo,
		arg.ID,
		arg.NodeID,
		arg.Os,
		arg.DockerVersion,
		arg.Arch,
		arg.TotalMem,
		arg.TotalDisk,
	)
	var i Server
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Ip,
		&i.Port,
		&i.SshUser,
		&i.SshKeyID,
		&i.Status,
		&i.NodeID,
		&i.Os,
		&i.DockerVersion,
		&i.Arch,
		&i.TotalMem,
		&i.TotalDisk,
		&i.CpuUsage,
		&i.MemUsage,
		&i.DiskUsage,
		&i.ContainerCount,
		&i.LastSeen,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TeamID,
		&i.HostKeyFingerprint,
		&i.EncryptedPassword,
	)
	return i, err
}

const updateServerAgentInfoGuarded = `-- name: UpdateServerAgentInfoGuarded :one
UPDATE servers
SET node_id = $2,
    os = $3,
    docker_version = $4,
    arch = $5,
    total_mem = $6,
    total_disk = $7,
    updated_at = now()
WHERE id = $1
  AND ip = $8
  AND port = $9
  AND ssh_user = $10
  AND ssh_key_id IS NOT DISTINCT FROM $11
  AND encrypted_password IS NOT DISTINCT FROM $12
RETURNING id, name, ip, port, ssh_user, ssh_key_id, status, node_id, os, docker_version, arch, total_mem, total_disk, cpu_usage, mem_usage, disk_usage, container_count, last_seen, created_at, updated_at, team_id, host_key_fingerprint, encrypted_password
`

type UpdateServerAgentInfoGuardedParams struct {
	ID                pgtype.UUID `json:"id"`
	NodeID            *string     `json:"node_id"`
	Os                *string     `json:"os"`
	DockerVersion     *string     `json:"docker_version"`
	Arch              *string     `json:"arch"`
	TotalMem          *int64      `json:"total_mem"`
	TotalDisk         *int64      `json:"total_disk"`
	Ip                string      `json:"ip"`
	Port              int32       `json:"port"`
	SshUser           string      `json:"ssh_user"`
	SshKeyID          pgtype.UUID `json:"ssh_key_id"`
	EncryptedPassword *string     `json:"encrypted_password"`
}

// Records validation inventory only when the row still matches the endpoint
// the validation ran against (JUS-5 fix round 1, defect 1): a concurrent PATCH
// to a new address must not inherit the OLD host's inventory. Like the
// unguarded variant it never touches status or last_seen.
func (q *Queries) UpdateServerAgentInfoGuarded(ctx context.Context, arg UpdateServerAgentInfoGuardedParams) (Server, error) {
	row := q.db.QueryRow(ctx, updateServerAgentInfoGuarded,
		arg.ID,
		arg.NodeID,
		arg.Os,
		arg.DockerVersion,
		arg.Arch,
		arg.TotalMem,
		arg.TotalDisk,
		arg.Ip,
		arg.Port,
		arg.SshUser,
		arg.SshKeyID,
		arg.EncryptedPassword,
	)
	var i Server
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Ip,
		&i.Port,
		&i.SshUser,
		&i.SshKeyID,
		&i.Status,
		&i.NodeID,
		&i.Os,
		&i.DockerVersion,
		&i.Arch,
		&i.TotalMem,
		&i.TotalDisk,
		&i.CpuUsage,
		&i.MemUsage,
		&i.DiskUsage,
		&i.ContainerCount,
		&i.LastSeen,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TeamID,
		&i.HostKeyFingerprint,
		&i.EncryptedPassword,
	)
	return i, err
}

const updateServerMetrics = `-- name: UpdateServerMetrics :one
UPDATE servers
SET cpu_usage = $2,
    mem_usage = $3,
    disk_usage = $4,
    container_count = $5,
    status = 'ready',
    last_seen = now(),
    updated_at = now()
WHERE id = $1
RETURNING id, name, ip, port, ssh_user, ssh_key_id, status, node_id, os, docker_version, arch, total_mem, total_disk, cpu_usage, mem_usage, disk_usage, container_count, last_seen, created_at, updated_at, team_id, host_key_fingerprint, encrypted_password
`

type UpdateServerMetricsParams struct {
	ID             pgtype.UUID `json:"id"`
	CpuUsage       *float64    `json:"cpu_usage"`
	MemUsage       *float64    `json:"mem_usage"`
	DiskUsage      *float64    `json:"disk_usage"`
	ContainerCount *int64      `json:"container_count"`
}

func (q *Queries) UpdateServerMetrics(ctx context.Context, arg UpdateServerMetricsParams) (Server, error) {
	row := q.db.QueryRow(ctx, updateServerMetrics,
		arg.ID,
		arg.CpuUsage,
		arg.MemUsage,
		arg.DiskUsage,
		arg.ContainerCount,
	)
	var i Server
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Ip,
		&i.Port,
		&i.SshUser,
		&i.SshKeyID,
		&i.Status,
		&i.NodeID,
		&i.Os,
		&i.DockerVersion,
		&i.Arch,
		&i.TotalMem,
		&i.TotalDisk,
		&i.CpuUsage,
		&i.MemUsage,
		&i.DiskUsage,
		&i.ContainerCount,
		&i.LastSeen,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TeamID,
		&i.HostKeyFingerprint,
		&i.EncryptedPassword,
	)
	return i, err
}

const upsertServerByNodeID = `-- name: UpsertServerByNodeID :one
INSERT INTO servers (name, ip, port, ssh_user, node_id, os, docker_version, arch, total_mem, total_disk)
VALUES ($1, $2, $3, '', $4, $5, $6, $7, $8, $9)
ON CONFLICT (node_id) DO UPDATE
SET os = EXCLUDED.os,
    docker_version = EXCLUDED.docker_version,
    arch = EXCLUDED.arch,
    total_mem = EXCLUDED.total_mem,
    total_disk = EXCLUDED.total_disk,
    updated_at = now()
RETURNING id, name, ip, port, ssh_user, ssh_key_id, status, node_id, os, docker_version, arch, total_mem, total_disk, cpu_usage, mem_usage, disk_usage, container_count, last_seen, created_at, updated_at, team_id, host_key_fingerprint, encrypted_password
`

type UpsertServerByNodeIDParams struct {
	Name          string  `json:"name"`
	Ip            string  `json:"ip"`
	Port          int32   `json:"port"`
	NodeID        *string `json:"node_id"`
	Os            *string `json:"os"`
	DockerVersion *string `json:"docker_version"`
	Arch          *string `json:"arch"`
	TotalMem      *int64  `json:"total_mem"`
	TotalDisk     *int64  `json:"total_disk"`
}

// Conflict-safe registration keyed on the node's stable identity. A concurrent
// registration of the same node id converges on one row: the winner inserts and
// the loser's ON CONFLICT updates that same row, so a race can never leave a
// duplicate or an orphan row with a NULL node_id (A4-12). name/ip are not
// overwritten on conflict so an operator's label survives re-registration.
func (q *Queries) UpsertServerByNodeID(ctx context.Context, arg UpsertServerByNodeIDParams) (Server, error) {
	row := q.db.QueryRow(ctx, upsertServerByNodeID,
		arg.Name,
		arg.Ip,
		arg.Port,
		arg.NodeID,
		arg.Os,
		arg.DockerVersion,
		arg.Arch,
		arg.TotalMem,
		arg.TotalDisk,
	)
	var i Server
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Ip,
		&i.Port,
		&i.SshUser,
		&i.SshKeyID,
		&i.Status,
		&i.NodeID,
		&i.Os,
		&i.DockerVersion,
		&i.Arch,
		&i.TotalMem,
		&i.TotalDisk,
		&i.CpuUsage,
		&i.MemUsage,
		&i.DiskUsage,
		&i.ContainerCount,
		&i.LastSeen,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TeamID,
		&i.HostKeyFingerprint,
		&i.EncryptedPassword,
	)
	return i, err
}
