// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: servers.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const clearServerHostKey = `-- name: ClearServerHostKey :one
UPDATE servers
SET host_key_fingerprint = NULL,
    updated_at = now()
WHERE id = $1
RETURNING id, name, ip, port, ssh_user, ssh_key_id, status, node_id, os, docker_version, arch, total_mem, total_disk, cpu_usage, mem_usage, disk_usage, container_count, last_seen, created_at, updated_at, team_id, host_key_fingerprint
`

// Forgets the pinned host key so the next validation re-pins it (operator reset
// after a legitimate host key rotation).
func (q *Queries) ClearServerHostKey(ctx context.Context, id pgtype.UUID) (Server, error) {
	row := q.db.QueryRow(ctx, clearServerHostKey, id)
	var i Server
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Ip,
		&i.Port,
		&i.SshUser,
		&i.SshKeyID,
		&i.Status,
		&i.NodeID,
		&i.Os,
		&i.DockerVersion,
		&i.Arch,
		&i.TotalMem,
		&i.TotalDisk,
		&i.CpuUsage,
		&i.MemUsage,
		&i.DiskUsage,
		&i.ContainerCount,
		&i.LastSeen,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TeamID,
		&i.HostKeyFingerprint,
	)
	return i, err
}

const createServer = `-- name: CreateServer :one
INSERT INTO servers (name, ip, port, ssh_user, ssh_key_id, team_id)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, name, ip, port, ssh_user, ssh_key_id, status, node_id, os, docker_version, arch, total_mem, total_disk, cpu_usage, mem_usage, disk_usage, container_count, last_seen, created_at, updated_at, team_id, host_key_fingerprint
`

type CreateServerParams struct {
	Name     string      `json:"name"`
	Ip       string      `json:"ip"`
	Port     int32       `json:"port"`
	SshUser  string      `json:"ssh_user"`
	SshKeyID pgtype.UUID `json:"ssh_key_id"`
	TeamID   pgtype.UUID `json:"team_id"`
}

func (q *Queries) CreateServer(ctx context.Context, arg CreateServerParams) (Server, error) {
	row := q.db.QueryRow(ctx, createServer,
		arg.Name,
		arg.Ip,
		arg.Port,
		arg.SshUser,
		arg.SshKeyID,
		arg.TeamID,
	)
	var i Server
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Ip,
		&i.Port,
		&i.SshUser,
		&i.SshKeyID,
		&i.Status,
		&i.NodeID,
		&i.Os,
		&i.DockerVersion,
		&i.Arch,
		&i.TotalMem,
		&i.TotalDisk,
		&i.CpuUsage,
		&i.MemUsage,
		&i.DiskUsage,
		&i.ContainerCount,
		&i.LastSeen,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TeamID,
		&i.HostKeyFingerprint,
	)
	return i, err
}

const deleteServer = `-- name: DeleteServer :exec
DELETE FROM servers WHERE id = $1
`

func (q *Queries) DeleteServer(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteServer, id)
	return err
}

const getServerByID = `-- name: GetServerByID :one
SELECT id, name, ip, port, ssh_user, ssh_key_id, status, node_id, os, docker_version, arch, total_mem, total_disk, cpu_usage, mem_usage, disk_usage, container_count, last_seen, created_at, updated_at, team_id, host_key_fingerprint FROM servers WHERE id = $1
`

func (q *Queries) GetServerByID(ctx context.Context, id pgtype.UUID) (Server, error) {
	row := q.db.QueryRow(ctx, getServerByID, id)
	var i Server
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Ip,
		&i.Port,
		&i.SshUser,
		&i.SshKeyID,
		&i.Status,
		&i.NodeID,
		&i.Os,
		&i.DockerVersion,
		&i.Arch,
		&i.TotalMem,
		&i.TotalDisk,
		&i.CpuUsage,
		&i.MemUsage,
		&i.DiskUsage,
		&i.ContainerCount,
		&i.LastSeen,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TeamID,
		&i.HostKeyFingerprint,
	)
	return i, err
}

const getServerByNodeID = `-- name: GetServerByNodeID :one
SELECT id, name, ip, port, ssh_user, ssh_key_id, status, node_id, os, docker_version, arch, total_mem, total_disk, cpu_usage, mem_usage, disk_usage, container_count, last_seen, created_at, updated_at, team_id, host_key_fingerprint FROM servers WHERE node_id = $1
`

func (q *Queries) GetServerByNodeID(ctx context.Context, nodeID *string) (Server, error) {
	row := q.db.QueryRow(ctx, getServerByNodeID, nodeID)
	var i Server
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Ip,
		&i.Port,
		&i.SshUser,
		&i.SshKeyID,
		&i.Status,
		&i.NodeID,
		&i.Os,
		&i.DockerVersion,
		&i.Arch,
		&i.TotalMem,
		&i.TotalDisk,
		&i.CpuUsage,
		&i.MemUsage,
		&i.DiskUsage,
		&i.ContainerCount,
		&i.LastSeen,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TeamID,
		&i.HostKeyFingerprint,
	)
	return i, err
}

const listServers = `-- name: ListServers :many
SELECT id, name, ip, port, ssh_user, ssh_key_id, status, node_id, os, docker_version, arch, total_mem, total_disk, cpu_usage, mem_usage, disk_usage, container_count, last_seen, created_at, updated_at, team_id, host_key_fingerprint FROM servers ORDER BY created_at DESC, id DESC
`

func (q *Queries) ListServers(ctx context.Context) ([]Server, error) {
	rows, err := q.db.Query(ctx, listServers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Server{}
	for rows.Next() {
		var i Server
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Ip,
			&i.Port,
			&i.SshUser,
			&i.SshKeyID,
			&i.Status,
			&i.NodeID,
			&i.Os,
			&i.DockerVersion,
			&i.Arch,
			&i.TotalMem,
			&i.TotalDisk,
			&i.CpuUsage,
			&i.MemUsage,
			&i.DiskUsage,
			&i.ContainerCount,
			&i.LastSeen,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TeamID,
			&i.HostKeyFingerprint,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listServersByTeam = `-- name: ListServersByTeam :many
SELECT id, name, ip, port, ssh_user, ssh_key_id, status, node_id, os, docker_version, arch, total_mem, total_disk, cpu_usage, mem_usage, disk_usage, container_count, last_seen, created_at, updated_at, team_id, host_key_fingerprint FROM servers
WHERE team_id = $1 OR team_id IS NULL
ORDER BY created_at DESC, id DESC
`

// A legacy node (team_id NULL) predates teams and stays visible to every
// authenticated caller; a team node belongs to its team only.
func (q *Queries) ListServersByTeam(ctx context.Context, teamID pgtype.UUID) ([]Server, error) {
	rows, err := q.db.Query(ctx, listServersByTeam, teamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Server{}
	for rows.Next() {
		var i Server
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Ip,
			&i.Port,
			&i.SshUser,
			&i.SshKeyID,
			&i.Status,
			&i.NodeID,
			&i.Os,
			&i.DockerVersion,
			&i.Arch,
			&i.TotalMem,
			&i.TotalDisk,
			&i.CpuUsage,
			&i.MemUsage,
			&i.DiskUsage,
			&i.ContainerCount,
			&i.LastSeen,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TeamID,
			&i.HostKeyFingerprint,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setServerHostKey = `-- name: SetServerHostKey :one
UPDATE servers
SET host_key_fingerprint = $2,
    updated_at = now()
WHERE id = $1
RETURNING id, name, ip, port, ssh_user, ssh_key_id, status, node_id, os, docker_version, arch, total_mem, total_disk, cpu_usage, mem_usage, disk_usage, container_count, last_seen, created_at, updated_at, team_id, host_key_fingerprint
`

type SetServerHostKeyParams struct {
	ID                 pgtype.UUID `json:"id"`
	HostKeyFingerprint *string     `json:"host_key_fingerprint"`
}

// Pins (or replaces) the TOFU host key fingerprint of a node.
func (q *Queries) SetServerHostKey(ctx context.Context, arg SetServerHostKeyParams) (Server, error) {
	row := q.db.QueryRow(ctx, setServerHostKey, arg.ID, arg.HostKeyFingerprint)
	var i Server
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Ip,
		&i.Port,
		&i.SshUser,
		&i.SshKeyID,
		&i.Status,
		&i.NodeID,
		&i.Os,
		&i.DockerVersion,
		&i.Arch,
		&i.TotalMem,
		&i.TotalDisk,
		&i.CpuUsage,
		&i.MemUsage,
		&i.DiskUsage,
		&i.ContainerCount,
		&i.LastSeen,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TeamID,
		&i.HostKeyFingerprint,
	)
	return i, err
}

const setServerStatus = `-- name: SetServerStatus :one
UPDATE servers
SET status = $2,
    updated_at = now()
WHERE id = $1
RETURNING id, name, ip, port, ssh_user, ssh_key_id, status, node_id, os, docker_version, arch, total_mem, total_disk, cpu_usage, mem_usage, disk_usage, container_count, last_seen, created_at, updated_at, team_id, host_key_fingerprint
`

type SetServerStatusParams struct {
	ID     pgtype.UUID `json:"id"`
	Status string      `json:"status"`
}

func (q *Queries) SetServerStatus(ctx context.Context, arg SetServerStatusParams) (Server, error) {
	row := q.db.QueryRow(ctx, setServerStatus, arg.ID, arg.Status)
	var i Server
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Ip,
		&i.Port,
		&i.SshUser,
		&i.SshKeyID,
		&i.Status,
		&i.NodeID,
		&i.Os,
		&i.DockerVersion,
		&i.Arch,
		&i.TotalMem,
		&i.TotalDisk,
		&i.CpuUsage,
		&i.MemUsage,
		&i.DiskUsage,
		&i.ContainerCount,
		&i.LastSeen,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TeamID,
		&i.HostKeyFingerprint,
	)
	return i, err
}

const updateServerAgentInfo = `-- name: UpdateServerAgentInfo :one
UPDATE servers
SET node_id = $2,
    os = $3,
    docker_version = $4,
    arch = $5,
    total_mem = $6,
    total_disk = $7,
    status = 'ready',
    last_seen = now(),
    updated_at = now()
WHERE id = $1
RETURNING id, name, ip, port, ssh_user, ssh_key_id, status, node_id, os, docker_version, arch, total_mem, total_disk, cpu_usage, mem_usage, disk_usage, container_count, last_seen, created_at, updated_at, team_id, host_key_fingerprint
`

type UpdateServerAgentInfoParams struct {
	ID            pgtype.UUID `json:"id"`
	NodeID        *string     `json:"node_id"`
	Os            *string     `json:"os"`
	DockerVersion *string     `json:"docker_version"`
	Arch          *string     `json:"arch"`
	TotalMem      *int64      `json:"total_mem"`
	TotalDisk     *int64      `json:"total_disk"`
}

func (q *Queries) UpdateServerAgentInfo(ctx context.Context, arg UpdateServerAgentInfoParams) (Server, error) {
	row := q.db.QueryRow(ctx, updateServerAgentInfo,
		arg.ID,
		arg.NodeID,
		arg.Os,
		arg.DockerVersion,
		arg.Arch,
		arg.TotalMem,
		arg.TotalDisk,
	)
	var i Server
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Ip,
		&i.Port,
		&i.SshUser,
		&i.SshKeyID,
		&i.Status,
		&i.NodeID,
		&i.Os,
		&i.DockerVersion,
		&i.Arch,
		&i.TotalMem,
		&i.TotalDisk,
		&i.CpuUsage,
		&i.MemUsage,
		&i.DiskUsage,
		&i.ContainerCount,
		&i.LastSeen,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TeamID,
		&i.HostKeyFingerprint,
	)
	return i, err
}

const updateServerMetrics = `-- name: UpdateServerMetrics :one
UPDATE servers
SET cpu_usage = $2,
    mem_usage = $3,
    disk_usage = $4,
    container_count = $5,
    status = 'ready',
    last_seen = now(),
    updated_at = now()
WHERE id = $1
RETURNING id, name, ip, port, ssh_user, ssh_key_id, status, node_id, os, docker_version, arch, total_mem, total_disk, cpu_usage, mem_usage, disk_usage, container_count, last_seen, created_at, updated_at, team_id, host_key_fingerprint
`

type UpdateServerMetricsParams struct {
	ID             pgtype.UUID `json:"id"`
	CpuUsage       *float64    `json:"cpu_usage"`
	MemUsage       *float64    `json:"mem_usage"`
	DiskUsage      *float64    `json:"disk_usage"`
	ContainerCount *int64      `json:"container_count"`
}

func (q *Queries) UpdateServerMetrics(ctx context.Context, arg UpdateServerMetricsParams) (Server, error) {
	row := q.db.QueryRow(ctx, updateServerMetrics,
		arg.ID,
		arg.CpuUsage,
		arg.MemUsage,
		arg.DiskUsage,
		arg.ContainerCount,
	)
	var i Server
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Ip,
		&i.Port,
		&i.SshUser,
		&i.SshKeyID,
		&i.Status,
		&i.NodeID,
		&i.Os,
		&i.DockerVersion,
		&i.Arch,
		&i.TotalMem,
		&i.TotalDisk,
		&i.CpuUsage,
		&i.MemUsage,
		&i.DiskUsage,
		&i.ContainerCount,
		&i.LastSeen,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TeamID,
		&i.HostKeyFingerprint,
	)
	return i, err
}
