// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: services.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countServicesByEnvironment = `-- name: CountServicesByEnvironment :one
SELECT count(*) FROM services WHERE environment_id = $1 AND deleted_at IS NULL
`

func (q *Queries) CountServicesByEnvironment(ctx context.Context, environmentID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countServicesByEnvironment, environmentID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countServicesByProject = `-- name: CountServicesByProject :one
SELECT count(*) FROM services s
JOIN environments e ON e.id = s.environment_id
WHERE e.project_id = $1 AND s.deleted_at IS NULL
`

func (q *Queries) CountServicesByProject(ctx context.Context, projectID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countServicesByProject, projectID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createService = `-- name: CreateService :one
INSERT INTO services (
    id, user_id, server_id, environment_id, name, status, compose_yaml, env, team_id
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, user_id, server_id, name, status, compose_yaml, env, created_at, updated_at, deleted_at, team_id, environment_id
`

type CreateServiceParams struct {
	ID            pgtype.UUID `json:"id"`
	UserID        pgtype.UUID `json:"user_id"`
	ServerID      pgtype.UUID `json:"server_id"`
	EnvironmentID pgtype.UUID `json:"environment_id"`
	Name          string      `json:"name"`
	Status        string      `json:"status"`
	ComposeYaml   string      `json:"compose_yaml"`
	Env           []byte      `json:"env"`
	TeamID        pgtype.UUID `json:"team_id"`
}

func (q *Queries) CreateService(ctx context.Context, arg CreateServiceParams) (Service, error) {
	row := q.db.QueryRow(ctx, createService,
		arg.ID,
		arg.UserID,
		arg.ServerID,
		arg.EnvironmentID,
		arg.Name,
		arg.Status,
		arg.ComposeYaml,
		arg.Env,
		arg.TeamID,
	)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ServerID,
		&i.Name,
		&i.Status,
		&i.ComposeYaml,
		&i.Env,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.TeamID,
		&i.EnvironmentID,
	)
	return i, err
}

const createServiceDeploy = `-- name: CreateServiceDeploy :one
INSERT INTO service_deploys (id, service_id, state, compose_yaml)
VALUES ($1, $2, $3, $4)
RETURNING id, service_id, state, compose_yaml, error, created_at, updated_at, finished_at
`

type CreateServiceDeployParams struct {
	ID          pgtype.UUID `json:"id"`
	ServiceID   pgtype.UUID `json:"service_id"`
	State       string      `json:"state"`
	ComposeYaml string      `json:"compose_yaml"`
}

func (q *Queries) CreateServiceDeploy(ctx context.Context, arg CreateServiceDeployParams) (ServiceDeploy, error) {
	row := q.db.QueryRow(ctx, createServiceDeploy,
		arg.ID,
		arg.ServiceID,
		arg.State,
		arg.ComposeYaml,
	)
	var i ServiceDeploy
	err := row.Scan(
		&i.ID,
		&i.ServiceID,
		&i.State,
		&i.ComposeYaml,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FinishedAt,
	)
	return i, err
}

const getService = `-- name: GetService :one
SELECT id, user_id, server_id, name, status, compose_yaml, env, created_at, updated_at, deleted_at, team_id, environment_id FROM services
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetService(ctx context.Context, id pgtype.UUID) (Service, error) {
	row := q.db.QueryRow(ctx, getService, id)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ServerID,
		&i.Name,
		&i.Status,
		&i.ComposeYaml,
		&i.Env,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.TeamID,
		&i.EnvironmentID,
	)
	return i, err
}

const hasActiveServiceDeploy = `-- name: HasActiveServiceDeploy :one
SELECT EXISTS (
    SELECT 1 FROM service_deploys WHERE service_id = $1 AND state = 'deploying'
)
`

// A service with a deploy in flight refuses a server change (409), like an
// application with a non-terminal deployment.
func (q *Queries) HasActiveServiceDeploy(ctx context.Context, serviceID pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, hasActiveServiceDeploy, serviceID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const hasServiceDeploys = `-- name: HasServiceDeploys :one
SELECT EXISTS (
    SELECT 1 FROM service_deploys WHERE service_id = $1
)
`

// Whether the service was ever deployed. A deployed service cannot change
// node: its compose project runs there.
func (q *Queries) HasServiceDeploys(ctx context.Context, serviceID pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, hasServiceDeploys, serviceID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listRoutableServices = `-- name: ListRoutableServices :many
SELECT id, user_id, server_id, name, status, compose_yaml, env, created_at, updated_at, deleted_at, team_id, environment_id FROM services
WHERE deleted_at IS NULL
ORDER BY created_at ASC, id ASC
`

// ListRoutableServices returns every live service with its document and
// environment, in creation order, so the proxy source can render each one's
// current domain map (a service that no longer renders is reported as
// unroutable rather than failing the node's sync).
func (q *Queries) ListRoutableServices(ctx context.Context) ([]Service, error) {
	rows, err := q.db.Query(ctx, listRoutableServices)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Service{}
	for rows.Next() {
		var i Service
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ServerID,
			&i.Name,
			&i.Status,
			&i.ComposeYaml,
			&i.Env,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.TeamID,
			&i.EnvironmentID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listServiceDeploys = `-- name: ListServiceDeploys :many
SELECT id, service_id, state, compose_yaml, error, created_at, updated_at, finished_at FROM service_deploys
WHERE service_id = $1
ORDER BY created_at DESC, id DESC
LIMIT $2
`

type ListServiceDeploysParams struct {
	ServiceID pgtype.UUID `json:"service_id"`
	Limit     int32       `json:"limit"`
}

func (q *Queries) ListServiceDeploys(ctx context.Context, arg ListServiceDeploysParams) ([]ServiceDeploy, error) {
	rows, err := q.db.Query(ctx, listServiceDeploys, arg.ServiceID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ServiceDeploy{}
	for rows.Next() {
		var i ServiceDeploy
		if err := rows.Scan(
			&i.ID,
			&i.ServiceID,
			&i.State,
			&i.ComposeYaml,
			&i.Error,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listServicesByEnvironment = `-- name: ListServicesByEnvironment :many
SELECT id, user_id, server_id, name, status, compose_yaml, env, created_at, updated_at, deleted_at, team_id, environment_id FROM services
WHERE environment_id = $1 AND deleted_at IS NULL
ORDER BY created_at DESC, id DESC
`

func (q *Queries) ListServicesByEnvironment(ctx context.Context, environmentID pgtype.UUID) ([]Service, error) {
	rows, err := q.db.Query(ctx, listServicesByEnvironment, environmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Service{}
	for rows.Next() {
		var i Service
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ServerID,
			&i.Name,
			&i.Status,
			&i.ComposeYaml,
			&i.Env,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.TeamID,
			&i.EnvironmentID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listServicesByProject = `-- name: ListServicesByProject :many
SELECT s.id, s.user_id, s.server_id, s.name, s.status, s.compose_yaml, s.env, s.created_at, s.updated_at, s.deleted_at, s.team_id, s.environment_id FROM services s
JOIN environments e ON e.id = s.environment_id
WHERE e.project_id = $1 AND s.deleted_at IS NULL
ORDER BY s.created_at DESC, s.id DESC
`

func (q *Queries) ListServicesByProject(ctx context.Context, projectID pgtype.UUID) ([]Service, error) {
	rows, err := q.db.Query(ctx, listServicesByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Service{}
	for rows.Next() {
		var i Service
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ServerID,
			&i.Name,
			&i.Status,
			&i.ComposeYaml,
			&i.Env,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.TeamID,
			&i.EnvironmentID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listServicesByServer = `-- name: ListServicesByServer :many
SELECT id, name FROM services
WHERE server_id = $1 AND deleted_at IS NULL
ORDER BY created_at DESC, id DESC
`

type ListServicesByServerRow struct {
	ID   pgtype.UUID `json:"id"`
	Name string      `json:"name"`
}

func (q *Queries) ListServicesByServer(ctx context.Context, serverID pgtype.UUID) ([]ListServicesByServerRow, error) {
	rows, err := q.db.Query(ctx, listServicesByServer, serverID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListServicesByServerRow{}
	for rows.Next() {
		var i ListServicesByServerRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listServicesByTeam = `-- name: ListServicesByTeam :many
SELECT id, user_id, server_id, name, status, compose_yaml, env, created_at, updated_at, deleted_at, team_id, environment_id FROM services
WHERE team_id = $1 AND deleted_at IS NULL
ORDER BY created_at DESC, id DESC
`

func (q *Queries) ListServicesByTeam(ctx context.Context, teamID pgtype.UUID) ([]Service, error) {
	rows, err := q.db.Query(ctx, listServicesByTeam, teamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Service{}
	for rows.Next() {
		var i Service
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ServerID,
			&i.Name,
			&i.Status,
			&i.ComposeYaml,
			&i.Env,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.TeamID,
			&i.EnvironmentID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listServicesByUser = `-- name: ListServicesByUser :many
SELECT id, user_id, server_id, name, status, compose_yaml, env, created_at, updated_at, deleted_at, team_id, environment_id FROM services
WHERE user_id = $1 AND deleted_at IS NULL
ORDER BY created_at DESC, id DESC
`

func (q *Queries) ListServicesByUser(ctx context.Context, userID pgtype.UUID) ([]Service, error) {
	rows, err := q.db.Query(ctx, listServicesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Service{}
	for rows.Next() {
		var i Service
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ServerID,
			&i.Name,
			&i.Status,
			&i.ComposeYaml,
			&i.Env,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.TeamID,
			&i.EnvironmentID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const purgeTombstonedServicesByEnvironment = `-- name: PurgeTombstonedServicesByEnvironment :execrows
DELETE FROM services
WHERE environment_id = $1 AND deleted_at IS NOT NULL
`

// Hard-deletes the soft-deleted services of one environment. An
// environment delete purges these in the same transaction first, so only
// live services block it (409); the compose volumes intentionally survive
// (they are the project's data, like on a soft delete).
func (q *Queries) PurgeTombstonedServicesByEnvironment(ctx context.Context, environmentID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, purgeTombstonedServicesByEnvironment, environmentID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const purgeTombstonedServicesByProject = `-- name: PurgeTombstonedServicesByProject :execrows
DELETE FROM services
WHERE environment_id IN (SELECT id FROM environments WHERE project_id = $1)
AND deleted_at IS NOT NULL
`

// Same as above for every environment of one project.
func (q *Queries) PurgeTombstonedServicesByProject(ctx context.Context, projectID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, purgeTombstonedServicesByProject, projectID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const purgeTombstonedServicesByServer = `-- name: PurgeTombstonedServicesByServer :execrows
DELETE FROM services
WHERE server_id = $1 AND deleted_at IS NOT NULL
`

// Same as above for one node.
func (q *Queries) PurgeTombstonedServicesByServer(ctx context.Context, serverID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, purgeTombstonedServicesByServer, serverID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const serviceNameInEnvironment = `-- name: ServiceNameInEnvironment :one
SELECT EXISTS (
    SELECT 1 FROM services
    WHERE environment_id = $1 AND name = $2 AND id <> $3 AND deleted_at IS NULL
)
`

type ServiceNameInEnvironmentParams struct {
	EnvironmentID pgtype.UUID `json:"environment_id"`
	Name          string      `json:"name"`
	ID            pgtype.UUID `json:"id"`
}

// The move-collision pre-check: whether the environment holds another live
// service with the name (exact match, like the unique index).
func (q *Queries) ServiceNameInEnvironment(ctx context.Context, arg ServiceNameInEnvironmentParams) (bool, error) {
	row := q.db.QueryRow(ctx, serviceNameInEnvironment, arg.EnvironmentID, arg.Name, arg.ID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const softDeleteService = `-- name: SoftDeleteService :one
UPDATE services
SET status = 'deleting',
    deleted_at = now(),
    updated_at = now()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, user_id, server_id, name, status, compose_yaml, env, created_at, updated_at, deleted_at, team_id, environment_id
`

func (q *Queries) SoftDeleteService(ctx context.Context, id pgtype.UUID) (Service, error) {
	row := q.db.QueryRow(ctx, softDeleteService, id)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ServerID,
		&i.Name,
		&i.Status,
		&i.ComposeYaml,
		&i.Env,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.TeamID,
		&i.EnvironmentID,
	)
	return i, err
}

const updateServiceConfig = `-- name: UpdateServiceConfig :one
UPDATE services
SET name = $2,
    compose_yaml = $3,
    env = $4,
    environment_id = COALESCE($5, environment_id),
    server_id = COALESCE($6, server_id),
    updated_at = now()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, user_id, server_id, name, status, compose_yaml, env, created_at, updated_at, deleted_at, team_id, environment_id
`

type UpdateServiceConfigParams struct {
	ID            pgtype.UUID `json:"id"`
	Name          string      `json:"name"`
	ComposeYaml   string      `json:"compose_yaml"`
	Env           []byte      `json:"env"`
	EnvironmentID pgtype.UUID `json:"environment_id"`
	ServerID      pgtype.UUID `json:"server_id"`
}

// Only the name, document, environment and variables are written, and the
// placement columns only when the caller passes them (COALESCE with narg):
// the service zeroes placement fields the request leaves alone, so a stale
// snapshot can never write back an old environment or server.
func (q *Queries) UpdateServiceConfig(ctx context.Context, arg UpdateServiceConfigParams) (Service, error) {
	row := q.db.QueryRow(ctx, updateServiceConfig,
		arg.ID,
		arg.Name,
		arg.ComposeYaml,
		arg.Env,
		arg.EnvironmentID,
		arg.ServerID,
	)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ServerID,
		&i.Name,
		&i.Status,
		&i.ComposeYaml,
		&i.Env,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.TeamID,
		&i.EnvironmentID,
	)
	return i, err
}

const updateServiceDeploy = `-- name: UpdateServiceDeploy :one
UPDATE service_deploys
SET state = $2,
    error = $3,
    finished_at = $4,
    updated_at = now()
WHERE id = $1
RETURNING id, service_id, state, compose_yaml, error, created_at, updated_at, finished_at
`

type UpdateServiceDeployParams struct {
	ID         pgtype.UUID        `json:"id"`
	State      string             `json:"state"`
	Error      string             `json:"error"`
	FinishedAt pgtype.Timestamptz `json:"finished_at"`
}

func (q *Queries) UpdateServiceDeploy(ctx context.Context, arg UpdateServiceDeployParams) (ServiceDeploy, error) {
	row := q.db.QueryRow(ctx, updateServiceDeploy,
		arg.ID,
		arg.State,
		arg.Error,
		arg.FinishedAt,
	)
	var i ServiceDeploy
	err := row.Scan(
		&i.ID,
		&i.ServiceID,
		&i.State,
		&i.ComposeYaml,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FinishedAt,
	)
	return i, err
}

const updateServiceStatus = `-- name: UpdateServiceStatus :one
UPDATE services
SET status = $2,
    updated_at = now()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, user_id, server_id, name, status, compose_yaml, env, created_at, updated_at, deleted_at, team_id, environment_id
`

type UpdateServiceStatusParams struct {
	ID     pgtype.UUID `json:"id"`
	Status string      `json:"status"`
}

func (q *Queries) UpdateServiceStatus(ctx context.Context, arg UpdateServiceStatusParams) (Service, error) {
	row := q.db.QueryRow(ctx, updateServiceStatus, arg.ID, arg.Status)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ServerID,
		&i.Name,
		&i.Status,
		&i.ComposeYaml,
		&i.Env,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.TeamID,
		&i.EnvironmentID,
	)
	return i, err
}
