// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: services.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createService = `-- name: CreateService :one
INSERT INTO services (
    id, user_id, server_id, name, status, compose_yaml, env
)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, user_id, server_id, name, status, compose_yaml, env, created_at, updated_at, deleted_at
`

type CreateServiceParams struct {
	ID          pgtype.UUID `json:"id"`
	UserID      pgtype.UUID `json:"user_id"`
	ServerID    pgtype.UUID `json:"server_id"`
	Name        string      `json:"name"`
	Status      string      `json:"status"`
	ComposeYaml string      `json:"compose_yaml"`
	Env         []byte      `json:"env"`
}

func (q *Queries) CreateService(ctx context.Context, arg CreateServiceParams) (Service, error) {
	row := q.db.QueryRow(ctx, createService,
		arg.ID,
		arg.UserID,
		arg.ServerID,
		arg.Name,
		arg.Status,
		arg.ComposeYaml,
		arg.Env,
	)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ServerID,
		&i.Name,
		&i.Status,
		&i.ComposeYaml,
		&i.Env,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createServiceDeploy = `-- name: CreateServiceDeploy :one
INSERT INTO service_deploys (id, service_id, state, compose_yaml)
VALUES ($1, $2, $3, $4)
RETURNING id, service_id, state, compose_yaml, error, created_at, updated_at, finished_at
`

type CreateServiceDeployParams struct {
	ID          pgtype.UUID `json:"id"`
	ServiceID   pgtype.UUID `json:"service_id"`
	State       string      `json:"state"`
	ComposeYaml string      `json:"compose_yaml"`
}

func (q *Queries) CreateServiceDeploy(ctx context.Context, arg CreateServiceDeployParams) (ServiceDeploy, error) {
	row := q.db.QueryRow(ctx, createServiceDeploy,
		arg.ID,
		arg.ServiceID,
		arg.State,
		arg.ComposeYaml,
	)
	var i ServiceDeploy
	err := row.Scan(
		&i.ID,
		&i.ServiceID,
		&i.State,
		&i.ComposeYaml,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FinishedAt,
	)
	return i, err
}

const getService = `-- name: GetService :one
SELECT id, user_id, server_id, name, status, compose_yaml, env, created_at, updated_at, deleted_at FROM services
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetService(ctx context.Context, id pgtype.UUID) (Service, error) {
	row := q.db.QueryRow(ctx, getService, id)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ServerID,
		&i.Name,
		&i.Status,
		&i.ComposeYaml,
		&i.Env,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listServiceDeploys = `-- name: ListServiceDeploys :many
SELECT id, service_id, state, compose_yaml, error, created_at, updated_at, finished_at FROM service_deploys
WHERE service_id = $1
ORDER BY created_at DESC, id DESC
LIMIT $2
`

type ListServiceDeploysParams struct {
	ServiceID pgtype.UUID `json:"service_id"`
	Limit     int32       `json:"limit"`
}

func (q *Queries) ListServiceDeploys(ctx context.Context, arg ListServiceDeploysParams) ([]ServiceDeploy, error) {
	rows, err := q.db.Query(ctx, listServiceDeploys, arg.ServiceID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ServiceDeploy{}
	for rows.Next() {
		var i ServiceDeploy
		if err := rows.Scan(
			&i.ID,
			&i.ServiceID,
			&i.State,
			&i.ComposeYaml,
			&i.Error,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listServicesByUser = `-- name: ListServicesByUser :many
SELECT id, user_id, server_id, name, status, compose_yaml, env, created_at, updated_at, deleted_at FROM services
WHERE user_id = $1 AND deleted_at IS NULL
ORDER BY created_at DESC, id DESC
`

func (q *Queries) ListServicesByUser(ctx context.Context, userID pgtype.UUID) ([]Service, error) {
	rows, err := q.db.Query(ctx, listServicesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Service{}
	for rows.Next() {
		var i Service
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ServerID,
			&i.Name,
			&i.Status,
			&i.ComposeYaml,
			&i.Env,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteService = `-- name: SoftDeleteService :one
UPDATE services
SET status = 'deleting',
    deleted_at = now(),
    updated_at = now()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, user_id, server_id, name, status, compose_yaml, env, created_at, updated_at, deleted_at
`

func (q *Queries) SoftDeleteService(ctx context.Context, id pgtype.UUID) (Service, error) {
	row := q.db.QueryRow(ctx, softDeleteService, id)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ServerID,
		&i.Name,
		&i.Status,
		&i.ComposeYaml,
		&i.Env,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateService = `-- name: UpdateService :one
UPDATE services
SET name = $2,
    compose_yaml = $3,
    env = $4,
    status = $5,
    updated_at = now()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, user_id, server_id, name, status, compose_yaml, env, created_at, updated_at, deleted_at
`

type UpdateServiceParams struct {
	ID          pgtype.UUID `json:"id"`
	Name        string      `json:"name"`
	ComposeYaml string      `json:"compose_yaml"`
	Env         []byte      `json:"env"`
	Status      string      `json:"status"`
}

func (q *Queries) UpdateService(ctx context.Context, arg UpdateServiceParams) (Service, error) {
	row := q.db.QueryRow(ctx, updateService,
		arg.ID,
		arg.Name,
		arg.ComposeYaml,
		arg.Env,
		arg.Status,
	)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ServerID,
		&i.Name,
		&i.Status,
		&i.ComposeYaml,
		&i.Env,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateServiceDeploy = `-- name: UpdateServiceDeploy :one
UPDATE service_deploys
SET state = $2,
    error = $3,
    finished_at = $4,
    updated_at = now()
WHERE id = $1
RETURNING id, service_id, state, compose_yaml, error, created_at, updated_at, finished_at
`

type UpdateServiceDeployParams struct {
	ID         pgtype.UUID        `json:"id"`
	State      string             `json:"state"`
	Error      string             `json:"error"`
	FinishedAt pgtype.Timestamptz `json:"finished_at"`
}

func (q *Queries) UpdateServiceDeploy(ctx context.Context, arg UpdateServiceDeployParams) (ServiceDeploy, error) {
	row := q.db.QueryRow(ctx, updateServiceDeploy,
		arg.ID,
		arg.State,
		arg.Error,
		arg.FinishedAt,
	)
	var i ServiceDeploy
	err := row.Scan(
		&i.ID,
		&i.ServiceID,
		&i.State,
		&i.ComposeYaml,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FinishedAt,
	)
	return i, err
}
