// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (user_id, refresh_hash, expires_at)
VALUES ($1, $2, $3)
RETURNING id, user_id, refresh_hash, expires_at, revoked_at, created_at
`

type CreateSessionParams struct {
	UserID      pgtype.UUID        `json:"user_id"`
	RefreshHash string             `json:"refresh_hash"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession, arg.UserID, arg.RefreshHash, arg.ExpiresAt)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RefreshHash,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteUserSessions = `-- name: DeleteUserSessions :exec
DELETE FROM sessions
WHERE user_id = $1
`

// DeleteUserSessions removes every session of a user, used after a password
// change so the old refresh chain dies with the credential.
func (q *Queries) DeleteUserSessions(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteUserSessions, userID)
	return err
}

const getSessionByRefreshHash = `-- name: GetSessionByRefreshHash :one
SELECT id, user_id, refresh_hash, expires_at, revoked_at, created_at
FROM sessions
WHERE refresh_hash = $1
`

func (q *Queries) GetSessionByRefreshHash(ctx context.Context, refreshHash string) (Session, error) {
	row := q.db.QueryRow(ctx, getSessionByRefreshHash, refreshHash)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RefreshHash,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const revokeSession = `-- name: RevokeSession :exec
UPDATE sessions
SET revoked_at = now()
WHERE refresh_hash = $1
  AND revoked_at IS NULL
`

func (q *Queries) RevokeSession(ctx context.Context, refreshHash string) error {
	_, err := q.db.Exec(ctx, revokeSession, refreshHash)
	return err
}
