// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (user_id, refresh_hash, expires_at, credential_version)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, refresh_hash, expires_at, revoked_at, created_at, credential_version
`

type CreateSessionParams struct {
	UserID            pgtype.UUID        `json:"user_id"`
	RefreshHash       string             `json:"refresh_hash"`
	ExpiresAt         pgtype.Timestamptz `json:"expires_at"`
	CredentialVersion int32              `json:"credential_version"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.UserID,
		arg.RefreshHash,
		arg.ExpiresAt,
		arg.CredentialVersion,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RefreshHash,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.CredentialVersion,
	)
	return i, err
}

const deleteUserSessions = `-- name: DeleteUserSessions :exec
DELETE FROM sessions
WHERE user_id = $1
`

// DeleteUserSessions removes every session of a user, used after a password
// change so the old refresh chain dies with the credential.
func (q *Queries) DeleteUserSessions(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteUserSessions, userID)
	return err
}

const getSessionByRefreshHash = `-- name: GetSessionByRefreshHash :one
SELECT id, user_id, refresh_hash, expires_at, revoked_at, created_at, credential_version
FROM sessions
WHERE refresh_hash = $1
`

func (q *Queries) GetSessionByRefreshHash(ctx context.Context, refreshHash string) (Session, error) {
	row := q.db.QueryRow(ctx, getSessionByRefreshHash, refreshHash)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RefreshHash,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.CredentialVersion,
	)
	return i, err
}

const revokeSession = `-- name: RevokeSession :exec
UPDATE sessions
SET revoked_at = now()
WHERE refresh_hash = $1
  AND revoked_at IS NULL
`

func (q *Queries) RevokeSession(ctx context.Context, refreshHash string) error {
	_, err := q.db.Exec(ctx, revokeSession, refreshHash)
	return err
}

const revokeSessionIfLive = `-- name: RevokeSessionIfLive :one
UPDATE sessions
SET revoked_at = now()
WHERE refresh_hash = $1
  AND revoked_at IS NULL
RETURNING id
`

// RevokeSessionIfLive revokes a session only while it is still live and
// returns its id. Zero rows means the session was already revoked or deleted
// (for example by a password reset racing this rotation), so the caller must
// refuse to issue a replacement.
func (q *Queries) RevokeSessionIfLive(ctx context.Context, refreshHash string) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, revokeSessionIfLive, refreshHash)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}
