// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package sqlc

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const checkSessionLive = `-- name: CheckSessionLive :one
SELECT id
FROM sessions
WHERE id = $1
  AND user_id = $2
  AND revoked_at IS NULL
  AND expires_at > now()
`

type CheckSessionLiveParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

// CheckSessionLive reports whether a session id is a live session of a user
// (present, not revoked, not expired). The guarded bulk delete uses it to
// refuse a stale sid with 409 instead of guessing which row is current (F2).
func (q *Queries) CheckSessionLive(ctx context.Context, arg CheckSessionLiveParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, checkSessionLive, arg.ID, arg.UserID)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (user_id, refresh_hash, expires_at, credential_version, user_agent, ip)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, refresh_hash, expires_at, revoked_at, created_at, credential_version, user_agent, ip, last_used_at
`

type CreateSessionParams struct {
	UserID            pgtype.UUID        `json:"user_id"`
	RefreshHash       string             `json:"refresh_hash"`
	ExpiresAt         pgtype.Timestamptz `json:"expires_at"`
	CredentialVersion int32              `json:"credential_version"`
	UserAgent         *string            `json:"user_agent"`
	Ip                *netip.Addr        `json:"ip"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.UserID,
		arg.RefreshHash,
		arg.ExpiresAt,
		arg.CredentialVersion,
		arg.UserAgent,
		arg.Ip,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RefreshHash,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.CredentialVersion,
		&i.UserAgent,
		&i.Ip,
		&i.LastUsedAt,
	)
	return i, err
}

const deleteOtherSessions = `-- name: DeleteOtherSessions :execrows
DELETE FROM sessions
WHERE user_id = $1
  AND id <> $2
  AND revoked_at IS NULL
`

type DeleteOtherSessionsParams struct {
	UserID pgtype.UUID `json:"user_id"`
	ID     pgtype.UUID `json:"id"`
}

// DeleteOtherSessions deletes every live session of a user except the given
// one (the caller's current session, which keeps working). Already-rotated
// (revoked) rows stay untouched so genuine-theft evidence survives. The store
// wrapper only runs this after proving the given session is live (F2).
func (q *Queries) DeleteOtherSessions(ctx context.Context, arg DeleteOtherSessionsParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteOtherSessions, arg.UserID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions
WHERE refresh_hash = $1
  AND revoked_at IS NULL
`

// DeleteSession removes the session with the given refresh hash only while it
// is still live. Logout uses it instead of RevokeSession so a replayed
// logged-out token reaches the reuse classifier as a deleted row, not a revoked
// one: RevokeFamilyIfStolen returns false (nothing to attribute), so the user's
// other live sessions survive and the refresh is a plain 401. An already-rotated
// (revoked) row is left in place so its reuse-detection evidence survives.
func (q *Queries) DeleteSession(ctx context.Context, refreshHash string) error {
	_, err := q.db.Exec(ctx, deleteSession, refreshHash)
	return err
}

const deleteSessionByID = `-- name: DeleteSessionByID :execrows
DELETE FROM sessions
WHERE id = $1
  AND user_id = $2
  AND revoked_at IS NULL
  AND expires_at > now()
`

type DeleteSessionByIDParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

// DeleteSessionByID deletes one live session scoped to its owner, like logout
// does: a replayed token is then unknown (a plain 401) and can never trigger
// the reuse-detection family revoke (F1). Zero rows means the id is unknown,
// foreign, already revoked (a rotated-away row keeps its reuse evidence), or
// expired (F4): the caller answers 404 either way, so a probe cannot
// distinguish them.
func (q *Queries) DeleteSessionByID(ctx context.Context, arg DeleteSessionByIDParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSessionByID, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteStaleSessions = `-- name: DeleteStaleSessions :execrows
DELETE FROM sessions
WHERE (revoked_at IS NULL AND expires_at < $1)
   OR (revoked_at IS NOT NULL AND revoked_at < $2)
`

type DeleteStaleSessionsParams struct {
	ExpiredBefore pgtype.Timestamptz `json:"expired_before"`
	RevokedBefore pgtype.Timestamptz `json:"revoked_before"`
}

// DeleteStaleSessions drops sessions that expired before the retention cutoff
// and revoked sessions whose revocation predates the reuse window. A revoked
// row is governed only by the revoked cutoff: its expiry must not shrink the
// reuse-detection window, and revoked rows stay the full 30 days so a replayed
// token can still revoke its family. The expired cutoff only buffers
// plain-expired rows before deletion.
func (q *Queries) DeleteStaleSessions(ctx context.Context, arg DeleteStaleSessionsParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteStaleSessions, arg.ExpiredBefore, arg.RevokedBefore)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteUserSessions = `-- name: DeleteUserSessions :exec
DELETE FROM sessions
WHERE user_id = $1
`

// DeleteUserSessions removes every session of a user, used after a password
// change so the old refresh chain dies with the credential.
func (q *Queries) DeleteUserSessions(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteUserSessions, userID)
	return err
}

const getSessionByRefreshHash = `-- name: GetSessionByRefreshHash :one
SELECT id, user_id, refresh_hash, expires_at, revoked_at, created_at, credential_version, user_agent, ip, last_used_at
FROM sessions
WHERE refresh_hash = $1
`

func (q *Queries) GetSessionByRefreshHash(ctx context.Context, refreshHash string) (Session, error) {
	row := q.db.QueryRow(ctx, getSessionByRefreshHash, refreshHash)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RefreshHash,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.CredentialVersion,
		&i.UserAgent,
		&i.Ip,
		&i.LastUsedAt,
	)
	return i, err
}

const listSessionsByUser = `-- name: ListSessionsByUser :many
SELECT id, user_agent, ip, created_at, last_used_at
FROM sessions
WHERE user_id = $1
  AND revoked_at IS NULL
  AND expires_at > $2
ORDER BY last_used_at DESC
LIMIT 50
`

type ListSessionsByUserParams struct {
	UserID    pgtype.UUID        `json:"user_id"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

type ListSessionsByUserRow struct {
	ID         pgtype.UUID        `json:"id"`
	UserAgent  *string            `json:"user_agent"`
	Ip         *netip.Addr        `json:"ip"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	LastUsedAt pgtype.Timestamptz `json:"last_used_at"`
}

// ListSessionsByUser returns the caller's live sessions (not revoked, not
// expired as of the given time), newest last use first, at most 50 rows. The
// existing sessions_user_id_idx serves the per-user lookup: a user holds a
// handful of rows, so no new index (measured: no sequential scan on realistic
// per-user row counts; revisit if the sessions table grows hot).
func (q *Queries) ListSessionsByUser(ctx context.Context, arg ListSessionsByUserParams) ([]ListSessionsByUserRow, error) {
	rows, err := q.db.Query(ctx, listSessionsByUser, arg.UserID, arg.ExpiresAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSessionsByUserRow{}
	for rows.Next() {
		var i ListSessionsByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.UserAgent,
			&i.Ip,
			&i.CreatedAt,
			&i.LastUsedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockUserSessions = `-- name: LockUserSessions :exec
SELECT pg_advisory_xact_lock(hashtextextended($1::text, 0))
`

// LockUserSessions takes the transaction-scoped advisory lock that serializes
// session changes for one user. Both the family-revocation path and the
// rotation acquire it first, so a rotation cannot insert a replacement after a
// reuse-detection snapshot has already read the user's live sessions.
func (q *Queries) LockUserSessions(ctx context.Context, userID string) error {
	_, err := q.db.Exec(ctx, lockUserSessions, userID)
	return err
}

const revokeSession = `-- name: RevokeSession :exec
UPDATE sessions
SET revoked_at = now()
WHERE refresh_hash = $1
  AND revoked_at IS NULL
`

func (q *Queries) RevokeSession(ctx context.Context, refreshHash string) error {
	_, err := q.db.Exec(ctx, revokeSession, refreshHash)
	return err
}

const revokeSessionIfLive = `-- name: RevokeSessionIfLive :one
UPDATE sessions
SET revoked_at = now()
WHERE refresh_hash = $1
  AND revoked_at IS NULL
RETURNING id
`

// RevokeSessionIfLive revokes a session only while it is still live and
// returns its id. Zero rows means the session was already revoked or deleted
// (for example by a password reset racing this rotation), so the caller must
// refuse to issue a replacement.
func (q *Queries) RevokeSessionIfLive(ctx context.Context, refreshHash string) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, revokeSessionIfLive, refreshHash)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const revokeUserSessions = `-- name: RevokeUserSessions :exec
UPDATE sessions
SET revoked_at = now()
WHERE user_id = $1
  AND revoked_at IS NULL
`

// RevokeUserSessions revokes every live session of a user. Refresh-token reuse
// detection calls it when a replayed token reveals a possible theft: every
// device is forced to re-authenticate.
func (q *Queries) RevokeUserSessions(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, revokeUserSessions, userID)
	return err
}

const rotateSession = `-- name: RotateSession :one
WITH revoked AS (
    UPDATE sessions AS s
    SET revoked_at = now()
    WHERE s.refresh_hash = $6
      AND s.revoked_at IS NULL
    RETURNING s.user_id, s.created_at
)
INSERT INTO sessions (user_id, refresh_hash, expires_at, credential_version, user_agent, ip, created_at)
SELECT r.user_id, $1, $2, $3, $4, $5, r.created_at
FROM revoked AS r
RETURNING id, user_id, refresh_hash, expires_at, revoked_at, created_at, credential_version, user_agent, ip, last_used_at
`

type RotateSessionParams struct {
	NewRefreshHash     string             `json:"new_refresh_hash"`
	ExpiresAt          pgtype.Timestamptz `json:"expires_at"`
	CredentialVersion  int32              `json:"credential_version"`
	UserAgent          *string            `json:"user_agent"`
	Ip                 *netip.Addr        `json:"ip"`
	RevokedRefreshHash string             `json:"revoked_refresh_hash"`
}

// RotateSession atomically revokes the presented live session and inserts its
// replacement in one statement, so a failed insert or a cancelled request
// cannot consume the user's only refresh token. Zero rows (pgx.ErrNoRows)
// means the presented session was already revoked or deleted, so the caller
// must refuse to issue a replacement. The replacement inherits the original
// sign-in created_at (F3: the list's Created means sign-in time, not last
// rotation); last_used_at is the rotation time via the column default.
func (q *Queries) RotateSession(ctx context.Context, arg RotateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, rotateSession,
		arg.NewRefreshHash,
		arg.ExpiresAt,
		arg.CredentialVersion,
		arg.UserAgent,
		arg.Ip,
		arg.RevokedRefreshHash,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RefreshHash,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.CredentialVersion,
		&i.UserAgent,
		&i.Ip,
		&i.LastUsedAt,
	)
	return i, err
}
