// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: teams.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const acceptInvite = `-- name: AcceptInvite :one
UPDATE invites
SET accepted_at = now()
WHERE token_hash = $1 AND accepted_at IS NULL AND expires_at > now()
RETURNING id, team_id, email, role, token_hash, invited_by, expires_at, accepted_at, created_at
`

// AcceptInvite consumes a pending, unexpired invite. A replayed, expired or
// unknown token matches no row, so the caller can never double-accept.
func (q *Queries) AcceptInvite(ctx context.Context, tokenHash string) (Invite, error) {
	row := q.db.QueryRow(ctx, acceptInvite, tokenHash)
	var i Invite
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Email,
		&i.Role,
		&i.TokenHash,
		&i.InvitedBy,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.CreatedAt,
	)
	return i, err
}

const countTeamOwners = `-- name: CountTeamOwners :one
SELECT count(*) FROM team_members WHERE team_id = $1 AND role = 'owner'
`

func (q *Queries) CountTeamOwners(ctx context.Context, teamID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countTeamOwners, teamID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createInvite = `-- name: CreateInvite :one
INSERT INTO invites (team_id, email, role, token_hash, invited_by, expires_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, team_id, email, role, token_hash, invited_by, expires_at, accepted_at, created_at
`

type CreateInviteParams struct {
	TeamID    pgtype.UUID        `json:"team_id"`
	Email     string             `json:"email"`
	Role      string             `json:"role"`
	TokenHash string             `json:"token_hash"`
	InvitedBy pgtype.UUID        `json:"invited_by"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateInvite(ctx context.Context, arg CreateInviteParams) (Invite, error) {
	row := q.db.QueryRow(ctx, createInvite,
		arg.TeamID,
		arg.Email,
		arg.Role,
		arg.TokenHash,
		arg.InvitedBy,
		arg.ExpiresAt,
	)
	var i Invite
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Email,
		&i.Role,
		&i.TokenHash,
		&i.InvitedBy,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createTeam = `-- name: CreateTeam :one
INSERT INTO teams (id, name, is_personal)
VALUES ($1, $2, $3)
RETURNING id, name, is_personal, created_at, updated_at
`

type CreateTeamParams struct {
	ID         pgtype.UUID `json:"id"`
	Name       string      `json:"name"`
	IsPersonal bool        `json:"is_personal"`
}

func (q *Queries) CreateTeam(ctx context.Context, arg CreateTeamParams) (Team, error) {
	row := q.db.QueryRow(ctx, createTeam, arg.ID, arg.Name, arg.IsPersonal)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.IsPersonal,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTeamMember = `-- name: CreateTeamMember :one
INSERT INTO team_members (team_id, user_id, role)
VALUES ($1, $2, $3)
RETURNING team_id, user_id, role, created_at
`

type CreateTeamMemberParams struct {
	TeamID pgtype.UUID `json:"team_id"`
	UserID pgtype.UUID `json:"user_id"`
	Role   string      `json:"role"`
}

func (q *Queries) CreateTeamMember(ctx context.Context, arg CreateTeamMemberParams) (TeamMember, error) {
	row := q.db.QueryRow(ctx, createTeamMember, arg.TeamID, arg.UserID, arg.Role)
	var i TeamMember
	err := row.Scan(
		&i.TeamID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const deleteInvite = `-- name: DeleteInvite :exec
DELETE FROM invites WHERE id = $1 AND team_id = $2
`

type DeleteInviteParams struct {
	ID     pgtype.UUID `json:"id"`
	TeamID pgtype.UUID `json:"team_id"`
}

func (q *Queries) DeleteInvite(ctx context.Context, arg DeleteInviteParams) error {
	_, err := q.db.Exec(ctx, deleteInvite, arg.ID, arg.TeamID)
	return err
}

const deleteTeam = `-- name: DeleteTeam :exec
DELETE FROM teams WHERE id = $1
`

func (q *Queries) DeleteTeam(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteTeam, id)
	return err
}

const deleteTeamMember = `-- name: DeleteTeamMember :exec
DELETE FROM team_members WHERE team_id = $1 AND user_id = $2
`

type DeleteTeamMemberParams struct {
	TeamID pgtype.UUID `json:"team_id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) DeleteTeamMember(ctx context.Context, arg DeleteTeamMemberParams) error {
	_, err := q.db.Exec(ctx, deleteTeamMember, arg.TeamID, arg.UserID)
	return err
}

const getInviteByTokenHash = `-- name: GetInviteByTokenHash :one
SELECT id, team_id, email, role, token_hash, invited_by, expires_at, accepted_at, created_at FROM invites WHERE token_hash = $1
`

func (q *Queries) GetInviteByTokenHash(ctx context.Context, tokenHash string) (Invite, error) {
	row := q.db.QueryRow(ctx, getInviteByTokenHash, tokenHash)
	var i Invite
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Email,
		&i.Role,
		&i.TokenHash,
		&i.InvitedBy,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getTeam = `-- name: GetTeam :one
SELECT id, name, is_personal, created_at, updated_at FROM teams WHERE id = $1
`

func (q *Queries) GetTeam(ctx context.Context, id pgtype.UUID) (Team, error) {
	row := q.db.QueryRow(ctx, getTeam, id)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.IsPersonal,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTeamForUser = `-- name: GetTeamForUser :one
SELECT t.id, t.name, t.is_personal, t.created_at, t.updated_at, m.role AS member_role
FROM teams t
JOIN team_members m ON m.team_id = t.id
WHERE t.id = $1 AND m.user_id = $2
`

type GetTeamForUserParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

type GetTeamForUserRow struct {
	ID         pgtype.UUID        `json:"id"`
	Name       string             `json:"name"`
	IsPersonal bool               `json:"is_personal"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	MemberRole string             `json:"member_role"`
}

// GetTeamForUser returns one team together with the caller's role, or no row
// when the caller is not a member. It is the authorization read of every
// team-scoped route.
func (q *Queries) GetTeamForUser(ctx context.Context, arg GetTeamForUserParams) (GetTeamForUserRow, error) {
	row := q.db.QueryRow(ctx, getTeamForUser, arg.ID, arg.UserID)
	var i GetTeamForUserRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.IsPersonal,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MemberRole,
	)
	return i, err
}

const getTeamMember = `-- name: GetTeamMember :one
SELECT team_id, user_id, role, created_at FROM team_members WHERE team_id = $1 AND user_id = $2
`

type GetTeamMemberParams struct {
	TeamID pgtype.UUID `json:"team_id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) GetTeamMember(ctx context.Context, arg GetTeamMemberParams) (TeamMember, error) {
	row := q.db.QueryRow(ctx, getTeamMember, arg.TeamID, arg.UserID)
	var i TeamMember
	err := row.Scan(
		&i.TeamID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const listInvitesByTeam = `-- name: ListInvitesByTeam :many
SELECT id, team_id, email, role, token_hash, invited_by, expires_at, accepted_at, created_at FROM invites
WHERE team_id = $1
ORDER BY created_at DESC, id DESC
`

func (q *Queries) ListInvitesByTeam(ctx context.Context, teamID pgtype.UUID) ([]Invite, error) {
	rows, err := q.db.Query(ctx, listInvitesByTeam, teamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Invite{}
	for rows.Next() {
		var i Invite
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.Email,
			&i.Role,
			&i.TokenHash,
			&i.InvitedBy,
			&i.ExpiresAt,
			&i.AcceptedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeamMembers = `-- name: ListTeamMembers :many
SELECT m.user_id, m.role, m.created_at, u.email
FROM team_members m
JOIN users u ON u.id = m.user_id
WHERE m.team_id = $1
ORDER BY m.created_at ASC, m.user_id ASC
`

type ListTeamMembersRow struct {
	UserID    pgtype.UUID        `json:"user_id"`
	Role      string             `json:"role"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	Email     string             `json:"email"`
}

func (q *Queries) ListTeamMembers(ctx context.Context, teamID pgtype.UUID) ([]ListTeamMembersRow, error) {
	rows, err := q.db.Query(ctx, listTeamMembers, teamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTeamMembersRow{}
	for rows.Next() {
		var i ListTeamMembersRow
		if err := rows.Scan(
			&i.UserID,
			&i.Role,
			&i.CreatedAt,
			&i.Email,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeamsByUser = `-- name: ListTeamsByUser :many
SELECT t.id, t.name, t.is_personal, t.created_at, t.updated_at, m.role AS member_role
FROM teams t
JOIN team_members m ON m.team_id = t.id
WHERE m.user_id = $1
ORDER BY t.is_personal ASC, t.created_at DESC, t.id DESC
`

type ListTeamsByUserRow struct {
	ID         pgtype.UUID        `json:"id"`
	Name       string             `json:"name"`
	IsPersonal bool               `json:"is_personal"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	MemberRole string             `json:"member_role"`
}

func (q *Queries) ListTeamsByUser(ctx context.Context, userID pgtype.UUID) ([]ListTeamsByUserRow, error) {
	rows, err := q.db.Query(ctx, listTeamsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTeamsByUserRow{}
	for rows.Next() {
		var i ListTeamsByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.IsPersonal,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.MemberRole,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTeam = `-- name: UpdateTeam :one
UPDATE teams
SET name = $2,
    updated_at = now()
WHERE id = $1
RETURNING id, name, is_personal, created_at, updated_at
`

type UpdateTeamParams struct {
	ID   pgtype.UUID `json:"id"`
	Name string      `json:"name"`
}

func (q *Queries) UpdateTeam(ctx context.Context, arg UpdateTeamParams) (Team, error) {
	row := q.db.QueryRow(ctx, updateTeam, arg.ID, arg.Name)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.IsPersonal,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTeamMemberRole = `-- name: UpdateTeamMemberRole :one
UPDATE team_members
SET role = $3
WHERE team_id = $1 AND user_id = $2
RETURNING team_id, user_id, role, created_at
`

type UpdateTeamMemberRoleParams struct {
	TeamID pgtype.UUID `json:"team_id"`
	UserID pgtype.UUID `json:"user_id"`
	Role   string      `json:"role"`
}

func (q *Queries) UpdateTeamMemberRole(ctx context.Context, arg UpdateTeamMemberRoleParams) (TeamMember, error) {
	row := q.db.QueryRow(ctx, updateTeamMemberRole, arg.TeamID, arg.UserID, arg.Role)
	var i TeamMember
	err := row.Scan(
		&i.TeamID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}
