// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: update_schedule.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getUpdateSchedule = `-- name: GetUpdateSchedule :one
SELECT check_enabled, auto_apply, channel, frequency, interval_minutes, at_time, weekday, updated_at
FROM update_schedule
WHERE id = true
`

type GetUpdateScheduleRow struct {
	CheckEnabled    bool               `json:"check_enabled"`
	AutoApply       bool               `json:"auto_apply"`
	Channel         string             `json:"channel"`
	Frequency       string             `json:"frequency"`
	IntervalMinutes int32              `json:"interval_minutes"`
	AtTime          string             `json:"at_time"`
	Weekday         int16              `json:"weekday"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetUpdateSchedule(ctx context.Context) (GetUpdateScheduleRow, error) {
	row := q.db.QueryRow(ctx, getUpdateSchedule)
	var i GetUpdateScheduleRow
	err := row.Scan(
		&i.CheckEnabled,
		&i.AutoApply,
		&i.Channel,
		&i.Frequency,
		&i.IntervalMinutes,
		&i.AtTime,
		&i.Weekday,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertUpdateSchedule = `-- name: UpsertUpdateSchedule :one
INSERT INTO update_schedule (id, check_enabled, auto_apply, channel, frequency, interval_minutes, at_time, weekday)
VALUES (true, $1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (id) DO UPDATE SET
    check_enabled = EXCLUDED.check_enabled,
    auto_apply = EXCLUDED.auto_apply,
    channel = EXCLUDED.channel,
    frequency = EXCLUDED.frequency,
    interval_minutes = EXCLUDED.interval_minutes,
    at_time = EXCLUDED.at_time,
    weekday = EXCLUDED.weekday,
    updated_at = now()
RETURNING check_enabled, auto_apply, channel, frequency, interval_minutes, at_time, weekday, updated_at
`

type UpsertUpdateScheduleParams struct {
	CheckEnabled    bool   `json:"check_enabled"`
	AutoApply       bool   `json:"auto_apply"`
	Channel         string `json:"channel"`
	Frequency       string `json:"frequency"`
	IntervalMinutes int32  `json:"interval_minutes"`
	AtTime          string `json:"at_time"`
	Weekday         int16  `json:"weekday"`
}

type UpsertUpdateScheduleRow struct {
	CheckEnabled    bool               `json:"check_enabled"`
	AutoApply       bool               `json:"auto_apply"`
	Channel         string             `json:"channel"`
	Frequency       string             `json:"frequency"`
	IntervalMinutes int32              `json:"interval_minutes"`
	AtTime          string             `json:"at_time"`
	Weekday         int16              `json:"weekday"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpsertUpdateSchedule(ctx context.Context, arg UpsertUpdateScheduleParams) (UpsertUpdateScheduleRow, error) {
	row := q.db.QueryRow(ctx, upsertUpdateSchedule,
		arg.CheckEnabled,
		arg.AutoApply,
		arg.Channel,
		arg.Frequency,
		arg.IntervalMinutes,
		arg.AtTime,
		arg.Weekday,
	)
	var i UpsertUpdateScheduleRow
	err := row.Scan(
		&i.CheckEnabled,
		&i.AutoApply,
		&i.Channel,
		&i.Frequency,
		&i.IntervalMinutes,
		&i.AtTime,
		&i.Weekday,
		&i.UpdatedAt,
	)
	return i, err
}
