// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const bumpCredentialVersion = `-- name: BumpCredentialVersion :exec
UPDATE users
SET credential_version = credential_version + 1
WHERE id = $1
`

// BumpCredentialVersion advances the account's credential version. It runs
// inside the password-reset transaction: every session minted before the bump
// carries the older version and Refresh refuses it.
func (q *Queries) BumpCredentialVersion(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, bumpCredentialVersion, id)
	return err
}

const countUsers = `-- name: CountUsers :one
SELECT count(*) FROM users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createFirstUser = `-- name: CreateFirstUser :one
INSERT INTO users (email, password_hash)
SELECT $1, $2
WHERE NOT EXISTS (SELECT 1 FROM users)
RETURNING id, email, created_at, password_hash, avatar, updated_at, credential_version
`

type CreateFirstUserParams struct {
	Email        string  `json:"email"`
	PasswordHash *string `json:"password_hash"`
}

// CreateFirstUser inserts the bootstrap account only while the table is empty,
// so two concurrent first registrations cannot both succeed (P-A2). Zero rows
// means an account already exists and the caller must fall back to the invite
// path.
func (q *Queries) CreateFirstUser(ctx context.Context, arg CreateFirstUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createFirstUser, arg.Email, arg.PasswordHash)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.CreatedAt,
		&i.PasswordHash,
		&i.Avatar,
		&i.UpdatedAt,
		&i.CredentialVersion,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, password_hash)
VALUES ($1, $2)
RETURNING id, email, created_at, password_hash, avatar, updated_at, credential_version
`

type CreateUserParams struct {
	Email        string  `json:"email"`
	PasswordHash *string `json:"password_hash"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Email, arg.PasswordHash)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.CreatedAt,
		&i.PasswordHash,
		&i.Avatar,
		&i.UpdatedAt,
		&i.CredentialVersion,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, created_at, password_hash, avatar, updated_at, credential_version
FROM users
WHERE lower(email) = lower($1)
`

func (q *Queries) GetUserByEmail(ctx context.Context, lower string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, lower)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.CreatedAt,
		&i.PasswordHash,
		&i.Avatar,
		&i.UpdatedAt,
		&i.CredentialVersion,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, created_at, password_hash, avatar, updated_at, credential_version
FROM users
WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.CreatedAt,
		&i.PasswordHash,
		&i.Avatar,
		&i.UpdatedAt,
		&i.CredentialVersion,
	)
	return i, err
}

const updateUserAvatar = `-- name: UpdateUserAvatar :one
UPDATE users
SET avatar = $2, updated_at = now()
WHERE id = $1
RETURNING id, email, created_at, password_hash, avatar, updated_at, credential_version
`

type UpdateUserAvatarParams struct {
	ID     pgtype.UUID `json:"id"`
	Avatar *string     `json:"avatar"`
}

// UpdateUserAvatar replaces the account's stored OAuth avatar URL. The caller
// (OAuth login) validates the URL against the shared allowlist first; a nil
// avatar clears the stored value. It returns the updated row so the login can
// mint its session from the fresh read.
func (q *Queries) UpdateUserAvatar(ctx context.Context, arg UpdateUserAvatarParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserAvatar, arg.ID, arg.Avatar)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.CreatedAt,
		&i.PasswordHash,
		&i.Avatar,
		&i.UpdatedAt,
		&i.CredentialVersion,
	)
	return i, err
}

const updateUserPasswordHash = `-- name: UpdateUserPasswordHash :exec
UPDATE users
SET password_hash = $2, updated_at = now()
WHERE lower(email) = lower($1)
`

type UpdateUserPasswordHashParams struct {
	Lower        string  `json:"lower"`
	PasswordHash *string `json:"password_hash"`
}

// UpdateUserPasswordHash replaces the password hash of the account with the
// given (normalized, lowercase) email; callers resolve the exact address via
// GetUserByEmail first.
func (q *Queries) UpdateUserPasswordHash(ctx context.Context, arg UpdateUserPasswordHashParams) error {
	_, err := q.db.Exec(ctx, updateUserPasswordHash, arg.Lower, arg.PasswordHash)
	return err
}
