// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: webhooks.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createApplicationWebhook = `-- name: CreateApplicationWebhook :one
INSERT INTO application_webhooks (application_id, provider, repo, hook_id, secret, url)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, application_id, provider, repo, hook_id, secret, url, created_at, updated_at
`

type CreateApplicationWebhookParams struct {
	ApplicationID pgtype.UUID `json:"application_id"`
	Provider      string      `json:"provider"`
	Repo          string      `json:"repo"`
	HookID        string      `json:"hook_id"`
	Secret        string      `json:"secret"`
	Url           string      `json:"url"`
}

func (q *Queries) CreateApplicationWebhook(ctx context.Context, arg CreateApplicationWebhookParams) (ApplicationWebhook, error) {
	row := q.db.QueryRow(ctx, createApplicationWebhook,
		arg.ApplicationID,
		arg.Provider,
		arg.Repo,
		arg.HookID,
		arg.Secret,
		arg.Url,
	)
	var i ApplicationWebhook
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.Provider,
		&i.Repo,
		&i.HookID,
		&i.Secret,
		&i.Url,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createWebhookEvent = `-- name: CreateWebhookEvent :one
INSERT INTO webhook_events (application_id, provider, event, delivery_id, ref, commit_sha)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, application_id, provider, event, delivery_id, ref, commit_sha, deployment_id, received_at
`

type CreateWebhookEventParams struct {
	ApplicationID pgtype.UUID `json:"application_id"`
	Provider      string      `json:"provider"`
	Event         string      `json:"event"`
	DeliveryID    string      `json:"delivery_id"`
	Ref           string      `json:"ref"`
	CommitSha     string      `json:"commit_sha"`
}

func (q *Queries) CreateWebhookEvent(ctx context.Context, arg CreateWebhookEventParams) (WebhookEvent, error) {
	row := q.db.QueryRow(ctx, createWebhookEvent,
		arg.ApplicationID,
		arg.Provider,
		arg.Event,
		arg.DeliveryID,
		arg.Ref,
		arg.CommitSha,
	)
	var i WebhookEvent
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.Provider,
		&i.Event,
		&i.DeliveryID,
		&i.Ref,
		&i.CommitSha,
		&i.DeploymentID,
		&i.ReceivedAt,
	)
	return i, err
}

const deleteApplicationWebhook = `-- name: DeleteApplicationWebhook :one
DELETE FROM application_webhooks
WHERE application_id = $1
RETURNING id, application_id, provider, repo, hook_id, secret, url, created_at, updated_at
`

func (q *Queries) DeleteApplicationWebhook(ctx context.Context, applicationID pgtype.UUID) (ApplicationWebhook, error) {
	row := q.db.QueryRow(ctx, deleteApplicationWebhook, applicationID)
	var i ApplicationWebhook
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.Provider,
		&i.Repo,
		&i.HookID,
		&i.Secret,
		&i.Url,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteWebhookEvent = `-- name: DeleteWebhookEvent :exec
DELETE FROM webhook_events
WHERE id = $1
`

func (q *Queries) DeleteWebhookEvent(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteWebhookEvent, id)
	return err
}

const getApplicationForUser = `-- name: GetApplicationForUser :one
SELECT id, user_id, server_id, name, provider, repo, clone_url, branch, build_pack, base_domain, port, host_port, created_at, updated_at, base_domain_disabled, team_id, is_preview FROM applications
WHERE id = $1 AND user_id = $2
`

type GetApplicationForUserParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) GetApplicationForUser(ctx context.Context, arg GetApplicationForUserParams) (Application, error) {
	row := q.db.QueryRow(ctx, getApplicationForUser, arg.ID, arg.UserID)
	var i Application
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ServerID,
		&i.Name,
		&i.Provider,
		&i.Repo,
		&i.CloneUrl,
		&i.Branch,
		&i.BuildPack,
		&i.BaseDomain,
		&i.Port,
		&i.HostPort,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BaseDomainDisabled,
		&i.TeamID,
		&i.IsPreview,
	)
	return i, err
}

const getApplicationWebhookByApp = `-- name: GetApplicationWebhookByApp :one
SELECT id, application_id, provider, repo, hook_id, secret, url, created_at, updated_at FROM application_webhooks
WHERE application_id = $1
`

func (q *Queries) GetApplicationWebhookByApp(ctx context.Context, applicationID pgtype.UUID) (ApplicationWebhook, error) {
	row := q.db.QueryRow(ctx, getApplicationWebhookByApp, applicationID)
	var i ApplicationWebhook
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.Provider,
		&i.Repo,
		&i.HookID,
		&i.Secret,
		&i.Url,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listWebhookTargetsForRepo = `-- name: ListWebhookTargetsForRepo :many
SELECT w.application_id, w.hook_id, w.secret, w.url,
       a.user_id, a.team_id, a.provider, a.repo, a.branch, a.clone_url,
       a.name, a.base_domain
FROM application_webhooks w
JOIN applications a ON a.id = w.application_id
WHERE w.provider = $1 AND lower(w.repo) = $2
`

type ListWebhookTargetsForRepoParams struct {
	Provider string `json:"provider"`
	Repo     string `json:"repo"`
}

type ListWebhookTargetsForRepoRow struct {
	ApplicationID pgtype.UUID `json:"application_id"`
	HookID        string      `json:"hook_id"`
	Secret        string      `json:"secret"`
	Url           string      `json:"url"`
	UserID        pgtype.UUID `json:"user_id"`
	TeamID        pgtype.UUID `json:"team_id"`
	Provider      string      `json:"provider"`
	Repo          string      `json:"repo"`
	Branch        string      `json:"branch"`
	CloneUrl      string      `json:"clone_url"`
	Name          string      `json:"name"`
	BaseDomain    string      `json:"base_domain"`
}

func (q *Queries) ListWebhookTargetsForRepo(ctx context.Context, arg ListWebhookTargetsForRepoParams) ([]ListWebhookTargetsForRepoRow, error) {
	rows, err := q.db.Query(ctx, listWebhookTargetsForRepo, arg.Provider, arg.Repo)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWebhookTargetsForRepoRow{}
	for rows.Next() {
		var i ListWebhookTargetsForRepoRow
		if err := rows.Scan(
			&i.ApplicationID,
			&i.HookID,
			&i.Secret,
			&i.Url,
			&i.UserID,
			&i.TeamID,
			&i.Provider,
			&i.Repo,
			&i.Branch,
			&i.CloneUrl,
			&i.Name,
			&i.BaseDomain,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateWebhookEventDeployment = `-- name: UpdateWebhookEventDeployment :exec
UPDATE webhook_events
SET deployment_id = $2
WHERE id = $1
`

type UpdateWebhookEventDeploymentParams struct {
	ID           pgtype.UUID `json:"id"`
	DeploymentID pgtype.UUID `json:"deployment_id"`
}

func (q *Queries) UpdateWebhookEventDeployment(ctx context.Context, arg UpdateWebhookEventDeploymentParams) error {
	_, err := q.db.Exec(ctx, updateWebhookEventDeployment, arg.ID, arg.DeploymentID)
	return err
}
